### ISSUE TITLE
Weird mouse speed in menus

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#103]
Mouse speed is different in some menus and seems to warp a bit in pip-boy(this may just be a readius mod thing); I hadn't opened the normal pipboy at any time

_Originally posted by @Mihli in #78 (test report)_

**Comment by hazelnot** [comment]
As far as I can tell this is just a Wine bug. The cursor is weird in menus even in Windows, and Wine is probably amplifying it.
