### ISSUE TITLE
Vortex Mod Manager cant find my games

### ISSUE THREAD

**Issue by Preceptus** [rockerbacon/modorganizer2-linux-installer#122]
I cannot get Vortex to identify Final Fantasy XII Steam version.
Supported games only shows 54 games.
Looking for help.

**Comment by rockerbacon** [comment]
Automatic detection only works for some Creation Engine Games, Final Fantasy XII not being one of them.

Vortex currently supports more than 54 games but the version supplied with the installer is outdated and likely doesn't support as many games.

**Comment by Preceptus** [comment]
> Automatic detection only works for some Creation Engine Games, Final Fantasy XII not being one of them.
> 
> Vortex currently supports more than 54 games but the version supplied with the installer is outdated and likely doesn't support as many games.

I had FFXII modding working before, so it did work. 
I am not sure why it does not detect it anymore, it is not even under supported games, whereas before it was.

**Comment by dantepd82-source** [comment]
Issue isn't fixed. When you try to manually set the target folder, Vortex will continue to point to steamapps\common\FINAL FANTASY XII THE ZODIAC AGE, no matter how many times you try to correct it.
