### ISSUE TITLE
Handle multiple steam installations

### ISSUE THREAD

**Issue by BafDyce** [rockerbacon/modorganizer2-linux-installer#123]
On my system, Steam is installed twice: Once natively and once in a flatpak. I mainly use the flatpak version (and the native installation only for VR games). However, the `utils/find-library-for-appid.sh` script only searches for the game in the first Steam installation it finds (which is the native version by default).

Ideally, if the script cannot find the appdir in a given steam installation, it should also check the other potential steam directories.

**Comment by rockerbacon** [comment]
Looking into it some more, there are still other parts of the scripts which only look at `$HOME/.steam/root`:

- Library path building in both `proton-launcher.sh` and `wine-launcher.sh`
- Custom Proton distributions search in `proton-launcher.sh`

**Comment by BafDyce** [comment]
Would it be possible to adjust all the scripts so that the user can simply supply the path of their steam installation directory? Thanks for your quick response btw :)

**Comment by rockerbacon** [comment]
This should no longer be a problem in the latest version, `utils/find-library-for-appid.sh` seems to properly search across multiple installations and `proton-launcher.sh`, `wine-launcher.sh` have been removed.
