### ISSUE TITLE
Can't Launch Wrye Bash Python Version

### ISSUE THREAD

**Issue by ThisNekoGuy** [rockerbacon/modorganizer2-linux-installer#133]
I tried following the Wine "guide" here (though the requirements.txt wasn't something I could figure out):

https://github.com/wrye-bash/wrye-bash

however MO2 doesn't like running the Wrye Bash python script for whatever reason (even after using protontricks to install Python27).

**Comment by ThisNekoGuy** [comment]
Also, attempting to run the Standalone Wrye Bash Windows executable throws a message about how it can't detect the game folder and to pass an argument for it but, when I do that, Wrye Bash just doesn't launch at all.

**Comment by rockerbacon** [comment]
I could launch the [beta version on Nexus](https://www.nexusmods.com/skyrim/mods/1840) just fine. I just downloaded the standalone executable and added the .exe as an executable in Mod Organizer 2, no winetricks required.

**Comment by ThisNekoGuy** [comment]
I just tried to launch the beta version, and it did launch, but it disables all of my plugins on startup and doesn't see where any of them are for whatever reason.
