### ISSUE TITLE
When trying to add The Mod Configuration Menu, the install fails when trying to run the external installer

### ISSUE THREAD

**Issue by flan7** [rockerbacon/modorganizer2-linux-installer#144]
I receive this message in the console:

```
[2020-08-24 15:48:37.445 W] WARNING: The extension of this file did not match the expected extensions for this format! You may want to inform the mod author.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Unhandled page fault on read access to 0000000000000068 at address 000000007AC2EEB1 (thread 0578), starting debugger...
[2020-08-24 15:48:44.028 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
[2020-08-24 15:48:44.057 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
[2020-08-24 15:48:44.091 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
[2020-08-24 15:48:45.116 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
[2020-08-24 15:48:45.149 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
[2020-08-24 15:48:45.183 E] QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
```

It pops up "could not compile script, errors found", then another pop up containing "Error code 3221225477". 

This also happens when installing alternate repairing, another mod using the same type of installer

**Comment by Computious** [comment]
I am having this same problem. Bump

**Comment by SFMason** [comment]
I'm getting the same issue on Skyrim, for mods SkyUI and A Quality World Map. I can't confirm this, but it looks like it's any mod that includes a script.cs file in the FOMOD installer. This would imply that the wine prefix is missing a .NET component to compile and run the script.
If it helps, both scripts are including the same namespaces:
```
using System.Text;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using System.ComponentModel;
using System.Drawing;
using fomm.Scripting;
using System.Globalization;
using System;
```
Unfortunately I can't expand the 'details' dropdown on the error message for more specific info.

**Comment by SFMason** [comment]
> I'm getting the same issue on Skyrim, for mods SkyUI and A Quality World Map. I can't confirm this, but it looks like it's any mod that includes a script.cs file in the FOMOD installer. This would imply that the wine prefix is missing a .NET component to compile and run the script.
> If it helps, both scripts are including the same namespaces:
> 
> ```
> using System.Text;
> using System.Collections.Generic;
> using System.IO;
> using System.Text.RegularExpressions;
> using System.Windows.Forms;
> using System.ComponentModel;
> using System.Drawing;
> using fomm.Scripting;
> using System.Globalization;
> using System;
> ```
> 
> Unfortunately I can't expand the 'details' dropdown on the error message for more specific info.

Looks like this might be at least part of the problem. I installed dotnet48 with protontricks, and it did allow me to run the installer (specifically for mod https://www.nexusmods.com/skyrim/mods/4929). However, the installer still failed when clicking 'Install' so there must be something else missing.

**Comment by fighuass** [comment]
Had this problem with SkyUI, but I got it to work by making a SkyUI folder where MO2 stores mods, and then simply copy pasting the .esp and .bsa. MO2 says it can't get it to work, but somehow it does.

**Comment by deane-c64** [comment]
Technically, at Best Fomod install is bad. at worse is whats happening here. Fomod workaround is simply to install manually inside Mod folder!

**Comment by TheDrifter363** [comment]
Wanted to update this post. Using the latest installer as of this date, the mod configuration menu FOMOD refuses to install. It crashes. I'm not sure if it's a dotnet issue, since the FOMOD says it's written in C#.

> [2022-01-14 20:33:40.866 W] The extension of this file did not match the expected
 extensions for this format.
[2022-01-14 20:33:43.693 W] C# [0]: Metadata file `System.Runtime.dll' could not
 be found
