### ISSUE TITLE
MO2 just doesn't open.

### ISSUE THREAD

**Issue by wizradicool** [rockerbacon/modorganizer2-linux-installer#147]
I can't even see any sort of error or anything, it just stops.

```
Running /home/altoids/Games/mod-organizer-2/run.sh
Initial process has started with pid 12544
Waiting for game to be considered started (first non-excluded process started)
Searching for Steam in '/home/altoids/.steam'
Found Steam
Searching for Steam in '/home/altoids/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Searching for game in library '/home/altoids/.steam/steam'
Found game
Searching for 'Proton 5.*' in library '/home/altoids/.steam/steam'
Found Proton

	PATH='/home/altoids/.steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/altoids/.steam/ubuntu12_32/steam-runtime/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
	LD_LIBRARY_PATH='/home/altoids/.steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/altoids/.steam/ubuntu12_32/steam-runtime/pinned_libs_64:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32:/libx32:/usr/libx32:/lib:/usr/lib:/usr/lib/i386-linux-gnu/sse2:/home/altoids/.steam/ubuntu12_32/steam-runtime/lib/i368-linux-gnu:/home/altoids/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/altoids/.steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/altoids/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/altoids/.steam/ubuntu12_32/steam-runtime/lib:/home/altoids/.steam/ubuntu12_32/steam-runtime/usr/lib' \
	STEAM_COMPAT_DATA_PATH='/home/altoids/.steam/steam/steamapps/compatdata/22380' \
	SteamGameId=22380 \
	SteamAppId=22380 \
	 \
	\
	'/home/altoids/.steam/steam/steamapps/common/Proton 5.0/proton' run '/home/altoids/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 


esync: up and running.
Setting breakpad minidump AppID = 22380
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198071788256 [API loaded no]
Initial process has exited.
All children have exited.
Exit with returncode 0

```

**Comment by rockerbacon** [comment]
Having 0 error logs is rather odd. Are you using the [latest stable](https://github.com/rockerbacon/lutris-skyrimse-installers/releases/tag/2.8.4) version from this repo? What distro are you using?

**Comment by wizradicool** [comment]
I tried both the latest stable version as well as the experimental one, and I am on Xubuntu bionic.

**Comment by rockerbacon** [comment]
Try forcing Steam to launch MO2 and see if it behaves any different:

Right click on Fallout New Vegas > Properties > Tab "General" > Set Launch Options > paste this into the text box:

```
"$HOME/.config/modorganizer2/instances/newvegas/run.sh" && echo %command% >/dev/null
```

Then launch the game on Steam

**Comment by wizradicool** [comment]
That didn't seem to do anything. If it means anything, I have `PROTON_USE_D9VK=1 %command%` in my launch options as well, this is necessary for the game to run for me. Pasting your command after the D9VK bit simply opens the FNV launcher like normal, pasting it before results in nothing launching to begin with.

**Comment by PopeRigby** [comment]
@wizradicool I think I'm having the same issue. Have you found a fix?

**Comment by ajventer** [comment]
I'm having this issue as well after reinstalling fallout4. It only affects FO4 however, my pre-existing installs for Skyrim Special Edition and Oblivion both work just fine.

I suspect the issue is something that changed in how steam sets up the prefixes, when a game is newly installed now, it gets a new prefix and this new prefix is breaking MO2. 
Unfortunately it produces no errors I can see, you may need to use strace or something to figure out where it's going wrong.

**Comment by PopeRigby** [comment]
@ajventer When you say strace, do you mean stack trace?

**Comment by ajventer** [comment]
@PopeRigby yes, strace is a stack tracing program on Linux. But I was suggesting it to @rockerbacon as a possible way to debug this weird issue.

**Comment by ajventer** [comment]
A bit more information:
- I ruled out the possiblity of the prefixes being the issue, if you use the same prefix created by Steam but with TKG's protonified system wine, then MO2 runs just fine.
If you use proton - it doesn't.
@rockerbacon  protonlauncher is NOT the source of the bug, if I bypass it and call proton directly the same problem happens.
It ONLY happens with installs of MO2 done after a particular date (I don't know when exactly) but my older ones work fine. It's quite possible there is some trick/override/work-around we can do in protonlauncher to fix it but I haven't found it yet, the fact that it just dies with no output whatsoever makes it very hard to debug.

As a work-around: I copied the prefix from steamplay (which contains all the requirements) to a different location, installed windows steam INTO the prefix, then moved my fallout4 directory into that windows steam, ran MO2 through that profile and that is able to run FO4 just fine bypassing proton entirely by using winesteam. 
This is not as convenient of course, but it does work in the meantime.

**Comment by jamtowers** [comment]
I've found a solution to this, at least in my case, as it turns out steam has a `tracked_files` file in the compatdata folder of each game, it seems this wasn't always the case, basically it doesn't load any files not on that list so when Lutris installs 'Visual C++ 2015-2019 Redistributable (x64)' onto that prefix the files added from that don't get added to the tracked files because it isn't run by steam, so when we try to launch the game through steam it doesn't load the C++ redis, which is a requirement of mod organizer (I suppose that's why it never throws bad a proper error, because it doesn't even get off the ground)

## The Solution

I found two ways to fix this:

#### The easy way
- delete/rename/move the `tracked_files` folder from the game's compatdata folder
  - you can find that file here: `~/.steam/steam/steamapps/compatdata/{steamid}`, 
  - {steamid} being the steam id for the game you want to launch mod organizer on, so in my case it's 377160 for fallout 4
- Apparently steam doesn't mind if this file doesn't exist and it'll just launch normally anyway, so it should just load everything in the prefix fixing the issue

#### The harder (probably safer) way
- Add all the extra files you need to the `tracked_files` file, I made a copy of the prefix before I ran the Lutris mod organizer install and then ran a diff tool to see what changed, then I added that to the tracked files, you however can probably just add the list I compiled to the end of your `tracked_files` file:
```
drive_c/windows/system32/api-ms-win-core-file-ansi-l2-1-0.dll
drive_c/windows/system32/api-ms-win-core-file-fromapp-l1-1-0.dll
drive_c/windows/system32/api-ms-win-core-libraryloader-l2-1-0.dll
drive_c/windows/system32/api-ms-win-core-localization-l1-2-2.dll
drive_c/windows/system32/api-ms-win-core-libraryloader-l2-1-0.dll
drive_c/windows/system32/api-ms-win-core-localization-l1-2-2.dll
drive_c/windows/system32/api-ms-win-core-memory-l1-1-3.dll
drive_c/windows/system32/api-ms-win-core-memory-l1-1-4.dll
drive_c/windows/system32/api-ms-win-core-namedpipe-ansi-l1-1-0.dll
drive_c/windows/system32/api-ms-win-core-registry-l2-2-0.dll
drive_c/windows/system32/api-ms-win-core-systemtopology-l1-1-0.dll
drive_c/windows/system32/api-ms-win-downlevel-kernel32-l2-1-0.dll
drive_c/windows/system32/d3d8thk.dll
drive_c/windows/system32/d3dim700.dll
drive_c/windows/system32/dcomp.dll
drive_c/windows/system32/directmanipulation.dll
drive_c/windows/system32/dplaysvr.exe
drive_c/windows/system32/dpvsetup.exe
drive_c/windows/system32/netio.sys
drive_c/windows/system32/wineusb.sys
drive_c/windows/system32/dsuiext.dll
drive_c/windows/system32/mfc140chs.dll
drive_c/windows/system32/mfc140cht.dll
drive_c/windows/system32/mfc140deu.dll
drive_c/windows/system32/mfc140.dll
drive_c/windows/system32/mfc140enu.dll
drive_c/windows/system32/mfc140esn.dll
drive_c/windows/system32/mfc140fra.dll
drive_c/windows/system32/mfc140ita.dll
drive_c/windows/system32/mfc140jpn.dll
drive_c/windows/system32/mfc140kor.dll
drive_c/windows/system32/mfc140rus.dll
drive_c/windows/system32/mfc140u.dll
drive_c/windows/system32/mfcm140.dll
drive_c/windows/system32/mfcm140u.dll
drive_c/windows/system32/msvcp140_1.dll
drive_c/windows/system32/msvcp140_2.dll
drive_c/windows/system32/msvcp140_atomic_wait.dll
drive_c/windows/system32/msvcp140_codecvt_ids.dll
drive_c/windows/system32/netutils.dll
drive_c/windows/system32/opencl.dll
drive_c/windows/system32/pwrshplugin.dll
drive_c/windows/system32/qasf.dll
drive_c/windows/system32/qdvd.dll
drive_c/windows/system32/srvcli.dll
drive_c/windows/system32/vcamp140.dll
drive_c/windows/system32/vccorlib140.dll
drive_c/windows/system32/vcruntime140_1.dll
drive_c/windows/system32/vga.dll
drive_c/windows/system32/wevtsvc.dll
drive_c/windows/syswow64/activeds.tlb
drive_c/windows/syswow64/api-ms-win-core-file-ansi-l2-1-0.dll
drive_c/windows/syswow64/api-ms-win-core-file-fromapp-l1-1-0.dll
drive_c/windows/syswow64/api-ms-win-core-libraryloader-l2-1-0.dll
drive_c/windows/syswow64/api-ms-win-core-localization-l1-2-2.dll
drive_c/windows/syswow64/api-ms-win-core-memory-l1-1-3.dll
drive_c/windows/syswow64/api-ms-win-core-memory-l1-1-4.dll
drive_c/windows/syswow64/api-ms-win-core-namedpipe-ansi-l1-1-0.dll
drive_c/windows/syswow64/api-ms-win-core-registry-l2-2-0.dll
drive_c/windows/syswow64/api-ms-win-core-systemtopology-l1-1-0.dll
drive_c/windows/syswow64/api-ms-win-downlevel-kernel32-l2-1-0.dll
drive_c/windows/syswow64/d3d8thk.dll
drive_c/windows/syswow64/d3dim700.dll
drive_c/windows/syswow64/dcomp.dll
drive_c/windows/syswow64/directmanipulation.dll
drive_c/windows/syswow64/dplaysvr.exe
drive_c/windows/syswow64/dpvsetup.exe
drive_c/windows/syswow64/dsuiext.dll
drive_c/windows/syswow64/mfc140chs.dll
drive_c/windows/syswow64/mfc140cht.dll
drive_c/windows/syswow64/mfc140deu.dll
drive_c/windows/syswow64/mfc140.dll
drive_c/windows/syswow64/mfc140enu.dll
drive_c/windows/syswow64/mfc140esn.dll
drive_c/windows/syswow64/mfc140fra.dll
drive_c/windows/syswow64/mfc140ita.dll
drive_c/windows/syswow64/mfc140jpn.dll
drive_c/windows/syswow64/mfc140kor.dll
drive_c/windows/syswow64/mfc140rus.dll
drive_c/windows/syswow64/mfc140u.dll
drive_c/windows/syswow64/mfcm140.dll
drive_c/windows/syswow64/mfcm140u.dll
drive_c/windows/syswow64/msvcp140_1.dll
drive_c/windows/syswow64/msvcp140_2.dll
drive_c/windows/syswow64/msvcp140_atomic_wait.dll
drive_c/windows/syswow64/msvcp140_codecvt_ids.dll
drive_c/windows/syswow64/netutils.dll
drive_c/windows/syswow64/opencl.dll
drive_c/windows/syswow64/pwrshplugin.dll
drive_c/windows/syswow64/qasf.dll
drive_c/windows/syswow64/qdvd.dll
drive_c/windows/syswow64/srvcli.dll
drive_c/windows/syswow64/vcamp140.dll
drive_c/windows/syswow64/vccorlib140.dll
drive_c/windows/syswow64/vcruntime140_1.dll
drive_c/windows/syswow64/vga.dll
drive_c/windows/syswow64/wbem/wbemdisp.dll
drive_c/windows/syswow64/wbem/wbemprox.dll
drive_c/windows/syswow64/wbem/wmic.exe
drive_c/windows/syswow64/wbem/wmiutils.dll
drive_c/windows/syswow64/wevtsvc.dll
```
- That list probably has stuff I didn't need to add (I excluded some obviously unnecessary files) but It shouldn't matter, hopefully once you've saved that file mod organizer will actually load

Hopefully this helps some folks!

**Comment by hmceph** [comment]
I have also run into this problem, but for Skyrim SE. No errors in terminal. I tried launching it from steam (for skyrimse) and it didn't do anything. Also tried the last suggested fix with no luck.

**Comment by LoneWolfHT** [comment]
> I have also run into this problem, but for Skyrim SE. No errors in terminal. I tried launching it from steam (for skyrimse) and it didn't do anything. Also tried the last suggested fix with no luck.
> 
> Edit: Nevermind I was using the wrong version of Proton on Steam. If anyone else has this problem. You want to delete your game's prefix for Proton GE, switch your proton version to 5.0 in steam, launch it, then delete MO2 from lutris and reinstall. Then it'll work. I did have to try to launch it a few times, but now it works. Sidenote, MO2 did launch with Proton 6.5 GE when I tried the run.sh suggested in Changing Proton Version discussion issue, but mods didn't load properly in game.

Had the same issue you did. Fixed now. Thanks!

**Comment by vondriago** [comment]
MO2 will not launch when Steam "play" button pressed. Tested this in Fallout 4 and Fallout 3 GOTY. Only way can launch MO2 is directly via protontrick launcher. Unfortunately, @jamtowers solution does not work.

Seems to launch Fallout 4 and run fine when using ptrotontricks launcher (I know not recommended). Reads all mods correctly. Only issue seems to be sound latency.

All requirements for Protontricks, Winetricks and Wine have been met, Protontricks installed with pipx. Manually update protontricks and winetricks, weekly. Running Fedora 34.

**Comment by rockerbacon** [comment]
Closing, since the executing method changed in version 3.x. Whatever may cause the same behavior in newer versions is unrelated to this issue.
