### ISSUE TITLE
MO2 fails to launch

### ISSUE THREAD

**Issue by poperigby** [rockerbacon/modorganizer2-linux-installer#157]
Not getting any error, but this is the log:
[mo2log.txt](https://github.com/rockerbacon/lutris-skyrimse-installers/files/5360490/mo2log.txt)

**Comment by samsamabou** [comment]
Hallo,

To solve this my trick was to change the runner from Linux to Wine to delete config file and then change back from Wine to Linux without forgetting to set again the executable to /home/username/Games/mod-organizer-2/run.sh.

**Comment by deane-c64** [comment]
> Hallo,
> 
> To solve this my trick was to change the runner from Linux to Wine to delete config file and then change back from Wine to Linux without forgetting to set again the executable to /home/username/Games/mod-organizer-2/run.sh.

where is the Config file?

**Comment by samsamabou** [comment]
> > Hallo,
> > To solve this my trick was to change the runner from Linux to Wine to delete config file and then change back from Wine to Linux without forgetting to set again the executable to /home/username/Games/mod-organizer-2/run.sh.
> 
> where is the Config file?

I do not know the location of the config file, just that it deletes itself when you change the runner and create a new one instead.
