### ISSUE TITLE
command wine vc_redist.x86.exe /q returned status 231. Aborting.

### ISSUE THREAD

**Issue by KorgiSilvercloud** [rockerbacon/modorganizer2-linux-installer#158]
I am getting a new error when I attempt to reinstall MO2 on a new system. I was able to get past the "shasum" error by updating winetricks, but now a new error pups up: "warning: Note: command wine vc_redist.x86.exe /q returned status 231. Aborting". Google has been absolutely no help in determining what this error means and I am at a loss. I am currently running Arch Linux with the latest wine-staging installed.

**Comment by rockerbacon** [comment]
This seems like an issue with Wine itself not being able to execute vc_redist.x86.exe.

The latest release contains a fix regarding Proton versioning, see if that fixes the problem. If it doesn't, you should check [bug tracking in the Wine project](https://bugs.winehq.org/)

**Comment by HeliosDK** [comment]
Seems like the error orcurrs when the installer tries to install a 32bit on 64bit wine since SkyrimSE is a 64bit .

**Comment by LordSocky** [comment]
Just putting an update here for those who are still having this issue, it seems recent Wine versions have an issue with installing vcrun2019, and Winetricks uses your system Wine by default. Easiest way around this is just downloading an older version of Wine through Lutris' runner manager, closing Lutris and running it from the terminal like so: `WINE=/home/USERNAME/.local/share/lutris/runners/wine/lutris-XXX-x86_64/bin/wine lutris`, substituting your username and Lutris Wine version. After installing, you can run it normally. Any Wine version older than 5.18 *should* work, but I only personally tested with lutris-5.0.

**Comment by Dathide** [comment]
After hours of searching, I found the solution. Lutris uses an outdated version of winetricks, causing file mismatches like these. Enter these commands in a terminal one after the other to fix:
```
cd "${HOME}/.local/share/lutris/runtime/winetricks"
sudo mv winetricks old_winetricks
sudo wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
sudo chmod +x winetricks
```
The first command moves you to the folder where the lutris old winetricks version is stored. The second renames the current winetricks just in case. The third downloads the latest winetricks. The fourth makes the downloaded file an executable.

**Comment by fighuass** [comment]
Thanks @LordSocky, can confirm that this fixes the issue! (Used lutris-5.0 as well, and Proton 5.0-10 for Skyrim SE in Steam).

Oddly enough the game does seem to mess up my GNOME dock now when I quit, but that's okay I guess.

**Comment by fighuass** [comment]
Wait, on a second thought... the voice acting is gone. Everything else works, though.

**Comment by rockerbacon** [comment]
Closing since the latest version no longer applies vcrun2019 to the prefix
