### ISSUE TITLE
Script to launch script extender through MO2 directly?

### ISSUE THREAD

**Issue by katawful** [rockerbacon/modorganizer2-linux-installer#166]
I'm trying to find a way to launch NVSE directly so I don't have to open up MO2 everytime just to play. I tried launching the desktop shortcut it creates but it doesn't seem to want to launch when messing with the provided run.sh script

**Comment by rockerbacon** [comment]
The desktop shortcut MO2 creates is simply an alias for `ModOrganizer.exe` with a few arguments. With these arguments in hand, you can simply append them to the command executed in `run.sh`.

**Comment by katawful** [comment]
I tried extracting the argument from the .lnk file but I can't seem to get it to work. How should it be set up to run a shortcut?

**Comment by katawful** [comment]
I figured it out, but for whatever reason its not loading anything into VFS. It only works if I launch through MO2 itself
