### ISSUE TITLE
Can't update after Lutris 0.5.8

### ISSUE THREAD

**Issue by hazelnot** [rockerbacon/modorganizer2-linux-installer#175]
Lutris got some major UI changes in 0.5.8 and it seems to have lost the ability to remove games without deleting their data as well. I'm not entirely sure how to update MO2 now.

**Comment by clad** [comment]
I downgraded to 0.5.7 after a few hours of trying to get 0.5.8 to work properly. It breaks a few things, and with MO2 you cannot get past initial install screen - https://github.com/lutris/lutris/issues/3290

**Comment by BrightCrow** [comment]
> I downgraded to 0.5.7 after a few hours of trying to get 0.5.8 to work properly. It breaks a few things, and with MO2 you cannot get past initial install screen - [lutris/lutris#3290](https://github.com/lutris/lutris/issues/3290)

Hi, could you tell me how do you downgrade to 0.5.7 please?

**Comment by clad** [comment]
> Hi, could you tell me how do you downgrade to 0.5.7 please?

It will depend on your distro (if you installed via your distro's package manager).

**Comment by BrightCrow** [comment]
> > Hi, could you tell me how do you downgrade to 0.5.7 please?
> 
> It will depend on your distro (if you installed via your distro's package manager).

Hi clad, thank you for your answer. :)

I'm on Manjaro, Lutris was pre-installed, and then updated with the package manager indeed.

**Comment by SmiVan** [comment]
Manjaro package downgrade instructions can be found here: https://wiki.manjaro.org/index.php?title=Downgrading_packages

**Comment by rockerbacon** [comment]
Closing as the latest version no longer uses Lutris
