### ISSUE TITLE
ENBoost not working for Skyrim LE

### ISSUE THREAD

**Issue by hazelnot** [rockerbacon/modorganizer2-linux-installer#177]
I've tried both enb versions (wrapper and injector) and, uh, it crashes my computer completely. The wrapper opens a small black window in the corner of the screen, then my mouse cursor starts lagging, followed by everything else, followed by a complete freeze. 

The injector works a bit better, it actually goes into the main menu, but when trying to load a save I just get a black screen with the background sound on a loop. Both versions ended up with me having to use the physical reset button.

Any help?

Specs:
Arch Linux
AMD Ryzen 7 1700X
16GB RAM
AMD Radeon 5700 XT Anniversary Edition (8GB RAM)

**Comment by rockerbacon** [comment]
You shouldn't use ENBoost. DXVK and Wine have their own memory patches which work better.

The Wine patch is enabled by default in Proton. If for some reason you need to enable it manually, all you need to do is set the environment variable `WINE_LARGE_ADDRESS_AWARE` to 1.

The DXVK patch is enabled with the configuration `d3d9.evictManagedOnUnlock`. Just download [this gist](https://gist.github.com/rockerbacon/884847dca974e947749df20c52e255fc) and save it as `dxvk.conf` in the same folder where `TESV.exe` resides. See [this issue on the DXVK project](https://github.com/doitsujin/dxvk/issues/1552) for a little more information.

Your black screen problem may not be related ENBoost specifically. If all you want is ENBoost then you'll be set with the aforementioned configurations and can ditch ENB entirely. If you also want ENB visual effects you may want to try a few things:

- Try a different ENB preset: ENB creators can write their own effects and it's difficult to ensure every single custom code out there will work. I have [Rudy ENB](https://www.nexusmods.com/skyrim/mods/41482) working, you might want to start with that.
- Try a different ENB version: updates might break compatibility with DXVK. I've used v0.434 and v0.444 successfully in my own game, you may want to start with those.

Also, remember to make sure ENB is your issue. Try to launch the game without ENB and see if everything works.

**Comment by hazelnot** [comment]
Yeah, everything works without ENB, I just keep getting crashes that people online are saying are caused by the mods making the game run out of RAM, and they all recommended ENBoost. I'll try DXVK's patch and see if that helps.

**Comment by Maxattax97** [comment]
Dear lord, I've spent several days trying to to get this to work on my system and all your patches in #271 fixed FNIS and a variety of crashes I was getting when creating a new game (both on the loading screen and also seemingly right around when the dragon lands). **Thank you SO MUCH!**

Recording this here so hopefully search engines find it.
```
ERROR(2012): Could not generate: defaultfemale.hkx defaultmale.hkx weapequip.hkx staggerbehavior.hkx sprintbehavior.hkx shout_behavior.hkx magicmountedbehavior.hkx magicbehavior.hkx magic_readied_direction_behavior.hkx 1hm_locomotion.hkx 1hm_behavior.hkx 0_master.hkx
```
