### ISSUE TITLE
MO2 closes on start

### ISSUE THREAD

**Issue by SmiVan** [rockerbacon/modorganizer2-linux-installer#180]
After installing MO2 from the "stable" installer by applying fixes for:
* #179 by modifying the installer as described there
* #61 by running `$HOME/.local/share/lutris/runtime/winetricks/winetricks --self-update`
* #158 by running `WINE=$HOME/.local/share/lutris/runners/wine/lutris-5.7-9-x86_64/bin/wine lutris -i ~/Downloads/modorganizer2.yml`

~~I've now encountered #119 when launching.
Opening a new issue as recommended.~~

---
### Behaviour:
Upon clicking "Play" on MO2 in lutris, nothing opens and the "Play" button returns after about 5-10 seconds.

---
### Software:

* Ubuntu 20.04.1 LTS
 *   Lutris 0.5.8
  *  Python 3.8.5
   * MO2 install script 2.8.6
---
### Log:

<details>
<summary> Click to open </summary>

```
Running gamemoderun /home/smivan/Games/mod-organizer-2/run.sh
Initial process has started with pid 53753
Start monitoring process.
gamemodeauto: 
Searching for Steam in '/home/smivan/.steam'
Found Steam
Searching for Steam in '/home/smivan/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Searching for game in library '/home/smivan/.steam/steam'
Found game
Searching for 'Proton 5.0' in library '/home/smivan/.steam/steam'
gamemodeauto: 
gamemodeauto: 
Found Proton
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 


	PATH='/home/smivan/.steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/smivan/.steam/ubuntu12_32/steam-runtime/usr/bin:/home/smivan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' \
	LD_LIBRARY_PATH='/home/smivan/.steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/smivan/.steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32:/libx32:/usr/libx32:/lib:/usr/lib:/usr/lib/i386-linux-gnu/sse2:/usr/lib/x86_64-linux-gnu/tls:/home/smivan/.steam/ubuntu12_32/steam-runtime/lib/i368-linux-gnu:/home/smivan/.steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/smivan/.steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/smivan/.steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/smivan/.steam/ubuntu12_32/steam-runtime/lib:/home/smivan/.steam/ubuntu12_32/steam-runtime/usr/lib' \
	STEAM_COMPAT_DATA_PATH='/home/smivan/.steam/steam/steamapps/compatdata/489830' \
	SteamGameId=489830 \
	SteamAppId=489830 \
	WINEDLLOVERRIDES='xaudio2_7=n,b;' PULSE_LATENCY_MSEC=90 \
	\
	'/home/smivan/.steam/steam/steamapps/common/Proton 5.0/proton' run '/home/smivan/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 


gamemodeauto: 
gamemodeauto: 
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
esync: up and running.
Setting breakpad minidump AppID = 489830
Steam_SetMinidumpSteamID:  Caching Steam ID:  [REDACTED] [API loaded no]
Monitored process exited.
Initial process has exited (return code: 0)
All monitored processes have exited.
Exit with returncode 0
```

</details>

---

~~It should also be noted the only instance of `libgamemodeauto.so.0` is located at `/usr/lib/x86_64-linux-gnu/libgamemodeauto.so.0`.~~

**Comment by SmiVan** [comment]
Alright so the easy solution is to just use the installer from the [lutris website](https://lutris.net/games/mod-organizer-2/). Not sure if the winetricks and vc_redist fixes still need to be done, but once I reinstalled from the website over the previous attempts at installation everything started working perfectly fine.

I think the recommendation of
> While these installers may be available on Lutris.net, users are always recommended to use the latest stable release from this repository.

should perhaps be withdrawn from the README, due to the strange behaviour of the "stable" installer.

**Comment by XMais** [comment]
Try to downgrade to lutris 0.5.7.
There are already issues posted here stating 0.5.8 causes major issues.
My MO2 completely broke down after the update to 0.5.8.

Download the old 0.5.7 for U19.10 here: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris

**Comment by Arcstur** [comment]
Same problem here (Linux Mint 20), switched to Lutirs 0.5.7.1 and it is working now. But I had to manually delete all lutris folders in .cache, .local, etc..

**Comment by CSAndrew** [comment]
I'm pretty sure I'm encountering the same thing on 0.5.7.1.

**Comment by Baa14453** [comment]
Inside your Proton installation `/home/smivan/.steam/steam/steamapps/common/Proton 5.0/` there is a file called `user_settings.sample.py`

Please copy this and rename it to `user_settings.py`

Try running again and post the new log, this should enable debug logging for Proton which might help.
