### ISSUE TITLE
Linux filesystem case-sensitive problems

### ISSUE THREAD

**Issue by XMais** [rockerbacon/modorganizer2-linux-installer#188]
(I'm not a native english speaker, I hope you can understand what I'm talking about)

Default Linux operation for new filesystems (i.e. ext4) is to treat filenames as is, as opaque byte sequences without any special meaning.
This means that for example "meshes" and "Meshes" are treated as two different folders, both can be created in the same directory. Under Windows, this is not possible. Creating a "meshes" folder when there is already a "Meshes" folder will  result in a "overwrite/insert into" confirmation dialogue.
I've found out the hard way, that this can lead to some serious problems when mixing up a Linux filesystem and a wine environment using that filesystem.

During my time modding Skyrim on Linux using this guide as a base, I ran into one big problem with this.
Mod creators, in general, don't follow a common naming-schema when creating directories for their mods. I've found everything so far, "meshes" (~90%), "Meshes"(~10%) and even "MESHES"(1 mod) as well as updates for mods, where files (textures, scripts) were changed in casing (for example follower_script_1.pex and Follower_Script_1.pex) Again, under Windows, that would all be the same and completely unproblematic. Under Linux, all of these would be treated as different files. 

Consequently, using MO2 on an ext4 filesystem resulted in some folders and files not being loaded at all: Some Meshes, Textures, Scripts and updates such as compatibility patches ended up missing in the MO2 VFS.

Users on the MO2 github have also reported this and provided a recommendation when using MO2 under Linux:

Simple, create a new filessystem for your MO2 mods with the Linux kernel-feature for case-insensitive files enabled.

1. Check if your kernel supports the feature: $ cat /sys/fs/ext4/features/casefold
2. Only, if supported, create a new partition with this feature:  $ mkfs -t ext4 -O casefold /dev/sda2
3. Move your MO2 mods folder to this new partition and change the path in MO2

And voila, your meshes, textures, scripts aren't missing anymore.

**Comment by rockerbacon** [comment]
Wine implements its own solution for this problem and no user intervention should be necessary, see [their wiki on the subject](https://wiki.winehq.org/Case_Insensitive_Filenames) for a little more information. I have not encountered a single problem regarding case sensitivity while using this project nor while using anything else under Wine.

If you had any problems you should report a bug to the [Wine project](https://bugs.winehq.org/). Notice that the Wine version provided by Proton 5.0 was tested countless times and works fine.

**Comment by XMais** [comment]
If I read the wiki, it becomes clear that the current solution is very far away from being optimal and may still cause some problems (at least performance wise).
On the wiki, the winehq team also mentions "fully implement case-insensitive in the kernel" as well as "Using a case-insensitive FUSE filesystem for just the Wine folder" as better solutions.

At least for me, the default wine implementation to fix this problem failed. I tested and verified trhis many many times before writing this issue. 
And eversince I created a separate partition for the mods folder, my performance in MO2 as well as Skyrim (laoding save) has gone up tremendously. It's just as the winehq team writes for their default implementation: "performance is suboptimal".

Consequently, I would still recommend anyone who wants to install many mods to use a separate case-insensitive filesystem.

**Comment by monomachos** [comment]
Wine should solve this problem at the cost of performance. But as of kernel 5.2 linux supports case insensitive directories for file systems. This is useful for wine and for android developers.

Here's a relevant LWN article about this feature and skyrim:

https://lwn.net/Articles/829919/
