### ISSUE TITLE
(Fallout 4) Cannot install because Winetricks won't install

### ISSUE THREAD

**Issue by 0IzzyJ0** [rockerbacon/modorganizer2-linux-installer#195]
Running /usr/bin/bash -c # clear envs set by Lutris
export LD_LIBRARY_PATH=""

nexus_game_id=fallout4
runner=proton

if [ ! -f "/home/izzyj/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/izzyj/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/izzyj/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        if [ -z "$steam_library" ]; then
            steam_library=$("/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)
        fi

        if [ ! -d "$steam_library" ]; then
            "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/izzyj/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/izzyj/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options $game_appid '/home/izzyj/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/izzyj/Games/mod-organizer-2/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/izzyj/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/izzyj/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options '/home/izzyj/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/izzyj/Games/mod-organizer-2/download.sh"
        ;;
esac

if [ -d "/home/izzyj/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/izzyj/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/izzyj/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/izzyj/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/izzyj/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/izzyj/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Initial process has started with pid 38656
Start monitoring process.
Searching for Steam in '/home/izzyj/.local/share/Steam'
Found Steam
Searching for game in library '/home/izzyj/.local/share/Steam'
Searching for game in library '/home/izzyj/Drives/Secondary/SteamGames'
Found game
Installing script extender...
------------------------------------------------------
You are running winetricks-20200412-next, latest upstream is winetricks-20201206!
------------------------------------------------------
------------------------------------------------------
You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing mkdir -p /home/izzyj/Drives/Secondary/SteamGames/steamapps/compatdata/377160
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 9f5266697d8aa45394d6baae27605470890fdf130fb45ae47cf4270287b3f64c with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call vcrun2019
Executing mkdir -p /home/izzyj/Drives/Secondary/SteamGames/steamapps/compatdata/377160
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2019 
------------------------------------------------------
Checksum for /home/izzyj/.cache/winetricks/vcrun2019/vc_redist.x86.exe did not match, retrying download
------------------------------------------------------
Executing cd /home/izzyj/.cache/winetricks/vcrun2019
Downloading https://aka.ms/vs/16/release/vc_redist.x86.exe to /home/izzyj/.cache/winetricks/vcrun2019
--2020-12-16 06:18:31--  https://aka.ms/vs/16/release/vc_redist.x86.exe
Resolving aka.ms (aka.ms)... 23.10.88.237
Connecting to aka.ms (aka.ms)|23.10.88.237|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/8ecb9800-52fd-432d-83ee-d6e037e96cc2/50A3E92ADE4C2D8F310A2812D46322459104039B9DEADBD7FDD483B5C697C0C8/VC_redist.x86.exe [following]
--2020-12-16 06:18:31--  https://download.visualstudio.microsoft.com/download/pr/8ecb9800-52fd-432d-83ee-d6e037e96cc2/50A3E92ADE4C2D8F310A2812D46322459104039B9DEADBD7FDD483B5C697C0C8/VC_redist.x86.exe
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 2606:2800:11f:7de:d31:7db:168f:1225, 93.184.215.201
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|2606:2800:11f:7de:d31:7db:168f:1225|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14337656 (14M) [application/octet-stream]
Saving to: ‘vc_redist.x86.exe’

     0K .......... .......... .......... .......... ..........  0% 1.03M 13s
    50K .......... .......... .......... .......... ..........  0% 3.00M 9s
   100K .......... .......... .......... .......... ..........  1% 2.86M 7s
   150K .......... .......... .......... .......... ..........  1% 2.83M 7s
   200K .......... .......... .......... .......... ..........  1% 2.08M 7s
   250K .......... .......... .......... .......... ..........  2% 3.23M 6s
   300K .......... .......... .......... .......... ..........  2% 2.97M 6s
   350K .......... .......... .......... .......... ..........  2% 1.17M 7s
   400K .......... .......... .......... .......... ..........  3% 2.34M 6s
   450K .......... .......... .......... .......... ..........  3% 2.47M 6s
   500K .......... .......... .......... .......... ..........  3%  619K 8s
   550K .......... .......... .......... .......... ..........  4% 9.31M 7s
   600K .......... .......... .......... .......... ..........  4%  625M 7s
   650K .......... .......... .......... .......... ..........  4%  570M 6s
   700K .......... .......... .......... .......... ..........  5% 3.61M 6s
   750K .......... .......... .......... .......... ..........  5% 1.95M 6s
   800K .......... .......... .......... .......... ..........  6% 2.20M 6s
   850K .......... .......... .......... .......... ..........  6% 2.17M 6s
   900K .......... .......... .......... .......... ..........  6% 3.44M 6s
   950K .......... .......... .......... .......... ..........  7%  517K 7s
  1000K .......... .......... .......... .......... ..........  7% 6.38M 6s
  1050K .......... .......... .......... .......... ..........  7%  569M 6s
  1100K .......... .......... .......... .......... ..........  8%  534M 6s
  1150K .......... .......... .......... .......... ..........  8%  531M 6s
  1200K .......... .......... .......... .......... ..........  8%  606M 5s
  1250K .......... .......... .......... .......... ..........  9% 2.61M 5s
  1300K .......... .......... .......... .......... ..........  9% 2.60M 5s
  1350K .......... .......... .......... .......... ..........  9% 2.55M 5s
  1400K .......... .......... .......... .......... .......... 10% 2.64M 5s
  1450K .......... .......... .......... .......... .......... 10% 1.83M 5s
  1500K .......... .......... .......... .......... .......... 11% 4.36M 5s
  1550K .......... .......... .......... .......... .......... 11% 1.56M 5s
  1600K .......... .......... .......... .......... .......... 11% 2.62M 5s
  1650K .......... .......... .......... .......... .......... 12%  611K 6s
  1700K .......... .......... .......... .......... .......... 12% 23.5M 5s
  1750K .......... .......... .......... .......... .......... 12%  635M 5s
  1800K .......... .......... .......... .......... .......... 13%  656M 5s
  1850K .......... .......... .......... .......... .......... 13%  669M 5s
  1900K .......... .......... .......... .......... .......... 13% 61.1M 5s
  1950K .......... .......... .......... .......... .......... 14% 1.00M 5s
  2000K .......... .......... .......... .......... .......... 14% 3.25M 5s
  2050K .......... .......... .......... .......... .......... 14% 2.95M 5s
  2100K .......... .......... .......... .......... .......... 15% 3.01M 5s
  2150K .......... .......... .......... .......... .......... 15% 2.91M 5s
  2200K .......... .......... .......... .......... .......... 16% 4.33M 5s
  2250K .......... .......... .......... .......... .......... 16% 1.21M 5s
  2300K .......... .......... .......... .......... .......... 16% 1.76M 5s
  2350K .......... .......... .......... .......... .......... 17% 3.03M 5s
  2400K .......... .......... .......... .......... .......... 17% 3.39M 5s
  2450K .......... .......... .......... .......... .......... 17% 2.47M 5s
  2500K .......... .......... .......... .......... .......... 18% 4.55M 5s
  2550K .......... .......... .......... .......... .......... 18% 3.13M 5s
  2600K .......... .......... .......... .......... .......... 18% 1.96M 5s
  2650K .......... .......... .......... .......... .......... 19% 2.96M 5s
  2700K .......... .......... .......... .......... .......... 19% 4.00M 4s
  2750K .......... .......... .......... .......... .......... 19% 2.07M 4s
  2800K .......... .......... .......... .......... .......... 20% 4.83M 4s
  2850K .......... .......... .......... .......... .......... 20% 2.95M 4s
  2900K .......... .......... .......... .......... .......... 21% 2.10M 4s
  2950K .......... .......... .......... .......... .......... 21% 2.88M 4s
  3000K .......... .......... .......... .......... .......... 21% 2.32M 4s
  3050K .......... .......... .......... .......... .......... 22% 4.36M 4s
  3100K .......... .......... .......... .......... .......... 22% 1.44M 4s
  3150K .......... .......... .......... .......... .......... 22% 1.51M 4s
  3200K .......... .......... .......... .......... .......... 23% 4.13M 4s
  3250K .......... .......... .......... .......... .......... 23% 2.17M 4s
  3300K .......... .......... .......... .......... .......... 23% 5.13M 4s
  3350K .......... .......... .......... .......... .......... 24%  648K 4s
  3400K .......... .......... .......... .......... .......... 24%  543M 4s
  3450K .......... .......... .......... .......... .......... 24%  697M 4s
  3500K .......... .......... .......... .......... .......... 25%  647M 4s
  3550K .......... .......... .......... .......... .......... 25% 2.33M 4s
  3600K .......... .......... .......... .......... .......... 26% 3.50M 4s
  3650K .......... .......... .......... .......... .......... 26% 3.51M 4s
  3700K .......... .......... .......... .......... .......... 26% 3.14M 4s
  3750K .......... .......... .......... .......... .......... 27% 2.75M 4s
  3800K .......... .......... .......... .......... .......... 27% 2.84M 4s
  3850K .......... .......... .......... .......... .......... 27% 1.95M 4s
  3900K .......... .......... .......... .......... .......... 28% 2.72M 4s
  3950K .......... .......... .......... .......... .......... 28% 2.24M 4s
  4000K .......... .......... .......... .......... .......... 28% 1.96M 4s
  4050K .......... .......... .......... .......... .......... 29% 3.29M 4s
  4100K .......... .......... .......... .......... .......... 29% 3.25M 4s
  4150K .......... .......... .......... .......... .......... 29% 1.75M 4s
  4200K .......... .......... .......... .......... .......... 30% 2.98M 4s
  4250K .......... .......... .......... .......... .......... 30% 1.92M 4s
  4300K .......... .......... .......... .......... .......... 31% 2.31M 4s
  4350K .......... .......... .......... .......... .......... 31% 2.78M 4s
  4400K .......... .......... .......... .......... .......... 31% 2.78M 4s
  4450K .......... .......... .......... .......... .......... 32% 3.78M 4s
  4500K .......... .......... .......... .......... .......... 32% 1.79M 4s
  4550K .......... .......... .......... .......... .......... 32% 1.57M 4s
  4600K .......... .......... .......... .......... .......... 33% 3.49M 4s
  4650K .......... .......... .......... .......... .......... 33% 1.56M 4s
  4700K .......... .......... .......... .......... .......... 33% 2.46M 4s
  4750K .......... .......... .......... .......... .......... 34% 1.35M 4s
  4800K .......... .......... .......... .......... .......... 34% 3.91M 4s
  4850K .......... .......... .......... .......... .......... 34% 1.59M 4s
  4900K .......... .......... .......... .......... .......... 35% 2.44M 4s
  4950K .......... .......... .......... .......... .......... 35% 2.43M 4s
  5000K .......... .......... .......... .......... .......... 36%  829K 4s
  5050K .......... .......... .......... .......... .......... 36% 2.15M 4s
  5100K .......... .......... .......... .......... .......... 36% 2.17M 4s
  5150K .......... .......... .......... .......... .......... 37% 1.89M 4s
  5200K .......... .......... .......... .......... .......... 37% 2.79M 4s
  5250K .......... .......... .......... .......... .......... 37% 3.19M 4s
  5300K .......... .......... .......... .......... .......... 38% 3.02M 4s
  5350K .......... .......... .......... .......... .......... 38% 6.32M 3s
  5400K .......... .......... .......... .......... .......... 38% 1.75M 3s
  5450K .......... .......... .......... .......... .......... 39% 1.29M 3s
  5500K .......... .......... .......... .......... .......... 39% 5.52M 3s
  5550K .......... .......... .......... .......... .......... 39% 2.68M 3s
  5600K .......... .......... .......... .......... .......... 40% 3.09M 3s
  5650K .......... .......... .......... .......... .......... 40% 1.76M 3s
  5700K .......... .......... .......... .......... .......... 41% 3.17M 3s
  5750K .......... .......... .......... .......... .......... 41% 2.17M 3s
  5800K .......... .......... .......... .......... .......... 41% 2.69M 3s
  5850K .......... .......... .......... .......... .......... 42% 2.13M 3s
  5900K .......... .......... .......... .......... .......... 42% 3.15M 3s
  5950K .......... .......... .......... .......... .......... 42% 1.40M 3s
  6000K .......... .......... .......... .......... .......... 43% 2.68M 3s
  6050K .......... .......... .......... .......... .......... 43% 3.62M 3s
  6100K .......... .......... .......... .......... .......... 43% 1.94M 3s
  6150K .......... .......... .......... .......... .......... 44% 6.52M 3s
  6200K .......... .......... .......... .......... .......... 44% 2.88M 3s
  6250K .......... .......... .......... .......... .......... 44% 2.50M 3s
  6300K .......... .......... .......... .......... .......... 45% 1.91M 3s
  6350K .......... .......... .......... .......... .......... 45% 1.92M 3s
  6400K .......... .......... .......... .......... .......... 46% 4.00M 3s
  6450K .......... .......... .......... .......... .......... 46% 2.91M 3s
  6500K .......... .......... .......... .......... .......... 46% 1.06M 3s
  6550K .......... .......... .......... .......... .......... 47% 3.40M 3s
  6600K .......... .......... .......... .......... .......... 47% 2.96M 3s
  6650K .......... .......... .......... .......... .......... 47% 2.58M 3s
  6700K .......... .......... .......... .......... .......... 48% 2.93M 3s
  6750K .......... .......... .......... .......... .......... 48% 1.93M 3s
  6800K .......... .......... .......... .......... .......... 48% 3.28M 3s
  6850K .......... .......... .......... .......... .......... 49% 1.51M 3s
  6900K .......... .......... .......... .......... .......... 49% 2.67M 3s
  6950K .......... .......... .......... .......... .......... 49% 2.68M 3s
  7000K .......... .......... .......... .......... .......... 50% 2.54M 3s
  7050K .......... .......... .......... .......... .......... 50% 3.30M 3s
  7100K .......... .......... .......... .......... .......... 51% 2.21M 3s
  7150K .......... .......... .......... .......... .......... 51% 1.93M 3s
  7200K .......... .......... .......... .......... .......... 51% 5.71M 3s
  7250K .......... .......... .......... .......... .......... 52% 3.03M 3s
  7300K .......... .......... .......... .......... .......... 52% 1.42M 3s
  7350K .......... .......... .......... .......... .......... 52% 2.69M 3s
  7400K .......... .......... .......... .......... .......... 53% 1.78M 3s
  7450K .......... .......... .......... .......... .......... 53% 2.36M 3s
  7500K .......... .......... .......... .......... .......... 53% 1.70M 3s
  7550K .......... .......... .......... .......... .......... 54% 1.99M 3s
  7600K .......... .......... .......... .......... .......... 54% 1.66M 3s
  7650K .......... .......... .......... .......... .......... 54% 5.01M 3s
  7700K .......... .......... .......... .......... .......... 55% 2.80M 3s
  7750K .......... .......... .......... .......... .......... 55% 3.11M 3s
  7800K .......... .......... .......... .......... .......... 56% 1.50M 3s
  7850K .......... .......... .......... .......... .......... 56% 1.93M 3s
  7900K .......... .......... .......... .......... .......... 56% 2.54M 2s
  7950K .......... .......... .......... .......... .......... 57% 2.83M 2s
  8000K .......... .......... .......... .......... .......... 57% 2.97M 2s
  8050K .......... .......... .......... .......... .......... 57% 3.06M 2s
  8100K .......... .......... .......... .......... .......... 58% 1.96M 2s
  8150K .......... .......... .......... .......... .......... 58% 2.49M 2s
  8200K .......... .......... .......... .......... .......... 58% 2.03M 2s
  8250K .......... .......... .......... .......... .......... 59% 1.82M 2s
  8300K .......... .......... .......... .......... .......... 59% 6.47M 2s
  8350K .......... .......... .......... .......... .......... 59% 1.77M 2s
  8400K .......... .......... .......... .......... .......... 60% 5.49M 2s
  8450K .......... .......... .......... .......... .......... 60% 2.01M 2s
  8500K .......... .......... .......... .......... .......... 61% 2.73M 2s
  8550K .......... .......... .......... .......... .......... 61% 2.18M 2s
  8600K .......... .......... .......... .......... .......... 61% 2.58M 2s
  8650K .......... .......... .......... .......... .......... 62% 3.52M 2s
  8700K .......... .......... .......... .......... .......... 62% 2.30M 2s
  8750K .......... .......... .......... .......... .......... 62% 2.30M 2s
  8800K .......... .......... .......... .......... .......... 63% 2.48M 2s
  8850K .......... .......... .......... .......... .......... 63% 1.38M 2s
  8900K .......... .......... .......... .......... .......... 63% 2.37M 2s
  8950K .......... .......... .......... .......... .......... 64% 3.86M 2s
  9000K .......... .......... .......... .......... .......... 64% 1.76M 2s
  9050K .......... .......... .......... .......... .......... 64% 3.06M 2s
  9100K .......... .......... .......... .......... .......... 65% 3.93M 2s
  9150K .......... .......... .......... .......... .......... 65% 2.30M 2s
  9200K .......... .......... .......... .......... .......... 66% 1.87M 2s
  9250K .......... .......... .......... .......... .......... 66% 2.78M 2s
  9300K .......... .......... .......... .......... .......... 66% 5.95M 2s
  9350K .......... .......... .......... .......... .......... 67% 2.72M 2s
  9400K .......... .......... .......... .......... .......... 67% 3.84M 2s
  9450K .......... .......... .......... .......... .......... 67% 1.31M 2s
  9500K .......... .......... .......... .......... .......... 68% 3.26M 2s
  9550K .......... .......... .......... .......... .......... 68% 1.41M 2s
  9600K .......... .......... .......... .......... .......... 68% 1.59M 2s
  9650K .......... .......... .......... .......... .......... 69% 2.49M 2s
  9700K .......... .......... .......... .......... .......... 69% 1.42M 2s
  9750K .......... .......... .......... .......... .......... 69% 2.01M 2s
  9800K .......... .......... .......... .......... .......... 70% 4.87M 2s
  9850K .......... .......... .......... .......... .......... 70% 2.96M 2s
  9900K .......... .......... .......... .......... .......... 71% 3.06M 2s
  9950K .......... .......... .......... .......... .......... 71% 1.59M 2s
 10000K .......... .......... .......... .......... .......... 71% 2.93M 2s
 10050K .......... .......... .......... .......... .......... 72% 1.69M 2s
 10100K .......... .......... .......... .......... .......... 72% 2.16M 2s
 10150K .......... .......... .......... .......... .......... 72% 1.98M 2s
 10200K .......... .......... .......... .......... .......... 73% 4.92M 2s
 10250K .......... .......... .......... .......... .......... 73% 1.52M 2s
 10300K .......... .......... .......... .......... .......... 73% 2.65M 2s
 10350K .......... .......... .......... .......... .......... 74% 2.17M 1s
 10400K .......... .......... .......... .......... .......... 74% 1.11M 1s
 10450K .......... .......... .......... .......... .......... 74% 3.25M 1s
 10500K .......... .......... .......... .......... .......... 75% 4.13M 1s
 10550K .......... .......... .......... .......... .......... 75% 2.70M 1s
 10600K .......... .......... .......... .......... .......... 76% 1.60M 1s
 10650K .......... .......... .......... .......... .......... 76% 2.94M 1s
 10700K .......... .......... .......... .......... .......... 76% 2.22M 1s
 10750K .......... .......... .......... .......... .......... 77% 3.10M 1s
 10800K .......... .......... .......... .......... .......... 77% 2.23M 1s
 10850K .......... .......... .......... .......... .......... 77% 2.98M 1s
 10900K .......... .......... .......... .......... .......... 78% 1.84M 1s
 10950K .......... .......... .......... .......... .......... 78% 7.46M 1s
 11000K .......... .......... .......... .......... .......... 78% 2.40M 1s
 11050K .......... .......... .......... .......... .......... 79% 7.71M 1s
 11100K .......... .......... .......... .......... .......... 79%  905K 1s
 11150K .......... .......... .......... .......... .......... 79% 1.42M 1s
 11200K .......... .......... .......... .......... .......... 80% 2.69M 1s
 11250K .......... .......... .......... .......... .......... 80% 2.23M 1s
 11300K .......... .......... .......... .......... .......... 81% 1.94M 1s
 11350K .......... .......... .......... .......... .......... 81% 4.10M 1s
 11400K .......... .......... .......... .......... .......... 81% 2.19M 1s
 11450K .......... .......... .......... .......... .......... 82% 2.20M 1s
 11500K .......... .......... .......... .......... .......... 82% 2.65M 1s
 11550K .......... .......... .......... .......... .......... 82% 1.73M 1s
 11600K .......... .......... .......... .......... .......... 83% 2.32M 1s
 11650K .......... .......... .......... .......... .......... 83% 1.53M 1s
 11700K .......... .......... .......... .......... .......... 83% 1.95M 1s
 11750K .......... .......... .......... .......... .......... 84% 2.56M 1s
 11800K .......... .......... .......... .......... .......... 84% 2.53M 1s
 11850K .......... .......... .......... .......... .......... 84% 3.19M 1s
 11900K .......... .......... .......... .......... .......... 85% 4.61M 1s
 11950K .......... .......... .......... .......... .......... 85% 1.75M 1s
 12000K .......... .......... .......... .......... .......... 86% 2.06M 1s
 12050K .......... .......... .......... .......... .......... 86% 3.59M 1s
 12100K .......... .......... .......... .......... .......... 86% 1.70M 1s
 12150K .......... .......... .......... .......... .......... 87% 2.69M 1s
 12200K .......... .......... .......... .......... .......... 87% 1.40M 1s
 12250K .......... .......... .......... .......... .......... 87% 2.41M 1s
 12300K .......... .......... .......... .......... .......... 88% 2.56M 1s
 12350K .......... .......... .......... .......... .......... 88% 1.40M 1s
 12400K .......... .......... .......... .......... .......... 88% 3.43M 1s
 12450K .......... .......... .......... .......... .......... 89% 5.77M 1s
 12500K .......... .......... .......... .......... .......... 89% 3.14M 1s
 12550K .......... .......... .......... .......... .......... 89% 1.29M 1s
 12600K .......... .......... .......... .......... .......... 90% 2.02M 1s
 12650K .......... .......... .......... .......... .......... 90% 4.26M 1s
 12700K .......... .......... .......... .......... .......... 91% 2.29M 1s
 12750K .......... .......... .......... .......... .......... 91% 3.19M 1s
 12800K .......... .......... .......... .......... .......... 91% 1.45M 0s
 12850K .......... .......... .......... .......... .......... 92% 1.57M 0s
 12900K .......... .......... .......... .......... .......... 92% 2.80M 0s
 12950K .......... .......... .......... .......... .......... 92% 2.73M 0s
 13000K .......... .......... .......... .......... .......... 93% 1.48M 0s
 13050K .......... .......... .......... .......... .......... 93% 2.39M 0s
 13100K .......... .......... .......... .......... .......... 93% 2.89M 0s
 13150K .......... .......... .......... .......... .......... 94% 1.44M 0s
 13200K .......... .......... .......... .......... .......... 94% 3.20M 0s
 13250K .......... .......... .......... .......... .......... 94% 3.56M 0s
 13300K .......... .......... .......... .......... .......... 95% 2.30M 0s
 13350K .......... .......... .......... .......... .......... 95% 2.56M 0s
 13400K .......... .......... .......... .......... .......... 96% 3.86M 0s
 13450K .......... .......... .......... .......... .......... 96% 1.62M 0s
 13500K .......... .......... .......... .......... .......... 96% 2.37M 0s
 13550K .......... .......... .......... .......... .......... 97% 2.01M 0s
 13600K .......... .......... .......... .......... .......... 97% 2.35M 0s
 13650K .......... .......... .......... .......... .......... 97% 1.57M 0s
 13700K .......... .......... .......... .......... .......... 98% 2.46M 0s
 13750K .......... .......... .......... .......... .......... 98% 4.10M 0s
 13800K .......... .......... .......... .......... .......... 98% 1.23M 0s
 13850K .......... .......... .......... .......... .......... 99% 2.65M 0s
 13900K .......... .......... .......... .......... .......... 99% 2.06M 0s
 13950K .......... .......... .......... .......... .......... 99% 3.39M 0s
 14000K .                                                     100% 3085G=5.9s

2020-12-16 06:18:37 (2.33 MB/s) - ‘vc_redist.x86.exe’ saved [14337656/14337656]

Executing cd /home/izzyj/Games/mod-organizer-2
------------------------------------------------------
sha256sum mismatch! Rename /home/izzyj/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.
------------------------------------------------------

**Comment by Arcstur** [comment]
Check klesha's response in the issue I posted, I had the exact same problem. 
https://github.com/rockerbacon/lutris-skyrimse-installers/issues/194#issuecomment-744887059
