### ISSUE TITLE
lutris 0.5.7.1-2 and MO2 2.2.2.1 upgrade

### ISSUE THREAD

**Issue by kleshas** [rockerbacon/modorganizer2-linux-installer#201]
Working through a new modlist, and tried updating MO2 via its upgrade functionality.  Seemed to work, get the splash screen but crashes.  I'll try using the latest version of Lutris (stayed on this version as it used to be the latest one that worked with your installer).

Is there a wait on something (lutris?) before you get a 2.3.2 installer?

[mo_interface.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/5847282/mo_interface.log)
[crash.txt](https://github.com/rockerbacon/lutris-skyrimse-installers/files/5847283/crash.txt)

**Comment by rockerbacon** [comment]
MO2 updated to 2.4.4 in #132
