### ISSUE TITLE
RaceMenu Overlays

### ISSUE THREAD

**Issue by Apex678** [rockerbacon/modorganizer2-linux-installer#205]
There is a problem with adding more overlays to RaceMenu. 

When editing the `[Overlays/Body]` section of the `skee64.ini` file to add more overlays, those changes are never recognised. It only ever has the default 3 for every body part I try to change. From what I can tell the `skee64.ini` file is never loaded for whatever reason. Other than that the mod works, but I really want to get this working correctly, I've spent an ungodly amount of time on this. I'll list some information below. Awesome project btw, keep up the good work. 

- Skyrim SE
- 2.8.6 Stable of this installer 
- Latest version of RaceMenu (I've also used an older version)
- No overlays 
- I tried creating an `skee64_custom.ini` with my changes and it didn't work
- The `skee64.log` never mentions `skee64.ini` (not sure if this is normal)
- The `skee64.log` file starts with `couldn't get trampoline interface` then `NetImmerse Override Enabled`
- The `skse64.log` file shows that RaceMenu loaded just fine 
- Other mods can use SKSE64 just fine
- I've done a fresh install and still no luck; Currently only have cleaned masters and RaceMenu 
- I made a post on the RaceMenu mod page but got no response 
- Interestingly the `skee64.ini` file shows the body section as having a default of 6 slots, however when I found the Github page for SKSE64Plugins, I looked at the skee/main.cpp code and the body sections default value is 3, which should be changed by the `skee64.ini` file. Which is what makes me believe that the config file isn't being read at all for some reason. I can't for the life of me figure out why or how to fix it. 

I haven't been modding all that long, or been on Github very long, if you need any more information then let me know.

**Comment by ale-saglia** [comment]
Still got the same problem, did you find any solution?

**Comment by Apex678** [comment]
> Still got the same problem, did you find any solution?

A few days ago I found 1 other person that solved this issue and it worked for me too. I was going to update this anyway so it's good that you reminded me. Installing the following resolved my problem: "PrivateProfileRedirector SE - Faster game start (INI file cacher)" /mods/18860 on Nexus. 

I'm running the latest version of everything. For reasons I barely understand this solves this issue on Linux. I'll mark this as solved. Although it would be useful to mention this somewhere.

**Comment by Apex678** [comment]
Installing https://www.nexusmods.com/skyrimspecialedition/mods/18860 fixes this issue
