### ISSUE TITLE
"Could not find proton"

### ISSUE THREAD

**Issue by SolarDifference** [rockerbacon/modorganizer2-linux-installer#207]
Mod organizer 2 installs beautifully, but when I click "play" I get the error in the attached screenshot. I'm running pop_os 20.10.

![Screenshot from 2021-02-10 21-06-412](https://user-images.githubusercontent.com/12777599/107598759-60761900-6be4-11eb-9207-82508feed4f4.png)

**Comment by graywolf-theheathen** [comment]
Same error here.

**Comment by RichDavis1** [comment]
Any luck on this?

**Comment by SolarDifference** [comment]
No luck on this so far Rich, sorry.

**Comment by rockerbacon** [comment]
Closing since the latest release no longer executes a Proton search.
