### ISSUE TITLE
Newer Proton Versions Fix and Break the Game

### ISSUE THREAD

**Issue by Thomdare** [rockerbacon/modorganizer2-linux-installer#213]
Hello, I've been trying to fix the fullscreen only issue with Fallout New Vegas for several days now. I have come to a half-solution, that is I can run it in windowed mode when I have the program use a newer version of Proton, however doing that prevents Mod Organizer from loading any mods other than NVSE. Does anyone have a solution? Any advice would be greatly appreciated.

**Comment by Thomdare** [comment]
Just a quick note, when I mean newer I don't mean 5.13 or Experimental. 5.13 still has the fullscreen issue but also loads no mods. Experimental refuses to start at all. I'm specifically referring to Glorious Eggroll's proton, which solves the fullscreen issue but loads no mods

**Comment by SleepyFugu** [comment]
That's not really an issue with this project, it's a known incompatibility of Mod Organizer 2's with recent versions of Proton. To my knowledge (I spent a week looking into this a couple of months back), there is no workaround outside of downgrading your proton version. There may be some more updated information on this here:

https://github.com/Modorganizer2/modorganizer/issues/372
