### ISSUE TITLE
sha256 Mismatch Returns

### ISSUE THREAD

**Issue by Retrograde-i486** [rockerbacon/modorganizer2-linux-installer#215]
Has anyone had any luck running this script lately? I've been doing my damnedest trying to troubleshoot this problem but i'm out of ideas. In theory the sha256 mismatch bug was fixed in winetricks: https://github.com/Winetricks/winetricks/issues/1713 17 days ago but I still can't get the installer to behave:

021-03-25 15:10:31 (58.0 MB/s) - ‘vc_redist.x86.exe’ saved [14319952/14319952]

Executing cd /games/mod-organizer-2
------------------------------------------------------
warning: sha256sum mismatch! Rename /home/{user}/.cache/winetricks/vcrun2019/vc_redist.x86.exe and try again.
-----------------------------------------------------

Coped the latest winetricks* 

From 

/home/<user>.local/share/lutris/runtime/winetricks

To
/usr/bin 

but still no joy.

**Comment by ciphersimian** [comment]
#61 

I fixed this by changing the sha256sum in the winetricks script, but then it just fails for a different reason because the new package from M$ is missing files.  I think this is going to require wine and winetricks updates.

**Comment by drewman** [comment]
I was able to get this installed by hacking on the winetricks script in `$HOME/.local/share/lutris/runtime/winetricks/winetricks` and changing the download links to download the versions that match the hashes.

Line 12805:
`https://aka.ms/vs/16/release/vc_redist.x86.exe` -> `https://download.visualstudio.microsoft.com/download/pr/8ecb9800-52fd-432d-83ee-d6e037e96cc2/50A3E92ADE4C2D8F310A2812D46322459104039B9DEADBD7FDD483B5C697C0C8/VC_redist.x86.exe`

Line 12825:
`https://aka.ms/vs/16/release/vc_redist.x64.exe` -> `https://download.visualstudio.microsoft.com/download/pr/89a3b9df-4a09-492e-8474-8f92c115c51d/B1A32C71A6B7D5978904FB223763263EA5A7EB23B2C44A0D60E90D234AD99178/VC_redist.x64.exe`

**Comment by Retrograde-i486** [comment]
Drew you are the man lol. So your fix didn't work initially for me, still was getting the mismatch errors. I ended up pulling down the vc_redist executables and getting the sha256 hashes from the links you posted and they were different. So maybe MS updated them again. I put those hashes into the winetricks file and it finally installed! So as far as I can tell, as of 3/26/2021 the hashes have been changed again:

New Hashes as of 03/26/2021

x86
w_download https://aka.ms/vs/16/release/vc_redist.x86.exe e830c313aa99656748f9d2ed582c28101eaaf75f5377e3fb104c761bf3f808b2

x64
w_download https://aka.ms/vs/16/release/vc_redist.x64.exe 015edd4e5d36e053b23a01adb77a2b12444d3fb6eccefe23e3a8cd6388616a16

 If I can figure out how to do a pull request with winetricks (little new to this) I'll let them know: https://github.com/Winetricks/winetricks/commit/19df518b16d246ee05f219425d0cae9864baee17

**Comment by pekempy** [comment]
Thanks Retrograde, the hashes you shared worked.

For me it was
line 12838 (x86)
line 12859 (x64)
line 12888 (x86 again)
line 12915 (x64 again)

**Comment by ciphersimian** [comment]
So @drewman, @Retrograde-i486, and @pekempy... what game are you trying to install and what distro, etc?  I made the same changes described here which indeed got me past the sha256sum mismatch, but now it's just failing with a different error:

```
00f0:err:msi:ACTION_InstallFiles compressed file wasn't installed (L"api_ms_win_core_console_l1_1_0.dll")
00f0:err:msi:execute_script Execution of script 0 halted; action L"InstallFiles" returned 1603
00f0:err:msi:ITERATE_Actions Execution halted, action L"InstallFinalize" returned 1603
00f0:fixme:wuapi:automatic_updates_Resume 
00f0:fixme:ver:GetCurrentPackageId (0068FE94 00000000): stub
00dc:fixme:ver:GetCurrentPackageId (0068FE94 00000000): stub
0024:fixme:ver:GetCurrentPackageId (0031FE94 00000000): stub
------------------------------------------------------
warning: Note: command wine vc_redist.x86.exe /q returned status 67. Aborting.
------------------------------------------------------
```

I'm trying to run oldrim (Skyrim LE) on Ubuntu 20.04.

```
$ cat /etc/os-release | grep VERSION=
VERSION="20.04.2 LTS (Focal Fossa)"
$ lutris --version
2021-03-29 19:49:14,432: Initializing lutris
2021-03-29 19:49:14,951: Downloading DXVK releases to /home/ciphersimian/.local/share/lutris/runtime/dxvk/dxvk_versions.json
2021-03-29 19:49:14,955: Runtime updated. Initialization complete.
lutris-0.5.8.3
$ wine --version
wine-6.0-rc1 (Staging)
```

**Comment by Retrograde-i486** [comment]
I was installing ModOrganizer 2 for use with Skyrim SE. I'm on Garuda Linux 5.11.8-140-tkg-bmq. Everything's working here and just took a break from playing. 

Make sure you're adding the new hashes under the **load_vcrun2019()** section of your winetricks file (located here: /home/<username>/.local/share/lutris/runtime/winetricks/ 
There are multiple load_vcrun20XX sections for various years, I only modied the 2019 section of my file.

Should look like this (I bolded the sections I have):
**x86**


load_vcrun2019()
{
    # https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
    # 2019/12/26: e59ae3e886bd4571a811fe31a47959ae5c40d87c583f786816c60440252cd7ec
    # 2020/03/23: ac96016f1511ae3eb5ec9de04551146fe351b7f97858dcd67163912e2302f5d6
    # 2020/05/20: a06aac66734a618ab33c1522920654ddfc44fc13cafaa0f0ab85b199c3d51dc0
    # 2020/08/05: b4d433e2f66b30b478c0d080ccd5217ca2a963c16e90caf10b1e0592b7d8d519
    # 2020/10/03: caa38fd474164a38ab47ac1755c8ccca5ccfacfa9a874f62609e6439924e87ec
    # 2020/11/13: 50a3e92ade4c2d8f310a2812d46322459104039b9deadbd7fdd483b5c697c0c8
    # 2021/03/09: 4521ed84b9b1679a706e719423d54ef5e413dc50dde1cf362232d7359d7e89c4
    **w_download https://aka.ms/vs/16/release/vc_redist.x86.exe e830c313aa99656748f9d2ed582c28101eaaf75f5377e3fb104c761bf3f808b2**

**x64**
**w_download https://aka.ms/vs/16/release/vc_redist.x64.exe 015edd4e5d36e053b23a01adb77a2b12444d3fb6eccefe23e3a8cd6388616a16**

**Comment by stoyanovgeorge** [comment]
Apparently Microsoft is updating those exe files pretty often, because my SHA256sums were different. The easiest way would be to download them on your HDD and calculate the `sha256sum <file_name>` and update the sums in the `$HOME/.local/share/lutris/runtime/winetricks/winetricks`

**Comment by KJNeko** [comment]
Might be bad practice to do this since your skipping checks but adding `--force` to `line 320 in modorganizer2.yml` before the `-q` flag will skip the sha256sum checks.

**Comment by rockerbacon** [comment]
Closing since the latest release no longer applies vcrun2019 to the prefix.
