### ISSUE TITLE
FNIS Error 5

### ISSUE THREAD

**Issue by thucar** [rockerbacon/modorganizer2-linux-installer#217]
I'm able to get everything else running for Skyrim SE but for the life of be I can not solve the FNIS error 5 issue.
I've installed Skyrim via Steam, verified it runs. Then ran the Lutris script to install MO2. No errors to be seen. MO2 is installed and I'm able to install mods and they show up in game.

When installing FNIS, I'm excluding all the language files in its tools folder, except for the English one because it complains about unknown characters if I do not. After excluding the extra language files, it installs fine. The issue manifests when I try to run FNIS GenerateFNISforUsers. This is what I get immediately after hitting Update FNIS Behavior
![image](https://user-images.githubusercontent.com/2293862/116188929-dd6b5600-a730-11eb-8b17-419c59500533.png)

I suspect it's a wine issue because when I run FNIS manually using wine outside Lutris and MO2, it runs fine but does not pick up any animations from installed mods.

Any ideas what to try or where to look?

**Comment by cverstege** [comment]
Performing the symlink described here, allowed me to run FNIS without any Errors from MO2 for Skyrim SE:
https://spacebums.co.uk/post/tes_skyrim_modding_guide_linux/#fnis-fores-new-idles-in-skyrim
```
cd /path_to_your/SteamLibrary/steamapps/common/Skyrim/Data
ln -s 'path_to_your/ModOrganizer/mods/FNIS Behavior 7_5-11811-7-5-1566571166/tools' tools
```
