### ISSUE TITLE
warning: Note: command wine regedit /S C:\windows\Temp\override-dll.reg returned status 53. Aborting.

### ISSUE THREAD

**Issue by tauin** [rockerbacon/modorganizer2-linux-installer#218]
when running the script it comes up with a bunch of errors saying something along the lines of

err:module:import_dll Library api-ms-win-core-util-l1-1-0.dll (which is needed by L"C:\\windows\\system32\\ucrtbase.dll") not found

multiple times with variation on what its loading and what is required

**Comment by tauin** [comment]
any update on this? im not sure what could be causing it

**Comment by ptkato** [comment]
I was having problems with #61, I fixed that by manually changing the sha256sum in the winetricks script, only to bump onto this error, I get the same thing: https://pastebin.com/Xxbvm9ja

```
Executing load_vcrun2019 
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcr140 ucrtbase vcomp140 vcruntime140
Executing wine regedit /S C:\windows\Temp\override-dll.reg
0208:err:module:import_dll Library ucrtbase.dll (which is needed by L"C:\\windows\\system32\\sechost.dll") not found
0208:err:module:import_dll Library sechost.dll (which is needed by L"C:\\windows\\system32\\advapi32.dll") not found
0208:err:module:import_dll Library ucrtbase.dll (which is needed by L"C:\\windows\\system32\\advapi32.dll") not found

...

0208:err:module:import_dll Library version.dll (which is needed by L"C:\\windows\\system32\\user32.dll") not found
0208:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\start.exe") not found
0208:err:module:LdrInitializeThunk Importing dlls for L"C:\\windows\\system32\\start.exe" failed, status c0000135
------------------------------------------------------
warning: Note: command wine regedit /S C:\windows\Temp\override-dll.reg returned status 53. Aborting.
```

**Comment by kleshas** [comment]
I get something similar: /mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64/ucrtbase.dll: Permission denied

**Comment by kleshas** [comment]
I have a similar issue with ucrtbase.dll
 `Executing cabextract -q --directory=/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64 /mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll
/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32/a10: WARNING; possible 9136 extra bytes at end of file.
/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64/ucrtbase.dll: Permission denied
------------------------------------------------------
warning: Note: command cabextract -q --directory=/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64 /mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll returned status 1. Aborting.
`

**Comment by LuxLucian** [comment]
Same issue here

https://pastebin.com/Pv4kAnrh

**Comment by LuxLucian** [comment]
> Same issue here
> 
> https://pastebin.com/Pv4kAnrh

Running Skyrim SE through steam a second time seemed to fix this. Could be worth a shot for anyone having this issue

**Comment by jaxarthur** [comment]
The issue is an outdated winetricks lutris runner. There is a bug with winetricks where it can't install vcrun2019 and it actually borks your wine prefix. To fix this issue you can update the wine tricks manually  using the command "~/.local/share/lutris/runtime/winetricks/winetricks --self-update" (There is probably a better way but I don't want to try and find it.) If you get still get the issue try backing up and deleting the prefix for SkyrimSE in the steamcompat folder.

**Comment by ptkato** [comment]
> The issue is an outdated winetricks lutris runner. There is a bug with winetricks where it can't install vcrun2019 and it actually borks your wine prefix. To fix this issue you can update the wine tricks manually using the command "~/.local/share/lutris/runtime/winetricks/winetricks --self-update" (There is probably a better way but I don't want to try and find it.) If you get still get the issue try backing up and deleting the prefix for SkyrimSE in the steamcompat folder.

```bash
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks > $HOME/.local/share/lutris/runtime/winetricks/winetricks
```

**Comment by kleshas** [comment]
That didn't fix my issue I listed above, though I admit that it might be a different issue to the OP (there is a common file in the error which is why I posted)
