### ISSUE TITLE
Installer fails on setting up wineprefix

### ISSUE THREAD

**Issue by will-hedges** [rockerbacon/modorganizer2-linux-installer#224]
No matter what I've tried, I get stuck on this stage. Feels like I'm close but at this point, don't really know what to try next. I hope this is a helpful issue to open, and if anyone has any advice, I'd greatly appreciate it.

Previous attempts to fix:
- Fixed sha256sum mismatch by:
  - updating vc_redist.x64.exe and x86 in /home/$USER/.cache/winetricks/vcrun2019 [#61](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/61)
  - updating checksums in /home/$USER/.local/share/lutris/runtime/winetricks/winetricks [#215](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/215)
- Changed lutris version of winetricks [#194](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/194#issuecomment-744887059)
- Followed steps to avoid ExtractFailure [#173](https://github.com/rockerbacon/lutris-skyrimse-installers/issues/173)
```
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx terminate
------------------------------------------------------
Executing cabextract -q --directory=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32 /home/will/.cache/winetricks/vcrun2019/vc_redist.x86.exe -F a10
Executing cabextract -q --directory=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64 /home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll
/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win32/a10: WARNING; possible 9136 extra bytes at end of file.
Executing cd /home/will/.cache/winetricks/vcrun2019
Executing wine vc_redist.x86.exe /q
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.9 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
009c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
009c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0110:fixme:advapi:DecryptFileW (L"C:\\users\\steamuser\\Temp\\{8C648D1F-A7ED-40C4-9960-8D4AA45828F2}\\", 00000000): stub
011c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
011c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
011c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
011c:fixme:advapi:DecryptFileW (L"C:\\users\\steamuser\\Temp\\{E8C4830E-E11B-465B-BFA6-F2FDB7732D21}\\", 00000000): stub
0128:fixme:shell:SHAutoComplete stub
011c:fixme:advapi:DecryptFileW (L"C:\\users\\steamuser\\Temp\\{E8C4830E-E11B-465B-BFA6-F2FDB7732D21}\\", 00000000): stub
011c:fixme:exec:SHELL_execute flags ignored: 0x00000100
0130:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0130:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0130:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0130:fixme:ole:CoInitializeSecurity 0057F5E8, -1, 00000000, 00000000, 6, 2, 00000000, 12288, 00000000 stub
0130:fixme:wuapi:automatic_updates_Pause 
0130:fixme:sfc:SRSetRestorePointW 0057F4B0 0057F6C0
0130:fixme:wuapi:automatic_updates_Resume 
0130:fixme:ver:GetCurrentPackageId (0057FE94 00000000): stub
011c:fixme:ver:GetCurrentPackageId (0057FE94 00000000): stub
0110:fixme:ver:GetCurrentPackageId (0057FE94 00000000): stub
Using native,builtin override for following DLLs: vcruntime140_1
Executing wine regedit /S C:\windows\Temp\override-dll.reg
0144:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0144:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
014c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
014c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0154:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0154:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
015c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
015c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0164:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0164:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
016c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
016c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Executing cabextract -q --directory=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64 /home/will/.cache/winetricks/vcrun2019/vc_redist.x64.exe -F a10
Executing cabextract -q --directory=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/system32 /home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64/a10 -F ucrtbase.dll
/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64/a10: no valid cabinets found
------------------------------------------------------
warning: Note: command cabextract -q --directory=/home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/system32 /home/will/.steam/debian-installation/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64/a10 -F ucrtbase.dll returned status 1. Aborting.
------------------------------------------------------
```
Upon terminal exit, I get the error

`I can't move /home/will/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation, it does not exist`

**Comment by kleshas** [comment]
Very similar to an error I've had - make sure you've set the game to use Proton 5.0 before running the installer (and also run the game once after changing Proton version).

**Comment by chemicalwill** [comment]
> Very similar to an error I've had - make sure you've set the game to use Proton 5.0 before running the installer (and also run the game once after changing Proton version).

Thanks for letting me know. I've double checked that I have it set in both spots:

![Screenshot from 2021-06-03 10-22-35](https://user-images.githubusercontent.com/36576135/120670364-f7960380-c455-11eb-88d6-ee5caa8a1606.png)
![Screenshot from 2021-06-03 10-22-18](https://user-images.githubusercontent.com/36576135/120670369-f8c73080-c455-11eb-844c-a9f0bf6334e4.png)

**Comment by averycoolbean** [comment]
im having this same issue, switching to proton 5.0 and launching the game did not resolve it either

**Comment by averycoolbean** [comment]
`------------------------------------------------------
Executing wine winecfg -v winxp64
------------------------------------------------------
warning: Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx terminate
------------------------------------------------------
Executing cabextract -q --directory=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win32 /home/bean/.cache/winetricks/vcrun2019/vc_redist.x86.exe -F a10
Executing cabextract -q --directory=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/syswow64 /home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win32/a10 -F ucrtbase.dll
/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win32/a10: WARNING; possible 9136 extra bytes at end of file.
Executing cd /home/bean/.cache/winetricks/vcrun2019
Executing wine vc_redist.x86.exe /q
0024:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0024:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
0024:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{C026DE8B-E873-4E28-9066-06C7047998D4}\\", 00000000): stub
0108:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
0108:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0108:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
0108:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{FB85DB67-B2B6-4F2C-AAF9-B574D0E57F70}\\", 00000000): stub
0114:fixme:shell:SHAutoComplete stub
0108:fixme:advapi:DecryptFileW (L"C:\\windows\\Temp\\{FB85DB67-B2B6-4F2C-AAF9-B574D0E57F70}\\", 00000000): stub
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
011c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
011c:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
011c:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
011c:fixme:ole:CoInitializeSecurity 0032F5E8, -1, 00000000, 00000000, 6, 2, 00000000, 12288, 00000000 stub
011c:fixme:wuapi:automatic_updates_Pause 
011c:fixme:sfc:SRSetRestorePointW 0032F4B0 0032F6C0
0128:fixme:advapi:DecryptFileW (L"C:\\ProgramData\\Package Cache\\{7D75664A-6C04-424C-82A1-EE88913E5F16}v14.29.30037\\packages\\vcRuntimeMinimum_x86\\vc_runtimeMinimum_x86.msi", 00000000): stub
0128:fixme:advapi:DecryptFileW (L"C:\\ProgramData\\Package Cache\\{7D75664A-6C04-424C-82A1-EE88913E5F16}v14.29.30037\\packages\\vcRuntimeMinimum_x86\\cab1.cab", 00000000): stub
0128:fixme:advapi:DecryptFileW (L"C:\\ProgramData\\Package Cache\\{01FAEC41-B3BC-44F4-B185-5E8475AEB855}v14.29.30037\\packages\\vcRuntimeAdditional_x86\\vc_runtimeAdditional_x86.msi", 00000000): stub
0128:fixme:advapi:DecryptFileW (L"C:\\ProgramData\\Package Cache\\{01FAEC41-B3BC-44F4-B185-5E8475AEB855}v14.29.30037\\packages\\vcRuntimeAdditional_x86\\cab1.cab", 00000000): stub
011c:fixme:file:NtLockFile I/O completion on lock not implemented yet
011c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
011c:fixme:wuapi:automatic_updates_Resume 
011c:fixme:ver:GetCurrentPackageId (0032FE94 00000000): stub
0108:fixme:ver:GetCurrentPackageId (0032FE94 00000000): stub
0024:fixme:ver:GetCurrentPackageId (0032FE94 00000000): stub
Using native,builtin override for following DLLs: vcruntime140_1
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
Executing cabextract -q --directory=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win64 /home/bean/.cache/winetricks/vcrun2019/vc_redist.x64.exe -F a10
Executing cabextract -q --directory=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 /home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win64/a10 -F ucrtbase.dll
/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win64/a10: no valid cabinets found
------------------------------------------------------
warning: Note: command cabextract -q --directory=/home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/system32 /home/bean/.local/share/Steam/steamapps/compatdata/22380/pfx/dosdevices/c:/windows/temp/win64/a10 -F ucrtbase.dll returned status 1. Aborting.
------------------------------------------------------`

**Comment by Drose221193** [comment]
Has anyone who previously commented on this found a solution? I am getting the same error when I tried installing today.

**Comment by kleshas** [comment]
This was what I did last time, just in case there's something you missed

Change Lutris to version 0.5.7.1 (in arch, using the application downgrade)
Run SkyrimSE once from steam with Proton 5.0-10 specified.

cd "${HOME}/.local/share/lutris/runtime/winetricks"
sudo mv winetricks old_winetricks
sudo wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
sudo chmod +x winetricks
(this is instead of --self-update as that updates the incorrect winetricks instance used in the MO2 install)

copy the new vcredist files.

lutris -i ~/Downloads/modorganizer.yml
