### ISSUE TITLE
error during install: when running cabextract it says "no valid cabinets found"

### ISSUE THREAD

**Issue by Erdragh** [rockerbacon/modorganizer2-linux-installer#228]
I am trying to install MO2 for Skyrim Special Edition for a long time now, and everytime I try to, I get an error concerning the cabextract command:
```
cabextract -q --directory=/home/erdragh/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/system32 /home/erdragh/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64/a10 -F ucrtbase.dll
```
of which the output is:
```
/home/erdragh/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/win64/a10: no valid cabinets found
```

Because of this, the installation can never complete.

[This is the full command line log when I try to install it](https://gist.github.com/Erdragh/aad86dc176c8f62088132847269764b3)

I am running Artix Linux and the latest version of lutris.
Neither storage, RAM, CPU nor GPU Power should be an issue:
```
OS: Artix Linux x86_64 
Host: X470 AORUS ULTRA GAMING 
Kernel: 5.12.12-zen1-1-zen 
Packages: 1446 (pacman)
Shell: bash 5.1.8 
Resolution: 1680x1050, 3440x1440 
DE: Plasma 5.22.2 
WM: KWin 
CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz 
GPU: NVIDIA GeForce RTX 2070 Rev. A 
Memory: 4851MiB / 16011MiB 
```
I am not well enough accustomed with wine and proton commands to realize what the issue might be, so any help is really welcome.

Thanks in Advance

**Comment by kleshas** [comment]
I got that error when I forgot to change the proton version for SE in steam to 5.0.
