### ISSUE TITLE
Game has no audio!

### ISSUE THREAD

**Issue by georgetnf** [rockerbacon/modorganizer2-linux-installer#235]
Installed and mods show up when game launches via MO2.

But has no sound, for me in the Steam launcher i have to put a special command.

like this: WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90 %command%

So how do i fix this on MO2?

if i launch the game via steam the mods dont show up!

**Comment by SchottyKid** [comment]
I have the same issue. I've tried assigning a GloriousEggroll version of Proton through Steam (not sure if this has any effect on MO2.) I've also tried adding the "WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90" environment variables through the game options (arguments) and system options. **None of these possible fixes were successful.** In my testing, at least.

**Comment by gtgremista** [comment]
well, i chose go to Vortex and use LOOT to organize my mod list, maybe i use MO2 when i play New Vegas. 

but for now Fallout 4/Skyrim i use vortex.

**Comment by TGRCdev** [comment]
I'm running Mod Organizer for Oblivion on Arch

I initially had no audio when I ran Oblivion through MO, but I fixed it by installing `lib32-libpulse` from the `multilib` repository.
