### ISSUE TITLE
MO2 Doesn't open (SkyrimSE)

### ISSUE THREAD

**Issue by Teruithi265** [rockerbacon/modorganizer2-linux-installer#238]
### I start the MO2 throught the lutris, but nothing happens, when i open the log show me this message:
        lutris-wrapper: Mod Organizer 2
        Running gamemoderun /home/gabrielto/Games/mod-organizer-2/run.sh
        Initial process has started with pid 133327
        Start monitoring process.
        gamemodeauto: 
        Searching for Steam in '/home/gabrielto/.local/share/Steam'
        Found Steam
        Searching for Steam in '/home/gabrielto/.var/app/com.valvesoftware.Steam/.local/share/Steam'
        Searching for game in library '/home/gabrielto/.local/share/Steam'
        Found game
        Searching for 'Proton 5.0' in library '/home/gabrielto/.local/share/Steam'
        gamemodeauto: 
        gamemodeauto: 
        Found Proton
        gamemodeauto: 
        gamemodeauto: 
        gamemodeauto: 
        
        
	        PATH='/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin:/home/gabrielto/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin' \
	        LD_LIBRARY_PATH='/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/libfakeroot:/usr/lib32:/usr/lib/openmpi:/usr/lib:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i368-linux-gnu:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/gabrielto/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib' \
	        STEAM_COMPAT_DATA_PATH='/home/gabrielto/.local/share/Steam/steamapps/compatdata/489830' \
	        SteamGameId=489830 \
	        SteamAppId=489830 \
	        WINEDLLOVERRIDES='xaudio2_7=n,b;' PULSE_LATENCY_MSEC=90 \
	        \
	        '/home/gabrielto/.local/share/Steam/steamapps/common/Proton 5.0/proton' run '/home/gabrielto/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe' 
        
        
        gamemodeauto: 
        gamemodeauto: 
        gamemodeauto: 
        fsync: up and running.
        wine: Call from 0x7b00fc3e to unimplemented function shell32.dll.SHGetFolderPathW, aborting
        wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 000000007B00FC3E (thread 002c), starting debugger...
        gamemodeauto: 
        Monitored process exited.
        Initial process has exited (return code: 0)
        All monitored processes have exited.
        Exit with returncode 0

**I tried with different versions of wine, but none of them worked**

**Comment by bouncingjohn** [comment]
I was getting a similar error.  I'm pretty sure it was caused by previously running SkyrimSE with a later version of Proton.

To fix: delete the game folder (489830) in compatdata - set the version of Proton that SSE uses to 5.0-10 - run the game once through Steam (to regenerate the folder in compatdata) - install MO2.

There's a YouTube video by GloriousEggroll detailing most of this procedure (plus some other potential problems.)

**Comment by GabrielTeruithi** [comment]
> I was getting a similar error. I'm pretty sure it was caused by previously running SkyrimSE with a later version of Proton.
> 
> To fix: delete the game folder (489830) in compatdata - set the version of Proton that SSE uses to 5.0-10 - run the game once through Steam (to regenerate the folder in compatdata) - install MO2.
> 
> There's a YouTube video by GloriousEggroll detailing most of this procedure (plus some other potential problems.)

Work as a charm, thanks very much!!

**Comment by bpgerber** [comment]
Is this caused by a different Proton version (I had the same issue by using a "GE" version)? Are there any plans to make it not dependent on 5.0-10 in the future?

**Comment by rockerbacon** [comment]
> Is this caused by a different Proton version (I had the same issue by using a "GE" version)? Are there any plans to make it not dependent on 5.0-10 in the future?

It's definitely something I want but it's a little tricky. Mod Organizer 2 depends on USVFS to load mods and that is broken on most Wine versions.

My current plans are to improve support for custom versions, although I can't guarantee they'll improve anything over the official 5.0.

**Comment by rockerbacon** [comment]
I'll try to improve this process a little in the installer itself, be it through some automation or better instructions. Steam doesn't handle switching Proton versions as well as it should.

**Comment by rockerbacon** [comment]
Completed in #506
