### ISSUE TITLE
Newbie solution for “Can’t find appID”, and MO2 not opening. 

### ISSUE THREAD

**Issue by Slippingstones** [rockerbacon/modorganizer2-linux-installer#246]
Hi I haven’t seen this anywhere yet.

 Before installing ANYTHING create a new SteamLibrary in Home, or Documents. Really anywhere that isn’t normally a Hidden folder. If you already installed it in the base steam directory Re-install.

Top Left of steam > settings > downloads > steamlibrary > Big Plus button +++

If you already have any game listed installed, and can’t figure out why MO2 isn’t loading go to your steamlibrary then steamapps in my case Documents >Steam Games > steamapps then open the compatdata folder. IT CONTAINS YOUR PROTON DATA.  Delete the appID for whatever game your M02 is for then reopen the game with PROTON 5.0-10 IN STEAM. It will recreate the Proton windows environment. Just swapping your game to proton 5 will cause the game to crash, and you to be heck of confused.  MO2 should be reinstalled after this so it can install itself using proton 5.

I am running Fedora 34. If this helps anyone I’m glad. I know it’s simple, but Linux is confusing especially if you are a new user like myself. The guides are small, and expect you to understand things that you just don’t. Good luck, and I hope maybe the author edits their read me to mention installing outside of the default steam directory soon.

If you came this far, and your NXM links aren’t working make sure you have BASH, or ZSH installed as your default shell. Then reinstall the MO2 app in lutris. The script provided with this doesn’t work with shells from newbie guides like Fish, and that is a problem with Fish not the script. I found this somewhere deep in the issues section, and can’t remember the ID.

**Comment by rockerbacon** [comment]
Closing, since none of this should be necessary in newer versions
