### ISSUE TITLE
Mods with Textures not loading - Fallout4

### ISSUE THREAD

**Issue by sum-rock** [rockerbacon/modorganizer2-linux-installer#263]
### Intro

I've been wracking my brain here on this one. It is certainly possible I'm making a dumb mistake with configurations but I've exhausted my troubleshooting options, so here it is...

### Issue

Fallout 4 mods appear to be loading the .esp files only. The general functionality of a mod is intact but the display is absent. In other words there are no meshes or textures. For example, when I install an additional weapon mod (e.g., M2216 Stand Alone), I can use the console to give myself the weapon which appears in my inventory. When it is equipped, my character is holding an invisible, but functional weapon. This issue is reproducible with any mods that I attempt to install. It is especially apparent in any re-texture (e.g., Vivid Fallout). 

I believe this is an issue related to the Virtual File System but I'm unsure of the expected behavior. Within MO2 on the right panel under the data tab I can find what I want the <code>../Fallout 4/Data</code> directory to look like. However, I do not think that what is represented there is actually being accessed by the game. What configuration options are there related to this VFS? Are there options I can throw into a shell script?

### Setup 
  - openSUSE Tumbleweed
  - Fallout 4
  - Separate game drive for Steam Library
  - Mod Organizer 2 installed from Lutris
  - Mod Organizer 2 install and mod instance folder on the same drive as Steam Library
  - Using Proton 5, enforced within steam options

### Sanity Checks
  - Yes, the mods are installed and activated.
  - Yes, I am running the F4SE from MO2.
  - Could I be missing something else dumb?

**Comment by otikscypi** [comment]
Sounds like you may have problem with ArchiveInvalidation. 
See this: 
https://www.nexusmods.com/fallout4/mods/4421
