### ISSUE TITLE
3.0.2 bash installer

### ISSUE THREAD

**Issue by kleshas** [rockerbacon/modorganizer2-linux-installer#265]
Installed fine.  Looks like skse64 2.1.4 was installed (ie the AE prelim version).  I assume this is expected?

**Comment by rockerbacon** [comment]
> Looks like skse64 2.1.4 was installed (ie the AE prelim version). I assume this is expected?
Yes, I updated it to install whatever was latest during my testings. I'll make sure to rollback to the latest pre-AE version for the stable release.

**Comment by kleshas** [comment]
Cool, no problem here as I just copied back the 2 skse files from SE. Installer had no errors, and game plays fine.
Good to see you back on this project :)

**Comment by rockerbacon** [comment]
Closing because version 3 has been released.
