### ISSUE TITLE
Testing needed: MO2 2.4.4

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#270]
Keeping this issue here for people to report tests results on pre-release [3.1.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/3.1.0) which updates MO2 to version 2.4.4.

My initial tests suggest everything is working fine on Fedora 35.

**Comment by kleshas** [comment]
I did an in-place install (ie over the top of existing one).  Installed with no errors.
Running MO2 from lutris, errored out.  Re-running gave this error
'failed to laod plugin installer_fomod_csharp.dll'

Installed to new folder and ran run.sh from command line:
error:  'Assertion failed: 0, file ../../../../proton/wine/dlls/mscoree/corruntimehost.c, line 1299'

**Comment by rockerbacon** [comment]
> I did an in-place install (ie over the top of existing one). Installed with no errors. Running MO2 from lutris, errored out. Re-running gave this error 'failed to load plugin installer_fomod_csharp.dll' Skipping this plugin next time and the process silently crashes.
> 
> Installed to new folder and ran run.sh from command line: error: 'Assertion failed: 0, file ../../../../proton/wine/dlls/mscoree/corruntimehost.c, line 1299'
> 
> dotnet48 is installed.

What distro are you using?

**Comment by kleshas** [comment]
arch, sway WM

**Comment by rockerbacon** [comment]
Can you check if `./run.sh --system-libs` produces any different results?

**Comment by kleshas** [comment]
same error.
[2022-01-05 18:52:48.951 W] user wants to skip plugin 'installer_omod.dll'
Assertion failed: 0, file ../../../../proton/wine/dlls/mscoree/corruntimehost.c, line 1299

If I remove the 2 dlls mentioned in the other issue, I get a long-winded error, but MO2 does load up, and seems to work fine

**Comment by rockerbacon** [comment]
I could not reproduce the first issue, the fomod plugin does not cause any issues on my end. You're running with Proton 5.0, right? I'll need input from more people on that one.

I could reproduce the second issue on all test installations but not on my main one. I managed to track the problem down to the "Python Proxy" plugin, disabling it in _Settings > Plugins > Proxy_ makes the error go away.
IIRC this plugin never worked and MO2 would prompt you to disable it on startup. The difference now seems to be that there is no prompt and you just get constant errors.

I'll run a few more tests and see what can be done about the Python Proxy problem. The offender seems to be a Win32 API call to [RtlIpv6AddressToStringA](https://docs.microsoft.com/en-us/windows/win32/api/ip2string/nf-ip2string-rtlipv6addresstostringa)

**Comment by kleshas** [comment]
> disabling it in _Settings > Plugins > Proxy_ makes the error go away.

Confirmed.

Yes, proton 5.0 (set in steam)

**Comment by rockerbacon** [comment]
The Python Proxy issue seems to simply be Proton 5.0 being too old. I quickly tested newer Proton versions and they have no problem loading the plugin.

The current installer does not work with newer Proton versions, though. I'm still running some tests to see if there's a way to update Proton.

**Comment by kleshas** [comment]
Been playing w/ MO2 all day.  Nice and fast loading up, using nexus mod download works as well as "open in nexusmods' in MO2, BUT super slow when updating mods etc.  Looks like it's single-threaded; processes main, wineserver and tabtip.exe are hogging the CPU continually.  No idea why tabtip should be running (I do have a display tablet, but it's not in use atm)

**Comment by rockerbacon** [comment]
Pre-release [4.0.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.0.0) is out, providing the needed Proton update to fix the plugin loading issues.

Refer to #275 for details on the Proton update.

**Comment by Karce** [comment]
I was able to launch skyrim se using pre-release 4.0.0 on Arch.

I had to install the `mingw-w64-gcc` and `mingw-w64-winpthreads` packages and then compile the steam-redirector. After that the installation went fine and I was able to launch MO2 through steam by pressing the play button and then I could launch SkyrimSE fine through MO2. I guess my only concern with this method is Steam updating games when you launch them this way.

**Comment by rockerbacon** [comment]
@Karce was the recompilation just a personal preference or did you run into issues with the pre-compiled binaries?

**Comment by Karce** [comment]
Ah sorry I didn't realize there were pre-compiled binaries. I just checked out the release tag in git and didn't download the release from GitHub, which was why the binaries were missing for me.

I just retried the release binaries you provided in the GitHub release and those worked for me without doing anything else.

**Comment by kleshas** [comment]
ran install.sh 2>error.log.  Attached is the result.  The errors were at the every end of the install process, which actually returned a "installation succcessful".   Running skyrim from steam (if I'm reading the changes for this install correctly, this is the correct way to run MO2 now?), results in a quick flash of a screen, then it CTDs.
[errormo2.log](https://github.com/rockerbacon/modorganizer2-linux-installer/files/7831315/errormo2.log)

**Comment by rockerbacon** [comment]
> ran 4.0.0's install.sh 2>error.log. Attached is the result. The errors were at the every end of the install process, which actually returned a "installation succcessful". Running skyrim from steam (if I'm reading the changes for this install correctly, this is the correct way to run MO2 now?), results in a quick flash of a screen, then it CTDs. If it makes a difference, there is a working MO2 install run from lutris still (different install folder to this attempt). [errormo2.log](https://github.com/rockerbacon/modorganizer2-linux-installer/files/7831315/errormo2.log)
> 

It looks like wine crashed pretty hard when trying to run winetricks. The installer has a bug where it cannot properly detect winetricks errors, that's why it showed the installation was successful.

If you changed Proton versions enough times it is possible your game's prefix may be broken (wine doesn't like certain version changes). I'd suggest re-creating it:
1. Go to `your steam library/steamapps/compatdata` and delete the folder 489830 (I'm assuming you're talking about SkyrimSE, if not you'll need to look at the appid for the game [here](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/gamesinfo))
2. Run the game on Steam again. You'll have a clean prefix once it finishes first time setup
3. Re-run the installer

> edit: reading through #275 - what do we do if/when we want to run skyrimse.exe itself? (eg to reset the skyrimprefs). Also ~/.steam/steam/userdata/<userid?>/config/shortcuts.vdf doesn't exist on my system. In fact, shortcuts.vdf doesn't exist anywhere.

The installer never removes the original .exe, it just renames it, you just have to add it as an executable in Mod Organizer 2 and you'll be able to run it.

The shortcuts file only keeps track of non-Steam applications added as shortcuts, it'll only exist if you have at least one shortcut. I also have no idea if different releases of Steam keep this file in different locations, I didn't go too deep into it.

**Comment by kleshas** [comment]
> * Go to `your steam library/steamapps/compatdata` and delete the folder 489830 (I'm assuming you're talking about SkyrimSE, if not you'll need to look at the appid for the game [here](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/gamesinfo))
> 
> * Run the game on Steam again. You'll have a clean prefix once it finishes first time setup
> 
> * Re-run the installer

Crashed.  Checking file integrity did nothing.  Had to delete the skryimlauncher.exe and rename _skyrimlauncher.exe, removing the leading _.  
Ran the installer - no errors.  Ran Skyrim from steam - again, quick window flash, and ctd.

**Comment by rockerbacon** [comment]
@kleshas maybe you used the [launch options trick](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/85#issuecomment-647038183) at some point? On Steam: right click Skyrim > properties and check if you have any launch options set.

**Comment by rockerbacon** [comment]
Pre-release [4.1.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.1.0) is out, adding nexus downloads integration.

Unless someone finds any new issues, this should be the last pre-release and the code will be merged tomorrow for a stable release.

**Comment by Karce** [comment]
I just tested the 4.1.0 release and the nxm links now work too, like you said. I changed browser settings to open nxm links with modorganizer2-nxm-broker.sh, which I found in ~/.local/share/modorganizer2, if anyone else is wondering.

**Comment by kleshas** [comment]
> @kleshas maybe you used the [launch options trick](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/85#issuecomment-647038183) at some point? On Steam: right click Skyrim > properties and check if you have any launch options set.

None were set.
I've reset my whole skyrim setup.  Deleted everything, started from scratch.  Currently using the 3.1.0 install, which works great for me (nexus integration etc), apart from the high CPU usage when moving and enabling mods (main, wineserve and tabtip.exe pegging a CPU thread)

**Comment by rockerbacon** [comment]
Stable release [4.1.1](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.1.1) is up.
Thanks everyone for helping with the tests!
