### ISSUE TITLE
PULSE_LATENCY_MSEC issues in pipewire

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#273]
Oddly, sound was borked in SSE.  I fixed by removing -e 'PULSE_LATENCY_MSEC=90' in run.sh.  Running pipewire.

_Originally posted by @kleshas in https://github.com/rockerbacon/modorganizer2-linux-installer/issues/270#issuecomment-1006066107_

**Comment by rockerbacon** [comment]
Some people have reported this environment variable reducing audio crackling in both Skyrim SE and Fallout 4, although it never fully solved the problem.

It is possible to detect if the system is using pipewire or pulseaudio and set the option accordingly but I'd prefer to just remove it altogether. I've had no crackling issues since moving to pipewire, the entirety of the Linux community seems eager to move to it and I could never attest this envvar having any noticeable effect in the first place.

**Comment by jthistle** [comment]
Weird - shouldn't this have no effect if pipewire is running?

**Comment by rockerbacon** [comment]
> Weird - shouldn't this have no effect if pipewire is running?

Would be my guess as well. Personaly, I've had no problems with it.

**Comment by rockerbacon** [comment]
This envvar is not used in the latest version
