### ISSUE TITLE
Updating to Proton 6.3

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#275]
## It just works!
I managed to get Proton 6.3 "working" fine and it was far easier than I had anticipated. It seems that UVFS not working on newer versions was not only an issue on Wine's side but also on MO2's side, probably related to [issues introduced after Windows updates](https://github.com/ModOrganizer2/modorganizer/issues/1410).

MO2 2.4.4 can successfuly load mods when running inside Proton 6.3 and it also requires no extra Winetricks to get going.

## The catch
Ever since Proton 5.13, Steam has introduced the new Soldier runtime which breaks a big part of this project.

### How MO2 is executed

You may have noticed that MO2 is executed from outside Steam. This was done with a little bit of reverse engineering of the Steam Client and some peeks at the Proton source code.

[proton-launcher.sh](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/launchers/proton-launcher.sh) is a script which tries to reproduce what the Steam Client does when executing a game using Proton 5.0, which is not much more than setting a combination of very specific environment variables. This script is installed in the user's home directory and reused by the `./run.sh` script of each MO2 instance.

Even if you use the launch options trick described in #85, MO2 will still run outside of the Steam environment.

### Why that was a bad idea

The Steam runtime changes require modifications to _proton-launcher.sh_ and I'm not even sure it is possible to get solid results with this alone. Just getting Proton 5.0 to work without issues took a lot of time, trial and error, and required many revisions until it was bug free.

In my testing, using the current launch method with Proton 6.3, I couldn't move my character meaning I could barely test anything. I'd expect more extensive testing to show more issues and for the game experience to be heavily inconsistent across different systems (the issue the new runtime attempts to improve on).

### A better idea

Just get MO2 running through Steam, without any external stuff.

It is possible to straight up add the MO2 executable as a Steam game and it'll work fine. Automating that could be a challenge, though. This would, at the very least, require parsing and changing the vdf file in `~/.steam/steam/userdata/<userid?>/config/shortcuts.vdf`, where Steam seems to store data on manually added executables and I'm not sure on how to identify the prefix for these shortcuts.

Another option is to try something similar to that old Windows trick for getting SKSE to run from within Steam: Just replace the game's executable with whatever you want to run. This one may be easier to pull off and warrants some tests but it may require polluting the game's directory with Mod Organizer files depending on how the test results go.

The final option is to just not automate anything at all. The project could turn into more of a guide where the work is divided between the user and the installer. This is my least favorite because it breaks the initial premise of the project: click install and forget about the rest.

What I really want right now is to get some ideas flowing, be it new ideas or ideas expanding on some of what I've written above.
I'd also really appreciate people's reports on things they might have been doing with different Proton versions as that may provide some insights as well.

**Comment by TheDrifter363** [comment]
Hey thanks so much for posting this! I actually was going to post a bug or feature request about your usage of Proton 5.0. There's this mod for New Vegas, a heap replacer. They provide a d3dx9_38.dll which doesn't work under 5.0. Even if you override it in winecfg, which your script does anyway. The heap replacer works fine under 6.3, so there's that. I'm not sure how to get it working in 5.0, but I guess I can wait until your 6.3 release checks out. Thanks for all the hard work! I just found out about your script, so I'm eager to see how it all works out.

**Comment by rockerbacon** [comment]
Pre-release [4.0.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.0.0) is out.

Just missing:
- More extensive testing
- Readme for the steam-redirector with compilation instructions
- Nexus downloads integration. I'm still clueless on how to get this working

**Comment by aksratamo** [comment]
I was just about to test it but sorry it says "ERROR: redirector binaries not found"
I guess its what you mentioned missing in readme.
could you give small rundown what i need to do?

im running popos 20.04lts and did not find the packages mingw64-gcc and mingw64-winpthreads-static

**Comment by rockerbacon** [comment]
@aksratamo make sure you've downloaded the file `release.tar.gz` from the [release page](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.0.0) as it contains pre-compiled binaries.

If you want to install from source, you'll need to install the specific MinGW packages for your distribution and compile the redirector yourself.

**Comment by aksratamo** [comment]
thanks i managed to get it to work.
But the skse says that its too old. there is a newer one when i checked out. can i just repelace the old files?
are the other errors something talking about dpiscaling to be concerened about?

![Screenshot from 2022-01-08 11-36-07](https://user-images.githubusercontent.com/5618026/148639438-2ee8daa2-161d-43dc-a5b9-eb1325094c87.png)

**Comment by rockerbacon** [comment]
@aksratamo SKS64 has been updated in [4.1.0](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.1.0). 

Yes, there is no need to wait for an installer update as far as SKSE64 is concerned. You can just download the newer one and install manually.

There will be a bunch of errors and warnings in the MO2 logs, that's expected. As far as I can tell, none of the errors relate to major issues and the only way to make them go away is pushing fixes to Wine itself.

**Comment by aksratamo** [comment]
do i run the new ./install?
from the commands it says that it installed the ne skse but MO2 still says the old one is installed.

```
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/ryzen/.steam/debian-installation'
INFO: steam not found in '/home/ryzen/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/ryzen/.steam/debian-installation'
INFO: selected install directory '/home/ryzen/Games/mod-organizer-2-skyrimspecialedition'
INFO: removing existing JDK installation in '/home/ryzen/.steam/debian-installation/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing JDK in '/home/ryzen/.steam/debian-installation/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/ryzen/Games/mod-organizer-2-skyrimspecialedition/modorganizer2'
INFO: installing script extender in '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/Data' into '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_1_6_353.dll' into '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_loader.exe' into '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_steam_loader.dll' into '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition'
INFO: installing nxm link broker in '/home/ryzen/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/ryzen/.local/share/applications/'
INFO: applying protontricks xaudio2_7=native
Executing mkdir -p /home/ryzen/.steam/debian-installation/steamapps/compatdata/489830
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: 7ec9c3e9140e592ef575140417f27e75e16ccebfeee9816cdbab21aa3d5c0841 with wine-6.3 and WINEARCH=win64
Using native override for following DLLs: xaudio2_7
Executing /home/ryzen/.cache/protontricks/proton/Proton 6.3/bin/wine regedit /S C:\windows\Temp\_native\override-dll.reg
pressure-vessel-adverb[295643]: W: Unable to generate locales: Child process exited with code 1
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Executing /home/ryzen/.cache/protontricks/proton/Proton 6.3/bin/wine64 regedit /S C:\windows\Temp\_native\override-dll.reg
pressure-vessel-adverb[295868]: W: Unable to generate locales: Child process exited with code 1
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
INFO: configuring mo2 executable path 'Z:\home\ryzen\Games\mod-organizer-2-skyrimspecialedition\modorganizer2\ModOrganizer.exe' in '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition/modorganizer2/instance_path.txt'
INFO: configuring mo2 nxm handler path 'Z:\home\ryzen\Games\mod-organizer-2-skyrimspecialedition\modorganizer2\nxmhandler.exe' in '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition/modorganizer2/instance_download_path.txt'
INFO: setting up redirector in '/home/ryzen/.steam/debian-installation/steamapps/common/Skyrim Special Edition/SkyrimSELauncher.exe'
INFO: installation completed successfully
```

**Comment by aksratamo** [comment]
Hi, I dont know if this is the right place. but you asked help and i help experimenting :)
everything works nicely. but after moving from proton 6.18GE to the official 6.3 i hear a lot of carckling sound distortion.
I think I will try to go back to the GE proton tommorow

And i did not find out how to get nemesis and enbs to work.
those what need to be launched from MO2 with custom exe like nemesis dont start up https://www.youtube-nocookie.com/embed/1aIAiq9yigU

**Comment by rockerbacon** [comment]
@aksratamo please do report back if GE works fine on your end.

The audio crackling is a known issue with both Skyrim SE and Fallout 4. The only confirmed fix I know of is compiling faudio with ffmpeg yourself and replacing the provided Steam libraries, which is quite advanced. I can tell you I had no crackling issues ever since moving from a distro using pulseaudio to a distro using pipewire but I haven't played too much and also don't have any other user reports to confirm it is a viable solution.

Last I checked ENBs for Skyrim SE are mostly broken. According to the maintainers of DXVK, the shaders generated by ENB are a mess and the fact they even work on Windows is a miracle. Because of that they refuse to invest time adding weird code to their own project to try and get them to work. You can find some ENB related issues on the [DXVK project](https://github.com/doitsujin/dxvk/issues/) itself, there is some useful information on specific versions and workarounds there.

I've been playing Skyrim LE because there were no issues with ENB when I built my loadorder. I get a pretty stable experience with Wine and DXVK memory patches for 32bit applications and that was the sole benefit in SE for me, personaly.

In regards to nemesis, I never tried it so I can't provide much help.

**Comment by aksratamo** [comment]
Hi,
I did not get the GE version to work. It will not launch mod organizer with those.
also no Luck with nemesis

But now every time i turn on steam it will verify my skyrim file integrety and download 800mb of stuff. nothing changes and MO2 and mods work fine. but it kind of annoying. Nice to have working mods tho :D
