### ISSUE TITLE
add support for alternative install path

### ISSUE THREAD

**Issue by LithRakoon** [rockerbacon/modorganizer2-linux-installer#278]
Right now the installer only supports the default steam game path, but i have most of my games installed on a second drive which doesnt work with the installer.
my install path: /media/[drive name]/steamlibrary

so my request in short is:
add support for alternative installed game path.

**Comment by rockerbacon** [comment]
The installer should automatically detect where the game is installed and use that as the path.

If you moved the game between different libraries, you may have run into a bug in the current detection method: Steam doesn't do an awesome job at cleaning up the files in the old library and that may lead the installer into believing the game is still in the old location. There was an issue for this already but I couldn't find it.
If that is your case, you'll need to go to the library where the game was previously and navigate to `steamapps/compatdata`. There you'll need to delete the folder whose name is the appid of the game. You can find all appids [here](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/gamesinfo).

**Comment by ConnorPivovarov** [comment]
Game install path detects automatically, but Proton is always expected to be at the default location. I also had some troubles during installation with this.

**Comment by LithRakoon** [comment]
i am gonna test it out youll hear back from me about the results

**Comment by LithRakoon** [comment]
after testing it does seem like it works

**Comment by michell-dev** [comment]
I couldn't install it on my secondary drive. Had to move my game to the default steam install for the mod to install successfully.
