### ISSUE TITLE
4.0.0 doesnt create a run.sh

### ISSUE THREAD

**Issue by LithRakoon** [rockerbacon/modorganizer2-linux-installer#279]
Just tried the 4.0.0 installer and i cant seem to find a run.sh file which was normally used to start Mo2, did it change?
or is this a bug

**Comment by rockerbacon** [comment]
Yes, you need to run the game on Steam and that should launch Mod Organizer 2. The reason why is described in details in #275.

**Comment by Neutrovertido** [comment]
I did open the game via Steam and that launches well... the game. So how do I launch MO2?

![imagen](https://user-images.githubusercontent.com/61665012/148660804-fba2f3a3-e2e4-4363-9b7f-4dde9f1108d6.png)
