### ISSUE TITLE
Launching game on Steam doesn't run MO2

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#281]
I did open the game via Steam and that launches well... the game. So how do I launch MO2?

![imagen](https://user-images.githubusercontent.com/61665012/148660804-fba2f3a3-e2e4-4363-9b7f-4dde9f1108d6.png)

_Originally posted by @Neutrovertido in https://github.com/rockerbacon/modorganizer2-linux-installer/issues/279#issuecomment-1008158700_

**Comment by rockerbacon** [comment]
@Neutrovertido could you give me the output for these commands?
```
ls -lh "$HOME/.local/share/Steam/steamapps/common/Skyrim Special Edition/SkyrimSELauncher.exe"
```
```
ls -lh "$HOME/.local/share/Steam/steamapps/common/Skyrim Special Edition/_SkyrimSELauncher.exe"
```
```
cat "$HOME/.local/share/Steam/steamapps/common/Skyrim Special Edition/modorganizer2/instance_path.txt"
```

**Comment by Neutrovertido** [comment]
I managed to fix it, I changed the proton version to the recommended one from the installer.
