### ISSUE TITLE
Fallout 4 - Update to latest 4.2.0 gives error message, sounds missing ingame

### ISSUE THREAD

**Issue by graygrotesque** [rockerbacon/modorganizer2-linux-installer#286]
Hello!

After updating from 2.8.6 to 4.2.0 I get this error message when I start MO2: https://paste.xinu.at/B3tTB0/

It starts however after I click "OK" and I can run the game. Ingame I noticed that I can hear ambient sound and gunshots, but I cant't hear conversations, footsteps, music or radios.

I think I followed all the steps from the update readme.

I noticed when I ran the installer that it missed winetricks as a dependency which wasn't the case in the 2.8.6.

I have made a backup so I guess I could copy it back and play it this way but I have notices the game running significantly smoother with the new version and proton 6.3. Would be nice to get it to work properly. :D

I'm using pipewire / wireplumber if that's important

Thanks for your work! (:

**Comment by KnightJeffrey** [comment]
This is not a problem with this program. Go to properties of the game on steam. Then general and type this in launch options: WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90 %command%

**Comment by graygrotesque** [comment]
Thanks for the reply! Unfortunately this launch option didn't help, it's still exactly as described

**Comment by KnightJeffrey** [comment]
okay then try WINEDLLOVERRIDES="xaudio2_7=n" PULSE_LATENCY_MSEC=90 %command%

**Comment by KnightJeffrey** [comment]
its the same but without the ,b

**Comment by graygrotesque** [comment]
sadly also no effect

**Comment by graygrotesque** [comment]
Okay, it was my fault. :D

I totally missed that I should run the game through steam now, instead of starting MO2 through lutris like before.

Everything works fine now as it should.


Sorry guys :sweat_smile:

**Comment by KnightJeffrey** [comment]
alright remember to close the issue
