### ISSUE TITLE
Game launches then just closes

### ISSUE THREAD

**Issue by KnightJeffrey** [rockerbacon/modorganizer2-linux-installer#288]
When launching the SKSE64 file from MO2 with mods the game pulls up a black screen and it says wait or force quit the application then the game closes automatically no matter what I do. This isn't a problem when launching without mods. I have all dependencies met yet the game just closes out.

**Comment by rockerbacon** [comment]
I would assume you use SkyUI. If you install just SkyUI, does everything work fine? If yes then you likely have a problematic mod or combination of mods in your load order - considering the game doesn't even get to the main menu, I'd assume the problematic mod is some SKSE plugin.

Also note that Skyrim SE ENBs are not properly supported by DXVK. If you're using one, try loading the game without an ENB.

**Comment by KnightJeffrey** [comment]
Works fine with enb and no other mods I'll check skyui

**Comment by KnightJeffrey** [comment]
SKYUI works must be another mod thank you
