### ISSUE TITLE
nxm broker not working after update from 2.8.6

### ISSUE THREAD

**Issue by graygrotesque** [rockerbacon/modorganizer2-linux-installer#297]
after updating from 2.8.6 to the latest official release 4.2.0 the nxm broker seems to have lost functionality. I just noticed it because I wanted to update a mod and already had everything installed before the update.
Is there something I can do? (:

**Comment by rockerbacon** [comment]
Make sure MO2 is properly connected to Nexus and that it is set to handle NXM links. You can check both in the MO2 settings.

**Comment by graygrotesque** [comment]
I tried that, but it didn't help. So I just backed up the config folder and completely reinstalled it. It didn't work the first time but when I did it again, restarted, copied the configs back, associated the links again it worked. Don't know what the problem was, but well.. :D

Thanks anyways!
