### ISSUE TITLE
Installer doesnt support Alternatives Mo2 install path

### ISSUE THREAD

**Issue by LithRakoon** [rockerbacon/modorganizer2-linux-installer#301]
I have tested on both Skyrim SE and morrowind and both when i gave the Mo2 installer a diffrent path it would not start, only with the default path it would start Mo2 and work perfectly
(4.2.0)

**Comment by rockerbacon** [comment]
Can't reproduce. You're most likely running into #285. You'll need manual workarounds to run MO2 outside directories allowed by the Steam Runtime Engine.

**Comment by LithRakoon** [comment]
oh yep #285 is exactly my issue
