### ISSUE TITLE
Crashes/Fails to open on 4.2.0

### ISSUE THREAD

**Issue by iamthehorker** [rockerbacon/modorganizer2-linux-installer#302]
Installing MO2 for Fallout 4 or New Vegas results in a crash when attempting to launch the game through Steam. This is my Proton crash log:

Unhandled exception: unimplemented function ntdll.dll.__wine_unix_spawnvp called in 64-bit code (0x000000007bc34538).
Register dump:
 rip:000000007bc34538 rsp:000000000033fad0 rbp:000000007b631228 eflags:00000202 (   - --  I   - - - )
 rax:0000000180000100 rbx:000000000033faf0 rcx:000000000033faf0 rdx:000000000041bbfa
 rsi:0000000000000001 rdi:00007fffffb90000  r8:000000000040ade7  r9:0000000000008f20 r10:0000000000440020
 r11:a55a5aa5a55a5aa5 r12:000000000000009c r13:00007fffffb90000 r14:000000000033fce0 r15:00007fffffb90000
Stack dump:
0x000000000033fad0:  000000000033faf0 00007fffffb90000
0x000000000033fae0:  000000007bc0d474 000000007bc52e99
0x000000000033faf0:  0000000180000100 0000000000000000
0x000000000033fb00:  000000007bc34538 0000000000000002
0x000000000033fb10:  000000000041c080 000000000041bbfa
0x000000000033fb20:  000000000033fce0 00007fffffb90000
0x000000000033fb30:  000000007bc0bb14 0000000000000033
0x000000000033fb40:  0000000000000202 000000000000007f
0x000000000033fb50:  0000000000000000 0000000000000000
0x000000000033fb60:  000000007bc0bb14 0000000000000011
0x000000000033fb70:  0000000000000001 00007fffffb90000
0x000000000033fb80:  000000000000009c 00007fffffb90000
Backtrace:
=>0 0x000000007bc34538 EntryPoint+0xffffffffffffffff() in ntdll (0x000000007b631228)
  1 0x000000000040ade7 EntryPoint+0xffffffffffffffff() in winemenubuilder (0x000000007b631228)
  2 0x000000000040ca33 in winemenubuilder (+0xca32) (0x0000000000000000)
  3 0x000000000040c975 in winemenubuilder (+0xc974) (0x0000000000000000)
  4 0x000000007b62c9a9 EntryPoint+0xffffffffffffffff() in kernel32 (0x0000000000000000)
  5 0x000000007bc5e5f3 EntryPoint+0xffffffffffffffff() in ntdll (0x0000000000000000)
0x000000007bc34538 EntryPoint+0xffffffffffffffff in ntdll: jmp	0x000000007bc34530 EntryPoint+0xffffffffffffffff
Modules:
Module	Address					Debug info	Name (23 modules)
PE	          400000-          41d000	Export          winemenubuilder
PE	        7b000000-        7b0d7000	Deferred        kernelbase
PE	        7b600000-        7b812000	Export          kernel32
PE	        7bc00000-        7bc9e000	Export          ntdll
PE	       1c8db0000-       1c8e3d000	Deferred        msvcrt
PE	       21a7e0000-       21a855000	Deferred        setupapi
PE	       228450000-       22847a000	Deferred        propsys
PE	       231ae0000-       231b62000	Deferred        rpcrt4
PE	       23d820000-       23da47000	Deferred        user32
PE	       26b4c0000-       26b642000	Deferred        gdi32
PE	       2739c0000-       273af6000	Deferred        oleaut32
PE	       2e3540000-       2e3591000	Deferred        shlwapi
PE	       2e8f10000-       2e9028000	Deferred        ole32
PE	       2f1fa0000-       2f1fad000	Deferred        version
PE	       3126f0000-       312709000	Deferred        shcore
PE	       327020000-       327072000	Deferred        combase
PE	       32a700000-       32a729000	Deferred        sechost
PE	       330260000-       33029f000	Deferred        advapi32
PE	       361860000-       36191b000	Deferred        windowscodecs
PE	       3af670000-       3af728000	Deferred        ucrtbase
PE	       3afd00000-       3afd1a000	Deferred        imm32
PE	    7fd332f20000-    7fd332f24000	Deferred        winex11
PE	    7fd333380000-    7fd333c57000	Deferred        shell32
Threads:
process  tid      prio (all id:s are in hex)
00000020 steam.exe
	00000024    0
	0000010c    0
00000030 (D) C:\windows\system32\winemenubuilder.exe
	00000034    0 <==
	00000110    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000050    0
	0000005c    0
	0000006c    0
	00000078    0
	000000a8    0
	000000ac    0
	000000c4    0
	000000e0    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	00000060    0
00000064 winedevice.exe
	00000068    0
	00000070    0
	00000074    0
	0000007c    0
	00000088    0
	0000008c    0
	00000090    0
00000080 explorer.exe
	00000084    0
	0000009c    0
	000000a0    0
00000094 plugplay.exe
	00000098    0
	000000b0    0
	000000b4    0
	000000b8    0
000000bc svchost.exe
	000000c0    0
	000000c8    0
	000000cc    0
000000d0 tabtip.exe
	000000d4    0
	000000fc    0
	00000100    0
000000d8 rpcss.exe
	000000dc    0
	000000e4    0
	000000e8    0
	000000ec    0
	000000f0    0
	000000f4    0
	000000f8    0
System information:
    Wine build: wine-6.3
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.16.0-1-default

**Comment by rockerbacon** [comment]
See if purging your existing prefix and creating a new one changes anything. You can find instructions for it [here](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md#using-alternative-proton-versions) under "Using alternative proton versions"
