### ISSUE TITLE
Can't use with Oblivion downloaded from 3rd party

### ISSUE THREAD

**Issue by BVCCAPIOH** [rockerbacon/modorganizer2-linux-installer#310]
I'd've gotten it from steam if they sold the game in Russian to Americans, but alas! I had to get it elsewhere, since the reason I've been wanting to play RPGs is to learn languages. It did not come with a steam ID and Steam treats it as a 3rd party game. Trying to set up Mod Organizer gave me this error:

 ERROR: could not find any Steam library containing a game with appid '22330'. If you known exactly where the library is, you can specify it using the environment variable STEAM_LIBRARY

Is there a way to work around this? I moved the game to my Steam library folder, but the error persists, and I can't really find in my other games anywhere you'd find an "AppID"

Thanks

**Comment by rockerbacon** [comment]
Games acquired outside of Steam are not officially supported. How are you launching the base game?
