### ISSUE TITLE
Steam flatpak version not working (everything on one drive)

### ISSUE THREAD

**Issue by Elinvynia** [rockerbacon/modorganizer2-linux-installer#312]
A small black window opens and immediately closes, nothing else happens. 

During installation, for the first time, it says it was cancelled after a weird message ("protontricks is now running in the background"). The second time works without any errors.

System: Fedora 35, AMD, wayland, Steam flatpak, flatpak protontricks, proton 6.3

Steam log: https://pastebin.com/0HzK7Sde

Installation log: https://pastebin.com/1iem64Vs

**Comment by geext-dk** [comment]
I've encountered the same issue. I've managed to fix it by giving the Steam flatpak access to the mod organizer directory. I guess it should be documented somewhere?
```
flatpak override --user --filesystem=<path-to-mo2> com.valvesoftware.Steam
```

**Comment by rockerbacon** [comment]
All install location related issues are now grouped in #656
