### ISSUE TITLE
Out of Memory in xEdit

### ISSUE THREAD

**Issue by Osced86** [rockerbacon/modorganizer2-linux-installer#323]
After upgrading from the older lutrix variant to the latest I've noted problems with using xEdit, I now can't load all my previous plugins without getting out of memory in the normal xEdit variant. I've also noted that some of the scripts for xEdit also gets out of memory. 

I can load all plugins in the 64 bit variant but xedit crashes with runtime error 216 when trying to open menu for running script and if you do something that in the 32 bit versions gives you a dialouge option.

I'm on Ubuntu 20.04 with latest wine staging 7.5 and 16 gb RAM.

**Comment by Andreiva13** [comment]
Anyone found a fix for this?

**Comment by Osced86** [comment]
I've got it to work when updated to latest beta xEdit.

**Comment by Andreiva13** [comment]
Which version in particular? Trying the 4.1.4 Extremely Experimental yielded the same result

**Comment by Osced86** [comment]
For me the 4.1.4 Extremely Experimental works, unsure why it don't work for you.

**Comment by alekulyn** [comment]
This bug is by no means resolved. I run out of memory on xEdit32, but I get a "runtime error 216" when trying to launch xEdit64 on v4.1.5f . I don't even get to load plugins screen. According to xedit discord, this is some sort of access violation.
