### ISSUE TITLE
Installer cannot find Skyrim Special Edition 

### ISSUE THREAD

**Issue by LunarPidgeon** [rockerbacon/modorganizer2-linux-installer#325]
installer version: 4.3.0 (latest at time of writing)
installer works properly until it attempts to find Skyrim, then gives the error "Could not find 'Skyrim Special Edition' in any of your Steam libraries. Make sure the game is installed and that you've run it at least once"
console output:
`> sudo ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: steam not found in ''
INFO: steam not found in '/root/.var/app/com.valvesoftware.Steam/.local/share/Steam'
ERROR: could not find any Steam library containing a game with appid '489830'. If you known exactly where the library is, you can specify it using the environment variable STEAM_LIBRARY
`
none of the older closed issues provided a fix, since this is a much more recent version.
OS: linux mint 20.3, kde plasma 5.18.8, 64-bit, kernel 5.4.0-107-generic
proton 6.3-8 used to attempt install, did not work

Im not sure what the error means when it says to specify the library with environment variables.

update: i attempted to fix the issue by changing the environment variable in terminal settings to "STEAM_LIBRARY=[path to steam library]", along with the path directly to the skyrim folder and various other paths around there, none of which fixed the issue.

tried in both zsh and bash, neither seemed to work.

update: with help from a friend, i set the environment variable to STEAM_LIBRARY='/home/USER/.steam/debian-installation', but now its saying permission denied in the console and closing.

update: i made the directory manually and set its permissions to rw for all, and the installer progressed further before failing to make another directory. i am going to continue making the directories it fails to, and seeing how far i get.

Update: now its freezing saying it cant find the session bus when i run as root, and this when i run as nonroot:
`cp: cannot stat '/home/USER/.steam/debian-installation/steamapps/compatdata/489830/steamapps/common/Skyrim Special Edition/Data/Scripts': Permission denied
cp: preserving times for '/home/USER/.steam/debian-installation/steamapps/compatdata/489830/steamapps/common/Skyrim Special Edition/Data': Operation not permitted`

update: am now getting this error:
`error: Unable to allocate instance id`

**Comment by LunarPidgeon** [comment]
update: i attempted to fix the issue by changing the environment variable in terminal settings to "STEAM_LIBRARY=[path to steam library]", along with the path directly to the skyrim folder and various other paths around there, none of which fixed the issue.

tried in both zsh and bash, neither seemed to work.

**Comment by LunarPidgeon** [comment]
update: with help from a friend, i set the environment variable to STEAM_LIBRARY='/home/USER/.steam/debian-installation', but now its saying permission denied in the console and closing.

**Comment by LunarPidgeon** [comment]
while trying to fix with aforementioned friend, i noticed that the terminal really doesnt like "skyrim special edition" unless the whole path is in quotes. maybe the install script isnt accounting for that?

**Comment by adolfgatonegro** [comment]
The problem seems to be that you're running the script using `sudo`, which means the installer looks for a Steam installation in the root user directory, not your regular home directory.

Try removing the directories you created manually, and running the script without elevated privileges, just using `./install.sh`.
