### ISSUE TITLE
Clicking [Install a new mod from an archive] freezes MO2

### ISSUE THREAD

**Issue by Peremious** [rockerbacon/modorganizer2-linux-installer#340]
Mod Organizer 2 freezes when clicking the option [Install a new mod from an archive]. I have to kill MO2 through steam and relaunch it in order to make MO2 interactive again. (New note: Alt+F4 closes the opened window and allows MO2 to be interactive again)

I have tried running the install script again to possibly fix it, but that did nothing. The install script finished correctly (according to the script itself)

I also tried entirely deleting the MO2 folder and reinstalling, it still does it.

MO2 used to work just fine on my setup, I'm not sure what happened. I haven't changed anything aside from adding mods to the game, but none that directly or indirectly interfere with MO2. I have added tools to MO2, but doing the fresh install got rid of those and it still does it, so that's not the problem.

I am on Manjaro KDE Plasma 5.24.5
I am using Proton 6.3-8 (as per the instructions)

**Comment by picobyte** [comment]
I don't have this issue. the button or Ctrl+M works fine for me, but then I have not followed this guide, I run MO2 in proton experimental, which seems to work, except for a gradual slowdown of MO2 after installing ~15 mods.

Thie button should give you an open file dialogue. Maybe the path you try to start is incorrectly set? Do you have a working dir set, in for your mod organizer? Is mod organizer settings->pahs set up right? Also try the buttons there, if that crashes, then maybe it's something wine related, causing any open file dialogue to fail.

**Comment by Peremious** [comment]
Everything is left as default in the installation for this from the latest script install of MO2 through Steam. I have no idea what you are talking about. Everything will be the default.
