### ISSUE TITLE
Is there any plans to make it proton 7.0 (or newer) compatible

### ISSUE THREAD

**Issue by jjxvi** [rockerbacon/modorganizer2-linux-installer#341]
Hello I'm having trouble running Skyrim SE with Proton 6.3 as sounds seems to be bugging but with Proton 7.0 and Experimental the game seems to be working just fine. Is the development of this installer at it's end or is there plans for new release any time in the future to make it perhaps Proton 7.0 compatible?

Also, I would appreciate any tips for making sound work on proton 6.3 so far only one's I've tried seem to have only made it worse.

**Comment by jake770321** [comment]
You can try modifying the script to use a newer proton version but if not, you can try a tool called steamtinkerlaunch.

**Comment by gibsonjareds** [comment]
I’ve been using it successfully on Proton 7.0 for a while now. No sound issues or anything. I install it, boot it up using the latest version of proton, then close it out and use the provided installer. I’m not using Lutris as I find it easy enough to just boot via the steam client, auto-updates be damned
