### ISSUE TITLE
Vortex mod manager 2 lutris errors after following instructions

### ISSUE THREAD

**Issue by WilliamBehrens** [rockerbacon/modorganizer2-linux-installer#344]
I used this lutris installer https://lutris.net/games/vortex-mod-manager/ (that links back to this repo) after installing and disabling automatic updates running the application gets me this in the lutris logs:
```
Started initial process 107566 from /home/will/.local/share/lutris/runners/wine/lutris-6.14-4-x86_64/bin/wine /home/will/Games/vortex-mod-manager/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe
Start monitoring process.
esync: up and running.

net.js:329
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:329:26)
    at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:67:18)
    at process.getStdout [as stdout] (internal/bootstrap/switches/is_main_thread.js:122:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:793)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
```

**Comment by NicBOMB** [comment]
> I used this lutris installer https://lutris.net/games/vortex-mod-manager/ (that links back to this repo) after installing and disabling automatic updates running the application gets me this in the lutris logs:

Try launching Vortex from the vortex-downloads-handler.desktop file provided from that installer. It should be located at `/home/yourhomedirectory/.local/share/applications/vortex-downloads-handler.desktop`. You can also try downloading a mod with the nxm protocol (Mod Manager Download button) and select Vortex (should be automatically detected) or browse for the `vortex-downloads-handler.desktop` file (manual app selection). That should launch the lutris wine prefix for you and download the mod.
If all of the above doesn't work try [my updated version of the lutris installer in #257](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/257#issuecomment-1149458081).
