### ISSUE TITLE
Getting ENB working on SkyrimSE

### ISSUE THREAD

**Issue by gibsonjareds** [rockerbacon/modorganizer2-linux-installer#345]
### Machine:

GPU: ASRock Phantom Gaming D Radeon RX 6500 XT 4GB GDDR6
CPU: Intel Core i7-10700
RAM: 32GB DDR4-3000
distro/kernel: Arch Linux/ 5.17.9-xanmod1-1
DE: KDE Plasma (x11)

### What works: 
It seems most things from the Rudy ENB preset for Obsidian Weathers works. I've never tested on Windows and don't have a working install to get it working on. If I have nothing else running I can get ~50fps easily in exteriors with ~60 at in for interiors at 1080p with a modlist of 181.

### What doesn't work:
The in-game GUI. I can open it before the title screen, but the title screen captures my mouse. I also wouldn't really consider it working if I can't tweak settings in-game.

### What I did to get it working:
- Follow instructions to install SSE w/ MO2
- Follow instructions to switch to Proton 7.0
- Use `protontricks-launch` to launch BethINI and set the recommended tweaks, as well as the BethINI preset for "High"
- Disable TAA In the INI and make other tweaks suggested by RudyENB
- Install ENB
- Install preset and its dependencies
- Install d3dcompiler_42,43,46,47 (maybe only 46 is necessary)
- Add native override for said d3d libraries
- Download the DXVK d3d11.dll from the official repo
- Rename it to d3d11_dxvk.dll
- Set the following in the enblocal.ini:
```
[PROXY]
EnableProxyLibrary=true
InitProxyFunctions=true
ProxyLibray=d3d11_dxvk.dll

[PERFORMANCE]
SpeedHack=true
ShaderCache=true
UsePatchSpeedhackWithoutGraphics=true
```
I also disabled DoF in the enbseries.ini for personal taste but that may have an impact.

I don't know if this will help anyone with getting it fully working. I may have forgotten a step or two, but this should _hopefully_ get you in the ballpark of getting it working.

**Comment by picobyte** [comment]
Not tested by me, but in case it helps, the enb archive contains these instructions in enbseries/LinuxVersion/readme.txt
```
TES Skyrim SE with ENBSeries running on "current" versions of WINE with DXVK:
As there can be many different hardware configurations, and even more software configurations, and I expect many of these combinations will work with a somewhat common set of >

In general, so long as you have the right versions of these applications installed, things should work basically the same as they do on Windows.

TES Skyrim SE version: 1.5.97.0.8
WINE version: lutris-6.4-x86_64 (also tested on Proton-6.5-GE-1)
Winetricks: d3dx11_43, d3dcompiler_43, d3dcompiler_47 (specific version of d3dcompiler likely doesn't matter)
DXVK version: v1.7.3L-03f11ba
Vulkan Instance Version: 1.2.141
Lutris version: 0.5.8.3
OS: Kubuntu 20.10
Video Card: NVidia GeForce GTX 980
ENBSeries Presets tested: Cathedral Minimalist ENB https://www.nexusmods.com/skyrimspecial ... mods/31367
Mods: This worked with no mods enabled, and 50 mods installed, so it seems pretty robust.
More than likely the major version of WINE and DXVK version range are the most critical here. I expect that any WINE 6.x version will work, and probably any DXVK that was buil>
While I tested this via Lutris, I don't think it is needed at all. You can likely run straight from Steam for Linux with a version of Proton that uses DXVK. You should theoret>

I find Lutris to be a nice way to run this, as it will handle installation of a lot of the components for you, such as WINE, and DXVK, and has installers for Skyrim for Steam:
https://lutris.net/games/the-elder-scrolls-v-skyrim-special-edition/

Follow the instructions from your ENBSeries preset on installation. Just be sure to use enbseries for TES Skyrim SE version 0.347 or (insert version name/number of the newer v>
```

**Comment by Zappleberry** [comment]
When you say get the d3d11.dll from the official repo, do you mean the ENB repo?

**Comment by fynzhak** [comment]
@Zappleberry , I'm assuming it's this official repo: https://github.com/doitsujin/dxvk
Be sure to use the 32-bit version of d3d11.dll.

@gibsonjareds , when you say the in game GUI does not work, is that the case before or after the steps in your section "What I did to get it working"?
I'm also unable to open the GUI in game, and that's still the case after following your advice. Just wondering if maybe there's something else I missed.

However, it seems that ENB does load, and you can configure the .ini before starting the game. :)

**Comment by rockerbacon** [comment]
I'll concentrate ENB discussions on #453
