### ISSUE TITLE
Cannot start organizer

### ISSUE THREAD

**Issue by daveedmee** [rockerbacon/modorganizer2-linux-installer#346]
When starting MO2 for the first time I created a new Instance for Skyrim SE, which brought the program to a crash.
When starting MO2 again I get this error:

The file 'Z:home\edgar-schluminski\.local\share\Steam\steamapps\common\Skyrim Special Edition\Organizer' does not exist.

Details read:
Error 2 ERROR_FILE_NOT_FOUND: Dateinichtgefunden. (0x2)
 . binary: 'Z:\home\edgar-schluminski\.local\share\Steam\steamapps\common\Skyrim Special Edition\Organizer'
 . owner: (file not found)
 . rights: (file not found)
 . arguments: '2\modorganizer2\ModOrganizer.exe'
 . cwd: 'Z:\home\edgar-schluminski\.local\share\Steam\steamapps\common\Skyrim Special Edition'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok
 
 
 Attached is a screenshot of the shell and the MO2 window with the error

![Screenshot_20220610_031759](https://user-images.githubusercontent.com/52132306/172971508-fa991189-dc8f-4405-a5d2-e7b5b763d344.png)
![Screenshot_20220610_031826](https://user-images.githubusercontent.com/52132306/172971510-ff3dbc67-fa6c-4265-9217-cd00618cd047.png)

**Comment by picobyte** [comment]
I think you forgot to doublequote your command, because you're passing arguments '2\modorganizer2\ModOrganizer.exe'
and I miss a backslash before '.local' in your exe and directory:
`Z:\home\edgar-schluminski.local\share\Steam\steamapps\common\Skyrim Special Edition`

**Comment by Wqery24** [comment]
Any Movement on this? I am having the same error with FONV.

**Comment by Daveedmee** [comment]
> I think you forgot to doublequote your command, because you're passing arguments '2\modorganizer2\ModOrganizer.exe' and I miss a backslash before '.local' in your exe and directory: `Z:\home\edgar-schluminski.local\share\Steam\steamapps\common\Skyrim Special Edition`

That was just a Copy/Paste error with the Backslash and the double quote didn't appear in the MO2 window that I attached as screenshot #2

**Comment by Daveedmee** [comment]
> Any Movement on this? I am having the same error with FONV.

I think my mistake was that I tried to install MO2 in a custom directory or a dirty Proton bottle. I had to delete and reinstall Skyrim Special Edition and left the installation directory untouched and it worked again.

I'm leaving the issue open since I was not the only one with this problem.

**Comment by rockerbacon** [comment]
Reopening due to new report

**Comment by rockerbacon** [comment]
Looks like a bug with Mod Organizer itself. If the reports are accurate, Mod Organizer is launched and then tries to launch itself again but is unable to handle spaces in the binary path.
Does the issue occur immediately after launching the game on Steam or is it triggered by some other action?

**Comment by riomccloud** [comment]
Happens here too, only when you change the Mod Organizer 2 default directory. This error happens after you create an instance. Then, if you close and start the game again, it immediately stops at this error.

**Comment by rockerbacon** [comment]
This looks to have the same cause as #387, that's recently been fixed. Closing for now.

**Comment by danaYatsuta** [comment]
Encountering this with Morrowind using 5.0.1. Tried removing prefix, creating a clean one and installing MO2 from scratch. I create a portable instance and leave all paths at default.

![Screenshot_20240518_012632](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/105816064/032b4d0a-7c3a-4230-a978-368545eccf3c)

**Comment by rockerbacon** [comment]
I'm grouping all install location related issues in #656, no further discussions here.
