### ISSUE TITLE
find-library-for-appid.sh echoes the compatdata directory if STEAM_LIBRARY exists

### ISSUE THREAD

**Issue by Spartan322** [rockerbacon/modorganizer2-linux-installer#349]
This results in a duplication of the middle part of the path which tends to cause mkdir commands to fail, ending the installation as a failure.

**Comment by firaenv** [comment]
could you provide more detail please?

**Comment by Lord-Guckavin** [comment]
If one sets $STEAM_LIBRARY to `/games/steam_library` then utils/find-library-for-appid.sh returns `/games/steam_library/steamapps/compatdata/$appid` which when the script tries to install a script extender you'll end up with something like `mkdir: cannot create directory ‘/games/steam_library/steamapps/compatdata/22330/steamapps/compatdata/22330/pfx/drive_c/java’: No such file or directory`

**Comment by rockerbacon** [comment]
Fixed in #324
