### ISSUE TITLE
Fallout NV: Enb not allowing game to launch.

### ISSUE THREAD

**Issue by firaenv** [rockerbacon/modorganizer2-linux-installer#350]
Game launches fine until I install the d3dl9 and enbhost.exe.  Then the game refuses to launch.

**Comment by picobyte** [comment]
I have run skyrim with ENB enabled, but not while my mod configuration was stable. I read somewhere that ENB wasn't working well in Linux, so I chose to disable it. The ENB archive for Skyrim does have a folder, though, where it mentions Linux installation, `enbseries/LinuxVersion/readme.txt`.

**Comment by firaenv** [comment]
Yeah they are highly unstable.  I got it to work though through constant tinkering.  Thank you for your input though!
