### ISSUE TITLE
Cannot install because Steam Deck does not include cabextract

### ISSUE THREAD

**Issue by Schwedr** [rockerbacon/modorganizer2-linux-installer#354]
Currently I'm working on installing mod organizer 2 for my New Vegas installation and I get all the way to the end of the installation before I get these two error messages. Below as well is the guide I have been following as well as the entire code up until the point of failure. I'm still relatively new to linux as I just got into it because of the steam deck so any help would be much appreciated!

warning: Working around wine bug 24013 -- Native d3dcompiler_43 may cause some d3d10 apps to crash, see https://bugs.winehq.org/show_bug.cgi?id=24013

warning: Cannot find cabextract.  Please install it (e.g. 'sudo apt-get install cabextract' or 'sudo yum install cabextract').

This is the guide I have been following up until this point -> https://www.youtube.com/watch?v=x55SAwnONbQ

(deck@steamdeck Downloads)$ ./install.sh 
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: selected install directory '/home/deck/Games/mod-organizer-2-newvegas'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing existing JDK installation in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing JDK in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/deck/Games/mod-organizer-2-newvegas/modorganizer2'
INFO: installing script extender in '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: installing nxm link broker in '/home/deck/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/deck/.local/share/applications/'
INFO: applying protontricks d3dcompiler_43 d3dx9
SSL_INIT
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/22380
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 918989a44c3442e1eb84f38746253ab099fa36746468af95f28d089548fb53f2 with wine-6.3 and WINEARCH=win64
Executing w_do_call d3dcompiler_43
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/22380
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_d3dcompiler_43 
------------------------------------------------------
warning: Working around wine bug 24013 -- Native d3dcompiler_43 may cause some d3d10 apps to crash, see https://bugs.winehq.org/show_bug.cgi?id=24013
------------------------------------------------------
------------------------------------------------------
warning: Cannot find cabextract.  Please install it (e.g. 'sudo apt-get install cabextract' or 'sudo yum install cabextract').
------------------------------------------------------
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by peamy** [comment]
Hey I was trying to install ModOrganiser2 on my steam deck yesterday and ran into the exact same issue where it complained something about cabextract.
What solved it for me was to uninstall protontricks and reïnstall it through the flatpack installer. Then configure it afterwards. I was also able to run the protontricks gui after this, which didnt work before.
https://github.com/Matoking/protontricks#flatpak-recommended
https://github.com/flathub/com.github.Matoking.protontricks#configuration

After this ModOrganiser installation seemed to work for me.

**Comment by toqov** [comment]
I am having this same issue, but in my case it appears that the installer is trying to install files to .local/share/Steam/steamapps, while my vegas install is located on the SD card at /run/media/mmcblk0p1/steamapps

**Comment by rockerbacon** [comment]
`cabextract` is required for MO2 installation and the Steam Deck does not provide it by default.
