### ISSUE TITLE
MO2/Skyrim SE - "Failed to start download:" error when using Nexus in a browser to choose mods

### ISSUE THREAD

**Issue by outsidefactor** [rockerbacon/modorganizer2-linux-installer#355]
Thanks in advance for taking the time to read this.

I installed MO2 using Installer 4.3.0 about two weeks ago, setting up for Skyrim SE. I am running Manjaro Linux.

All went well for a few days, letting me get a good set of mods installed and running. I played happily for a week, and went back to install a new mod and I got an error "Failed to start download:" when I tried to install directly from the Nexus. I was able to download the mod and manually install it, so I moved on.

But it never works any more. I have tried a bunch of mods and none download. I have tried both Google Chrome and Firefox. The link gets sent from the browser, but MO2 "Failed to start download:".

Any suggestions about how to progress this? I had thought it might just get fixed when some library was updated, but it's been a couple of weeks now. Anyone else having this issue? Nothing about the error shows up in the MO2 log window pane.

**Comment by outsidefactor** [comment]
I found this thread:

https://bytemeta.vip/repo/rockerbacon/modorganizer2-linux-installer/issues/317

Which points to:

https://github.com/Matoking/protontricks/issues/146

The easy fix was to install protontricks-git from the AUR (I am on Manjaro).

**Comment by SegoItCh** [comment]
I'm getting it with Ubuntu and updated protontricks

**Comment by rockerbacon** [comment]
Duplicate of #317
