### ISSUE TITLE
Can't install winetricks

### ISSUE THREAD

**Issue by SpaceWolf727** [rockerbacon/modorganizer2-linux-installer#356]
Installer gets stuck when trying to download winetricks, it seems like it isn't connecting to whatever server the file is hosted on. Any ideas?

**Comment by firaenv** [comment]
wdym winetricks? I don't think it's suppose to install that.

**Comment by SpaceWolf727** [comment]
Found a solution: waiting. For some reason the installer just gets stuck
for a minute on it.

**Comment by YO-SC** [comment]
yep, this is it
