### ISSUE TITLE
NXM links not working

### ISSUE THREAD

**Issue by FerenczHollander** [rockerbacon/modorganizer2-linux-installer#358]
I have installed MO2 on my Steam Deck. When I click an NXM link on nexusmods.com it says I need to select an application to open x-scheme-handler/nxm. What can I do to get these links to work?

**Comment by firaenv** [comment]
What type of DE are you using?

**Comment by MaggiWuerze** [comment]
Late to the party here, but I have the same issue on my Deck, what do you mean with DE @ArcheMcDonnell ?
