### ISSUE TITLE
Error "redirector binaries not found" after attempting to run install script

### ISSUE THREAD

**Issue by AbrafoJ** [rockerbacon/modorganizer2-linux-installer#361]
Hi all,

Attempting to go through the installation steps [https://www.youtube.com/watch?v=x55SAwnONbQ](url)

After enterting in `./install.sh ` I get:

`deck@steamdeck Downloads)$ ./modorganizer2-linux-installer-master/install.sh 
ERROR: redirector binaries not found`

I've run through the steps a few times and continue to run into this issue. One person in the comments on the youtube video is also experiencing this problem but no solution was posted. I'd love some help with this.

Cheers,

-AbrafoJ

**Comment by TannerBluhm** [comment]
Came here with the exact same problem :sweat_smile:

**Comment by LennyMcLennington** [comment]
You downloaded the source code instead of the latest release build which it tells you to download in that video and in the repo's README.md https://github.com/rockerbacon/modorganizer2-linux-installer#installation-steps

**Comment by rockerbacon** [comment]
Pre-compiled binaries are available in the tarball downloaded from the releases page.

If you're downloading the source, you'll have to either compile the binaries yourself or get them from somewhere else. Compilation instructions are available in the [steam-redirector's readme](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/steam-redirector)
