### ISSUE TITLE
Skyrim Together Reborn Support

### ISSUE THREAD

**Issue by GamzeeRakoon** [rockerbacon/modorganizer2-linux-installer#362]
Using MO2 to launch Skyrim together reborn does not work as it will give the the error
![image](https://user-images.githubusercontent.com/41258148/178985167-72b2c41d-5265-4f61-80ee-cb618f830c53.png)

To install Skyrim Together Reborn i followed the official guide
https://wiki.tiltedphoques.com/tilted-online/guides/client-setup/skyrim-together-reborn

I have tested and launched it straight via steam and that worked so this is an issue only in MO2 Linux

errors i see in the terminal when launcher STR are:
``EnableNonClientDpiScaling() failed for HWND 0x3011a (120) (Call not implemented.)``
``[2022-07-14 12:45:24.058 W] [creationgameplugins.cpp:133] Z:/home/niki/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/profiles/Skyrim Together Reborn/plugins.txt empty``

**Comment by Baguettedood** [comment]
I was able to get past the "Fatal Minhook error" by changing my prefix's "Windows verison" to Windows 10. Not sure if this works for everyone, however.

Unfortunately I later ended up with a "failed to find dll:  bink2w64.dll" error when running through Mod Organizer, as shown:
![Screenshot_20220717_144542](https://user-images.githubusercontent.com/6375753/179384311-6b5e7789-4a5e-4dbc-a9d0-f9e1e9522de0.png)

Running SkyrimTogether.exe directly without Mod Organizer opens the game properly, with Skyrim Together working.

I ended up adding SkyrimTogether.exe as a non-steam game, setting its Proton version to be the same as SSE's, setting my launch options to `STEAM_COMPAT_DATA_PATH="/path/to/steamapps/compatdata/489830/" %command%`, and using [movfs4l.py](https://github.com/qsniyg/ksp_stuff) to load the Mod Organizer modlist instead.
