### ISSUE TITLE
[Skyrim Special Edition] Error after creating new portable instance

### ISSUE THREAD

**Issue by witheredwojak** [rockerbacon/modorganizer2-linux-installer#363]
Installing MO2 on fresh install of Skyrim Special Edition. This error appears after creating the new portable MO2 instance.

![1](https://user-images.githubusercontent.com/66310741/179352377-e914d212-cde0-4d99-b9e7-e7d5399e1404.png)

**Comment by cojeap** [comment]
You need to make some changes to the ModOrganiser.ini

There shouldn't be spaces in the path. This an MO2 quirk.  Similar, there should be no "."  in folder names.

Turn from this:
4\binary=Z:/home/USER/path/to/data/Skyrim Special Edition/etc/modorganizer2/explorer++/Explorer++.exe

to this:
4\binary=Z:/home/USER/path/to/data/SkyrimSE/etc/modorganizer2/explorer++/Explorer++.exe

**Comment by Smirnaff** [comment]
> You need to make some changes to the ModOrganiser.ini
> 
> There shouldn't be spaces in the path. This an MO2 quirk. Similar, there should be no "." in folder names.
> 
> Turn from this: 4\binary=Z:/home/USER/path/to/data/Skyrim Special Edition/etc/modorganizer2/explorer++/Explorer++.exe
> 
> to this: 4\binary=Z:/home/USER/path/to/data/SkyrimSE/etc/modorganizer2/explorer++/Explorer++.exe
> 
> I have found that regarding the folders with "." in name symlinks work fine.

Doesn't work for me. Should I rename the Skyrim folder as a whole? But that way it won't launch via Steam

**Comment by Metallumere** [comment]
I'd also like to report similar issues.
Seems like spaces in the Mod Organizer install directory breaks everything.
I get this error:
> 14:24:38.169 [E] failed to spawn "Z:\home\metall\\.steam\debian-installation\steamapps\common\Skyrim Special Edition\And" Things\Elder Scrolls\MO2 SkyrimSE\modorganizer2\ModOrganizer.exe

Probably because my MO2 install is located here:
> Z:/home/metall/Stuff And Things/Elder Scrolls/MO2 SkyrimSE/modorganizer2/explorer++/Explorer++.exe

And my game itself is installed here:
> Z:/home/metall/.steam/debian-installation/steamapps/common/Skyrim Special Edition

It's an easy enough fix, just install in a path with no spaces, but similar to #505 fixing Steam install paths, a similar fix should probably support spaces in portable MO2 install paths.

**Comment by rockerbacon** [comment]
All install location issues are now grouped in #656
