### ISSUE TITLE
Can't start launcher anymore

### ISSUE THREAD

**Issue by Watercrown** [rockerbacon/modorganizer2-linux-installer#364]
I was trying to tweak my game settings so I started mo2 and selected the launcher. It gives me an error that says "MO2 is already open." Only way to tweak my settings is with the .ini... which obviously is not ideal.

**Comment by ConvexTlc97** [comment]
Same issue here. Don't know a fix just yet for this

**Comment by ConvexTlc97** [comment]
NVM found the work around for this real quick. In MO2 you need to edit the Binary line to the old launcher EXE. The script for this changes it and renames the old one the same but with a _ before the text. just have to set the binary to _SkyrimSELauncher.exe then save and launch it and you will be able to edit the settings.

**Comment by rockerbacon** [comment]
This is covered in the post-install instructions linked in the README
