### ISSUE TITLE
MO2 slows down with some errors

### ISSUE THREAD

**Issue by Ozbourne** [rockerbacon/modorganizer2-linux-installer#368]
Hi,

I'm having some problems with the MO2 slowing down to a point where everything takes few second to register, couple of times had to restart the WM since everything locked up. I haven't had this problem with anything else so far.
I'm running Arch with bspwm, Proton 6.3-8 and gtx1070 if thats any help.

![mo2errors](https://user-images.githubusercontent.com/42701499/183223647-3a149d28-853b-4b4a-b886-64c21272d976.png)

**Comment by Neuromancer-94** [comment]
Same issue, would love to know if there's a fix.

**Comment by noughtmare** [comment]
Updating to proton 7 or experimental mostly fixed this for me. Follow [these instructions](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md#using-alternative-proton-versions) and do the optional step.

**Comment by ksladowski** [comment]
Same here. Steam deck

**Comment by mmatis** [comment]
Ditto over here on a fresh install and prefix of SSE. My old manual MO2 install in my old SSE prefix didn't have this lag. I think it might have to do with checking nexus. Seems to happen most after adding a mod and then stops until it has to get some info on a mod from Nexus.

**Comment by rockerbacon** [comment]
Closing as stale
