### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by Jlf0258** [rockerbacon/modorganizer2-linux-installer#373]
Can someone help me with these , trying to install mod2 on steam deck and i having issues... i am following the guide from youtube :https://www.youtube.com/watch?v=x55SAwnONbQ 

this is what i am getting , 

(zenity:19636): WARNING **: 09:23:41.902: AT-SPI: Could not obtain desktop path or name

** (zenity:19636): WARNING **: 09:23:41.917: AT-SPI: Could not obtain desktop path or name

** (zenity:19636): WARNING **: 09:23:41.917: atk-bridge: get_device_events_reply: unknown signature

** (zenity:19636): WARNING **: 09:23:41.917: atk-bridge: get_device_events_reply: unknown signature

** (zenity:19636): WARNING **: 09:23:41.917: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:19636): WARNING **: 09:23:41.932: AT-SPI: Could not obtain desktop path or name

** (zenity:19636): WARNING **: 09:23:41.932: atk-bridge: get_device_events_reply: unknown signature

** (zenity:19636): WARNING **: 09:23:41.932: atk-bridge: get_device_events_reply: unknown signature

** (zenity:19636): WARNING **: 09:23:41.932: atk-bridge: GetRegisteredEvents returned message with unknown signature

its goes through the install of mod and then it said cant find directory, new to Linux but i am tech savy... any help would be greatly appreciated

**Comment by lindelleric** [comment]
I have the exact same issue... Did you manage to find a solution?

**Comment by Jlf0258** [comment]
So does it work after two days? I decided to reset my whole steam deck and now i am gonna tried it again..., please let me know if you have any pointers.... thank you so much ....
