### ISSUE TITLE
Steam Deck SSE/MO2 install issues

### ISSUE THREAD

**Issue by 404Fox** [rockerbacon/modorganizer2-linux-installer#377]
MO2 cannot open the browser.
The system handler does not have a setting to open `x-scheme-handler/nxm`.

The deck is Arch with KDE, but has an immutable filesystem to facilitate Valve's management of the system packages.
By default, you can only install flatpaks from KDE's Discover app.
The SteamOS version is 3.3.1

The steps I followed are based on this tutorial: https://youtu.be/x55SAwnONbQ

1. Have launched Skyrim at least once, using Proton 6.3-8 (someone said to do this, but my desktop install uses experimental without issue)
2. Install protontricks from discover
3. Run `echo "alias protontricks='flatpak run com.github.Matoking.protontricks'" >> ~/.bashrc`
4. Run the install script (4.3.0 from releases)

I ran the install script again to save its output, choosing the option to "update" MO2.
[install.sh.log](https://github.com/rockerbacon/modorganizer2-linux-installer/files/9432644/install.sh.log)

**Comment by Dreyfus404** [comment]
If you need to download it on Nexus Mods, this video may help you
https://www.youtube.com/watch?v=x55SAwnONbQ
