### ISSUE TITLE
Mod Organizer 2 Failed to install

### ISSUE THREAD

**Issue by sambo60** [rockerbacon/modorganizer2-linux-installer#380]
I'm trying to install  Mod Organizer 2 but it keeps saying it failed.  There are error messages in terminal but I'm not sure how to resolve them.  I have Lutris with Vortex in the past as of last year but recently I wanted to have another Skyrim SE playthrough and reinstalled Vortex on Lutris only to have it not work anymore.  I can't find a solution to that so I thought I would give Mod Organizer 2 a shot.  Here is terminal print out.  Thanks for help.  I did select Proton 6.3 first and then 7.0 but with same results.  I am able to run Skyrim SE without any issues and have even installed a script extender that I got to work as well:

/.../My Games/ModOrg2 >>> ./install.sh                                                                           
INFO: all dependencies met
Gtk-Message: 22:50:32.972: Failed to load module "appmenu-gtk-module"
INFO: selected game 'skyrimspecialedition'
Gtk-Message: 22:50:46.657: Failed to load module "appmenu-gtk-module"
INFO: found Steam in '/home/sambo/.local/share/Steam'
INFO: steam not found in '/home/sambo/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/sambo/.local/share/Steam'
Gtk-Message: 22:50:52.509: Failed to load module "appmenu-gtk-module"
Gtk-Message: 22:50:55.981: Failed to load module "appmenu-gtk-module"
INFO: selected install directory '/home/sambo/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
Gtk-Message: 22:51:13.035: Failed to load module "appmenu-gtk-module"
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
Gtk-Message: 22:51:17.723: Failed to load module "appmenu-gtk-module"
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
Gtk-Message: 22:51:18.253: Failed to load module "appmenu-gtk-module"
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
Gtk-Message: 22:51:27.888: Failed to load module "appmenu-gtk-module"
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
Gtk-Message: 22:51:32.017: Failed to load module "appmenu-gtk-module"
INFO: using wget backend
INFO: fetching remote resource at 'https://skse.silverlock.org/beta/skse64_2_01_05.7z'
INFO: downloading 'https://skse.silverlock.org/beta/skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
Gtk-Message: 22:51:32.232: Failed to load module "appmenu-gtk-module"
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
Gtk-Message: 22:51:32.869: Failed to load module "appmenu-gtk-module"
INFO: removing existing JDK installation in '/home/sambo/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/java'
INFO: installing JDK in '/home/sambo/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/java'
Gtk-Message: 22:51:32.986: Failed to load module "appmenu-gtk-module"
Gtk-Message: 22:51:33.082: Failed to load module "appmenu-gtk-module"
INFO: installing Mod Organizer 2 in '/home/sambo/Games/mod-organizer-2-skyrimspecialedition/modorganizer2'
INFO: installing script extender in '/home/sambo/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/Data' into '/home/sambo/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_1_6_353.dll' into '/home/sambo/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_loader.exe' into '/home/sambo/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: copying '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05/skse64_2_01_05/skse64_steam_loader.dll' into '/home/sambo/.local/share/Steam/steamapps/common/Skyrim Special Edition'
INFO: installing nxm link broker in '/home/sambo/.local/share/modorganizer2'
INFO: installing nxm link handler in '/home/sambo/.local/share/applications/'
INFO: applying protontricks xaudio2_7=native
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.8.2.dev3+gbe3805b', 'console_scripts', 'protontricks')())
  File "/usr/bin/protontricks", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/protontricks/__init__.py", line 1, in <module>
    from .steam import *
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 9, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
Gtk-Message: 22:51:41.806: Failed to load module "appmenu-gtk-module"
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'
Gtk-Message: 22:51:41.928: Failed to load module "appmenu-gtk-module"

**Comment by moriartynz** [comment]
I'm not sure what distro you're running, you might like to try:
```
sudo apt-get install appmenu-gtk2-module appmenu-gtk3-module
pip3 install vdf
```

**Comment by zeparu** [comment]
facing same issue right now on arch linux, protontrick (aur) is newest version and python-vdf is installed

**Comment by rockerbacon** [comment]
Something wrong with Protontricks dependencies, best I can do is recommend trying to install it from another source.
