### ISSUE TITLE
Hanging on "Configuring game prefix"

### ISSUE THREAD

**Issue by PICKLEINMOUTH** [rockerbacon/modorganizer2-linux-installer#381]
Hi all, trying to install MO2 for Fallout New Vegas to play TTW on deck, installation is hanging on configuring game prefix. Output is attached, any help would be greatly appreciated! EDIT looks like it's not specific to New Vegas either, same thing happens trying to install under Fallout 3
[mo2.txt](https://github.com/rockerbacon/modorganizer2-linux-installer/files/9456022/mo2.txt)

**Comment by VolatileRain** [comment]
Ye i’m having the same problem as well 🙁

**Comment by Revan-Sera** [comment]
Me too

**Comment by mattundie** [comment]
Also having this issue on my deck

**Comment by cjdw94** [comment]
Same for me with FO3 GOTY.  Hoping for an easy fix - really want to play modded FO3 on my deck.

**Comment by infinstarlight** [comment]
What has worked for me was letting it run up to configuring the prefix then adding MO to Steam and adding mods through desktop mode and then launching MO in game mode

**Comment by cjdw94** [comment]
How do you add MO to Steam at that point?  The installer keeps telling me it's already installed, but I have no idea where to find it.

**Comment by Revan-Sera** [comment]
I've worked out the issue is to do with a change to proton tricks 1.9.1, if you downgrade to the previous version to works just fine

**Comment by VolatileRain** [comment]
> What has worked for me was letting it run up to configuring the prefix then adding MO to Steam and adding mods through desktop mode and then launching MO in game mode

ok so i did that but now once i’ve loaded into mo2 from game mode i can’t get to fnv’s game folder in order to create a portable instance because it’s a hidden folder and i can’t access it from game mode. i’ve look at where its at in desktop mode. my question is do i launch mo2 from desktop mode to create the instance or what else do i do?

**Comment by Revan-Sera** [comment]
> I've worked out the issue is to do with a change to proton tricks 1.9.1, if you downgrade to the previous version to works just fine I'll post how I did that when I get home and I can look at my steam deck

This is the command I ran to downgrade Protontricks to 1.9.0
flatpak update --commit=ffeb022787f036839f0aa98948025726c5c01173124890dcc3861c09a8be874c com.github.Matoking.protontricks

rerunning install.sh after that fixes the issue and it no longer gets stuck on "configuring game prefix"

P.S I have absolutely zero Linux experience, I've only had a steam deck for a few days so I'm sorry in advance if this is bad advice but it worked perfectly for me.

**Comment by VolatileRain** [comment]
i’m at work rn i’ll try as soon as i get off work….oh god i hope it does 🤞

**Comment by PICKLEINMOUTH** [comment]
> > I've worked out the issue is to do with a change to proton tricks 1.9.1, if you downgrade to the previous version to works just fine I'll post how I did that when I get home and I can look at my steam deck
> 
> This is the command I ran to downgrade Protontricks to 1.9.0 flatpak update --commit=ffeb022787f036839f0aa98948025726c5c01173124890dcc3861c09a8be874c com.github.Matoking.protontricks
> 
> rerunning install.sh after that fixes the issue and it no longer gets stuck on "configuring game prefix"
> 
> P.S I have absolutely zero Linux experience, I've only had a steam deck for a few days so I'm sorry in advance if this is bad advice but it worked perfectly for me.

That's giving me "Error: Can't update to a specific commit without root permissions, do I need to be running this command in the Protontrick's install directory?

**Comment by Revan-Sera** [comment]
I dont think so, try setting a password for the your user (default user is deck) with the passwd command, then try again. as I said I'm a Linux noob with just a couple of days experience. The thing i did directly before I ran than flatpak command was to set a password and enable SSH so I could try this from my Laptop (having trouble with the Steam Deck keyboard).

**Comment by Revan-Sera** [comment]
> > I've worked out the issue is to do with a change to proton tricks 1.9.1, if you downgrade to the previous version to works just fine I'll post how I did that when I get home and I can look at my steam deck
> 
> This is the command I ran to downgrade Protontricks to 1.9.0 flatpak update --commit=ffeb022787f036839f0aa98948025726c5c01173124890dcc3861c09a8be874c com.github.Matoking.protontricks
> 
> rerunning install.sh after that fixes the issue and it no longer gets stuck on "configuring game prefix"
> 
> P.S I have absolutely zero Linux experience, I've only had a steam deck for a few days so I'm sorry in advance if this is bad advice but it worked perfectly for me.

OK. Im 100% sure that Protontricks 1.9.1 is the issue, I just updated it back to 1.9.1 and tried install.sh again and it got stuck on configuring again. downgraded back to 1.9.0 with the command above and its working again, hope this helps.

**Comment by cjdw94** [comment]
> > > I've worked out the issue is to do with a change to proton tricks 1.9.1, if you downgrade to the previous version to works just fine I'll post how I did that when I get home and I can look at my steam deck
> > 
> > 
> > This is the command I ran to downgrade Protontricks to 1.9.0 flatpak update --commit=ffeb022787f036839f0aa98948025726c5c01173124890dcc3861c09a8be874c com.github.Matoking.protontricks
> > rerunning install.sh after that fixes the issue and it no longer gets stuck on "configuring game prefix"
> > P.S I have absolutely zero Linux experience, I've only had a steam deck for a few days so I'm sorry in advance if this is bad advice but it worked perfectly for me.
> 
> OK. Im 100% sure that Protontricks 1.9.1 is the issue, I just updated it back to 1.9.1 and tried install.sh again and it got stuck on configuring again. downgraded back to 1.9.0 with the command above and its working again, hope this helps.

This absolutely worked for me.   I had to get creative a few times after reading the logs, but this was the main source of the problem.   THANK YOU SO MUCH!  =D
