### ISSUE TITLE
Installer fails to start due to "ERROR: redirector binaries not found"

### ISSUE THREAD

**Issue by stewie828** [rockerbacon/modorganizer2-linux-installer#386]
Installer fails to start due to "ERROR: redirector binaries not found". Not sure what is causing this any help would be appreciated.

**Comment by davidchuckjim** [comment]
Did you ever get a resolution to this? I have the same problem and it is stopping me from installing at all.

**Comment by stewie828** [comment]
Haven’t received any assistance with this yet and have yet to figure it out myself. Hoping this issue gains some traction. 

> Did you ever get a resolution to this? I have the same problem and it is stopping me from installing at all.

**Comment by stewie828** [comment]
Closed by mistake.

**Comment by FiraxCZ** [comment]
same problem xd

**Comment by FiraxCZ** [comment]
Found [this](https://www.reddit.com/r/SteamDeck/comments/wjdfy8/guide_6_steps_to_installing_mod_organizer_2/) mby it will work

**Comment by AkitoshTheBold** [comment]
I got the same error. The mistake I made was to clone the repo instead of grabbing an archive from releases.
doing this fixed it for me.
