### ISSUE TITLE
Skryim SE update 1.6.629 update broke SKSE and stopped MO2 from launching

### ISSUE THREAD

**Issue by Gary8thomas** [rockerbacon/modorganizer2-linux-installer#389]
Exactly what the title says, MO2 does not launch anymore and just leads to the original Skyrim launch menu.

**Comment by maciozo** [comment]
Rerunning the installer seems to get MO2 working as before again, but as for SKSE, we'll just have to wait until Silverlock release an update. Not sure there's anything in particular this project can do about that.

**Comment by patrioticparadox** [comment]
First type this into your web browser:

    steam://nav/console

Then allow it to open steam client bootstrapper. Once the console window appears, type:

    download_depot 489830 489833 4570833277049890269

Check the console for the location of the newly downloaded skyrimse.exe version 1.6.353. Then simply replace the exe in your game files with this one. 

Credit ContaBiscuits: https://www.reddit.com/r/skyrimmods/comments/xetnls/skyrim_updated_to_16629/
