### ISSUE TITLE
Installer is not space aware

### ISSUE THREAD

**Issue by YokaiOftheNine** [rockerbacon/modorganizer2-linux-installer#394]
The installer seems to be unaware of spaces in the folder naming as it seems to spit out each word in the folder naming under different line in terminal, I did follow all steps before running the install script, and did it during the initial picking of the selected game

Screenshot attached 
![image](https://user-images.githubusercontent.com/88157094/191460378-2d5eb0bb-2b41-4a82-aeb3-b7dae67e6ac9.png)

**Comment by PoshOctavia69** [comment]
i have the same issue, the error message sent me on a bit of a wild goose chase trying to figure out what it was saying before i noticed this in the issues section, i thought it was just in a non standard location and had been trying to figure out what an environment variable was and how to use it, are there any working workarounds for the issue?

**Comment by YokaiOftheNine** [comment]
The only workaround I found for now is literally renaming the steam folders to have no spaces
Renaming folders allowed the install script to find the install location of games that can be modded with MO2, I didn't figure that out until I put 2 and 2 together and found out doing so would be a good workaround
