### ISSUE TITLE
Installer can't find Steam

### ISSUE THREAD

**Issue by xylorp** [rockerbacon/modorganizer2-linux-installer#396]
Hey! I'm getting this weird error using the installer:
`INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: steam not found in ''
INFO: steam not found in '/root/.var/app/com.valvesoftware.Steam/.local/share/Steam'
ERROR: could not find any Steam library containing a game with appid '22380'. If you known exactly where the library is, you can specify it using the environment variable STEAM_LIBRARY
`

If I set the ENV STEAM_LIBRARY to the steam library path, it still does not work : 0

If I do export STEAM_LIBRARY=path, I can do echo $STEAM_LIBRARY and it gives the path, but MO2 still says it can't find steam in /root/var/app/ or '', instead of saying it can't find steam in 'path'

**Comment by Zwolf6** [comment]
How did you solve this?
