### ISSUE TITLE
How to pass parameters to MO2?

### ISSUE THREAD

**Issue by ajventer** [rockerbacon/modorganizer2-linux-installer#401]
Based on my understanding of commit 5eb1a7e77a21c95ce69911ca21e1e7694dcd6bfa if a parameter is passed to mo-redirector, it should be passed along to MO2 - allowing for things like auto-launching the game.

Yet trying this from steam causes instant crashes to happen with no error message. I tried the obvious version: change the launch options to:
%command% Journey <-- No luck
Used the format MO2 generates if you create desktop icons:
%command% "moshortcut://Journey" 

Still no luck. 

This would be really helpful on the steam deck as it would avoid needing to switch profiles to keyboard mouse in order to click "Run" in MO2 only to immediately switch back to gamepad to actually control the game.

Am I misinterpreting the commit or am I using the feature wrong ?

**Comment by Zouizoui78** [comment]
If I understand the code in the commit you linked, what happens is that when you pass an argument to the redirector, it doesn't forward it to mo2, but instead it execute mo2's nexus download handler and pass the argument to it.

If you don't plan on using mo2's nexus download integration, you can change the line 114 in steam-redirector/main.c from
`exit_status = execute_from_path_file(MO2_DOWNLOAD_PATH_FILE, argv[1]);`
to
`exit_status = execute_from_path_file(MO2_PATH_FILE, argv[1]);`

Then compile by calling `make` in the steam-redirector directory, rename main.exe to SkyrimSELauncher.exe and move it to your Skyrim installation directory (`/path/to/SteamLibrary/steamapps/common/Skyrim Special Edition`).

It should then forward whatever argument you type in steam's launch options correctly to mo2. Using the Septimus modlist, I entered the argument `moshortcut://Septimus` and it worked.

Be aware that while I have not tested I'm pretty sure it will break the nexus download integration.

Regarding your issue with the steam deck, you don't have to change the input profile. You can use the mouse on any window by pressing the steam button while moving on the right trackpad. No very comfortable of course but it should be enough to click the run button in mo2.

**Comment by ajventer** [comment]
Personally I don't use the download integration so wouldn't have cared, but based on your findings, if it's possible to easily have both features in parallel that seems to me the correct approach. If you'd like to do a P.R. based on your change please go ahead, otherwise I'm happy to do it myself.

Otherwise, as it happens, I have found that the easiest way to deal with MO2 in game mode is to hit the RUN button using the touchpad. But it would still be nice to use the bypass feature MO2 already has.

**Comment by rockerbacon** [comment]
The version in the master branch should already be capable of properly handling a single parameter. All that's necessary now is to add some instructions to the post-install documentation.
