### ISSUE TITLE
Oblivion no longer launching

### ISSUE THREAD

**Issue by AnotherTieflingBard** [rockerbacon/modorganizer2-linux-installer#406]
It creates a popup that says "an error occurred: Failed to save '{}', could not create a temporary file: {} (error {})" 

This happens no matter how many times you freshly install both the game and the mod organizer

**Comment by Razatop** [comment]
Getting this to after installing (Or rather trying to install [Compat patches for Unique Landscapes](https://www.nexusmods.com/oblivion/mods/13834/)) Anything like this for you? Also uploading your dump log would probably help  :D

**Comment by rockerbacon** [comment]
Duplicate of #407
