### ISSUE TITLE
Mod Organizer 2 cannot login to Nexus nor open a browser

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#41]
## Description

Attempting to login to Nexus from Mod Organizer 2 may cause the program to freeze. The program may also freeze when doing anything that should open a browser (visit mod on Nexus, etc).

## Workarounds

It's possible to login to Nexus by manually adding your Nexus API key:

1. Visit [this page on Nexus](https://www.nexusmods.com/users/myaccount?tab=api) and click the button "REQUEST AN API KEY" next to Mod Organizer 2;
2. Copy the generated key;
3. Go to `Tools > Settings > Nexus` and click on "Enter API key manually";
4. Paste the key you copied on step 2 into the textbox and click ok;

There is no known workaround for allowing it to open a browser.

## Cause

The cause of this bug is still unknown.

**Comment by brandonegbert** [comment]
It seems like there should be someway set a handler for `nxm://` protocol links in the browser but I messed with it for a bit and couldn't get it working.  If someone could figure that out then using the MO2 runscript as the executable for it might work using the native browser.

Alternatively it may be possible to install a browser into the WINE env and use that for browsing and installing but I haven't tried that.

**Comment by rockerbacon** [comment]
> It seems like there should be someway set a handler for `nxm://` protocol links in the browser but I messed with it for a bit and couldn't get it working. If someone could figure that out then using the MO2 runscript as the executable for it might work using the native browser.

NXM URIs are already handled by the installer, you should be able to simply use the "Mod Manager Download" button from within your native browser.

**Comment by brandonegbert** [comment]
Well, doesn't work for me then.

**Comment by rockerbacon** [comment]
> Well, doesn't work for me then.

Open a separate issue so your problem can be investigated.

**Comment by rockerbacon** [comment]
The recent updates to MO2 2.4.4 and Proton 6.3 seem to have fixed this issue.
