### ISSUE TITLE
incompatible with games stored on the steam deck SD card

### ISSUE THREAD

**Issue by IoannesNuncius** [rockerbacon/modorganizer2-linux-installer#417]
The installer seems to assume that steam is saving the games to the ordinary internal storage URL, and installation fails if it doesn't find game files in that location. Is there a way to adjust the installation path to an SD card?

**Comment by Zouizoui78** [comment]
This problem doesn't occur only on the deck, I had the same issue on my desktop where Skyrim is installed on another partition than the system root.

You can create a symlink to workaround the issue :
`cd /home/deck/.steam/root/steamapps/common/ && ln -s /path/to/Skyrim/directory`

**Comment by demolitions** [comment]
I can attest the symlink method works perfectly to install and start MO2,
on the Steam Deck, if you installed the game in the SD Card, you'll have to execute 
`ln -s /run/media/mmcblk0p1/steamapps/common/Skyrim\ Special\ Edition /home/deck/.steam/steam/steamapps/common/` 
(substitute the game directory with the correct one if it's not Skyrim SE)
Keep in mind that if you already tried to install MO2 with this package, and it failed, it will have already created a directory `/home/deck/.steam/steam/steamapps/common/Skyrim\ Special\ Edition` (again, substitute correct game directory name) which you will have to delete to create the symbolic link.
Shouldn't this workaround be written at least in the README?
Or better, would it work adding the "standard" Steam Deck SDcard library path (`/run/media/mmcblk0p1`) to the the `utils/list-steam-libraries.sh` array of candidates?

**Comment by jschuhmann47** [comment]
Yes, I also believe that it should be mentioned in the README, at least someting that redirects here

**Comment by rockerbacon** [comment]
Will be handled in #496
