### ISSUE TITLE
/tmp mounted with "noexec" leads to installation failure

### ISSUE THREAD

**Issue by alxwk** [rockerbacon/modorganizer2-linux-installer#422]
AFAIK, mounting /tmp with "noexec" attribute is a common practice in modern distros, but this leads to failure as the installer tries to execute scripts from there. Setting CACHE=0 doesn't help. Editing `downloads_cache`
 into something like `"$script_root/tmp/mo2-linux-installer-downloads-cache"` allows the installer to work, but it just because I run it from a directory placed into a filesystem mounted with "exec", which may not be true for a random user setup.

So, at least, the fact that the cache directory needs to be at a filesystem allowing execution should be noted in README.md.

**Comment by MAESTROHANTER** [comment]
> AFAIK, mounting /tmp with "noexec" attribute is a common practice in modern distros, but this leads to failure as the installer tries to execute scripts from there. Setting CACHE=0 doesn't help. Editing `downloads_cache` into something like `"$script_root/tmp/mo2-linux-installer-downloads-cache"` allows the installer to work, but it just because I run it from a directory placed into a filesystem mounted with "exec", which may not be true for a random user setup.
> 
> So, at least, the fact that the cache directory needs to be at a filesystem allowing execution should be noted in README.md.

I'm probably stuck into exactly this situation cause it can't create dir in my tmp - always error. Can you describe please what exactly do you edit to solve this?
