### ISSUE TITLE
mkdir: cannot create directory

### ISSUE THREAD

**Issue by ImThomasThorne** [rockerbacon/modorganizer2-linux-installer#427]
I ran the install script and got this error. I'm hoping that its not because I need to run as sudo.

> [thomas@fedora MO2 Installer]$ sh install.sh 
> INFO: all dependencies met
> INFO: selected game 'newvegas'
> INFO: found Steam in '/home/thomas/.local/share/Steam'
> INFO: steam not found in '/home/thomas/.var/app/com.valvesoftware.Steam/.local/share/Steam'
> INFO: game not found in '/home/thomas/.local/share/Steam'
> INFO: game found in '/home/thomas/DriveOne/SteamLibrary'
> /home/thomas/DriveOne/Mod Organizer 2/MO2 Installer/utils/dialog.sh: line 43: Organizer: command not found
> INFO: selected install directory '/home/thomas/DriveOne/Mod Organizer 2/FNV-MO2'
> INFO: using wget backend
> INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
> INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
> mkdir: cannot create directory ‘/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07’: Permission denied

![Screenshot_20221218_200126](https://user-images.githubusercontent.com/65457136/208316931-dd1e8f24-5f58-4497-8200-039c2012d47f.png)

**Comment by Dipseebloo** [comment]
I ran into the same problem and sadly while running as `sudo` did allow me to go over this error, it also caused like 10 more problems... Was your experience any different ?

**Comment by Cobra00747** [comment]
I'm having a very similar issue.
![image](https://user-images.githubusercontent.com/121925475/210936456-2f53f9fe-9aeb-4243-977d-b081e62d74a7.png)

I made a folder named java at that location and it didn't work.

Complete log:
![image](https://user-images.githubusercontent.com/121925475/210936354-7fd28b11-c657-4432-a935-39e487698e73.png)

**Comment by MageInBlack** [comment]
It happened to me as well. I ran the script as sudo first, then as regular user. Turns out they create the similar directory in /tmp as root if you run the script. And permission is denied cause it can be accessed only by root.

To fix it i removed the mo2 directory int /tmp with sudo rm -d
And then launched the script as user
It seems to work now

So please if you have similar issue that:
/tmp has the right permissions
there is no mo2 file in there that is only accessed by root
if there is try removing it and starting script again AS USER and not as root.

**Comment by rockerbacon** [comment]
Don't run anything within this project as a root user. It is not necessary and will lead to broken installs.

Make sure your `/tmp` directory is flagged to allow any user to read, write and execute it (777).
