### ISSUE TITLE
After selecting game install for fo4 its not finding my steam library

### ISSUE THREAD

**Issue by ImThomasThorne** [rockerbacon/modorganizer2-linux-installer#428]
Trying to set up fallout for and for what ever reason the script isn't finding the right library location

> [thomas@UNKNOWN MO2 Installer]$ ./install.sh 
> INFO: all dependencies met
> INFO: selected game 'fallout4'
> INFO: found Steam in '/home/thomas/.local/share/Steam'
> INFO: steam not found in '/home/thomas/.var/app/com.valvesoftware.Steam/.local/share/Steam'
> INFO: game found in '/home/thomas/.local/share/Steam'
> /home/thomas/DriveOne/Mod Organizer 2/MO2 Installer/utils/dialog.sh: line 43: Organizer: command not found
> INFO: selected install directory '/home/thomas/DriveOne/Mod Organizer 2/FO4-MO2'
> INFO: using wget backend
> INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
> INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
> INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
> INFO: using wget backend
> INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
> INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
> INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
> INFO: using wget backend
> INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
> INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
> INFO: using wget backend
> INFO: fetching remote resource at 'https://f4se.silverlock.org/beta/f4se_0_06_21.7z'
> INFO: downloading 'https://f4se.silverlock.org/beta/f4se_0_06_21.7z' to '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21.7z'
> INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21.7z' to '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21'
> INFO: removing existing JDK installation in '/home/thomas/.local/share/Steam/steamapps/compatdata/377160/pfx/drive_c/java'
> INFO: installing JDK in '/home/thomas/.local/share/Steam/steamapps/compatdata/377160/pfx/drive_c/java'
> INFO: installing Mod Organizer 2 in '/home/thomas/DriveOne/Mod Organizer 2/FO4-MO2/modorganizer2'
> INFO: installing script extender in '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4'
> INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21' into '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4'
> INFO: installing nxm link broker in '/home/thomas/.local/share/modorganizer2'
> INFO: installing nxm link handler in '/home/thomas/.local/share/applications/'
> INFO: applying protontricks xaudio2_7=native
> steam-runtime-launcher-service[128]: W: The --socket option is deprecated. Prefer to use --session or --bus-name.
> Executing mkdir -p /home/thomas/DriveOne/SteamLibrary/steamapps/compatdata/377160
> ------------------------------------------------------
> warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> ------------------------------------------------------
> Using winetricks 20220411 (protontricks-flatpak) - sha256sum: 7742386ba997512fc50088dc66dc6119946de735a62b0a7f0763cd3b1924abbd with wine-6.3 and WINEARCH=win64
> Using native override for following DLLs: xaudio2_7
> Executing /home/thomas/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 6.3/bin/wine regedit /S C:\windows\Temp\_native\override-dll.reg
> /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
> 0188:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 0190:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> Executing /home/thomas/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 6.3/bin/wine64 regedit /S C:\windows\Temp\_native\override-dll.reg
> /bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
> 0198:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> 01a8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
> INFO: configuring mo2 executable path 'Z:\home\thomas\DriveOne\Mod Organizer 2\FO4-MO2\modorganizer2\ModOrganizer.exe' in '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4/modorganizer2/instance_path.txt'
> INFO: configuring mo2 nxm handler path 'Z:\home\thomas\DriveOne\Mod Organizer 2\FO4-MO2\modorganizer2\nxmhandler.exe' in '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4/modorganizer2/instance_download_path.txt'
> INFO: backing up original executable '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe' in '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4/_Fallout4Launcher.exe'
> mv: cannot stat '/home/thomas/.local/share/Steam/steamapps/common/Fallout 4/Fallout4Launcher.exe': No such file or directory
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21.7z'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/fallout4_f4se_0_06_21'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
> INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by rockerbacon** [comment]
It is trying to find the game in the library at `/home/thomas/.local/share/Steam`. If the game isn't there but was there at some point, it is possible Steam has left some junk behind which the installer detected as the game.

**Comment by rockerbacon** [comment]
This will be handled in #496
