### ISSUE TITLE
MO2 Mod and Download paths?

### ISSUE THREAD

**Issue by AldricXSara** [rockerbacon/modorganizer2-linux-installer#429]
Cannot locate the download and mod path in default installtion path.
Also, Will symlink break the path config?

**Comment by rockerbacon** [comment]
It will vary based on where you installed MO2 and whether you selected a portable install or not. It will either be somewhere within the game's compatdata folder or in the folder where MO2 is installed.

Symlinking should work fine as long as the links don't cross filesystems (can't symlink to your HDD if MO2 is in your SSD). If you need to symlink across devices, you may need additional configurations to steam's pressure vessel and Flatpak (if you're using it).
