### ISSUE TITLE
Installing mo2 for Fallout4 doesn't change launch options

### ISSUE THREAD

**Issue by eNTi** [rockerbacon/modorganizer2-linux-installer#432]
I'm trying to get this running for Fallout 4. I had it working perfectly for Fallout New Vegas before.

Edit: It seems main.exe just starts the game instead of redirecting to mo2?

**Comment by mihalycsaba** [comment]
yeah, the game won't launch after install

**Comment by rockerbacon** [comment]
Lacking information
