### ISSUE TITLE
Unable to execute "./install.sh"

### ISSUE THREAD

**Issue by SumDumGoi** [rockerbacon/modorganizer2-linux-installer#433]
I've been scratching my head on this one for a few days now. To run though what I've done real quick up to this point;

I downloaded the zip from this site, unzipped it, installed protontricks (because it wasn't installed beforehand), downloaded and unzipped 7z, and finally attempted to run step 4 of the installation steps and the result is the following error: 

> ERROR: redirector binaries not found

I'm fairly new to the Linux environment so while I feel like I've learn a lot in this first week alone, I feel like I may be missing something with trying to get this to work. I believe I am using the last stable version of Debian. Any guidance would be appreciated. If you need me to try something through terminal it would be helpful to explain which commands to use and how to use them.

Edit: Resolved. User error. I downloaded the zip from the top of the page instead of the link in the middle of the instructions. Works now; this can be closed.

**Comment by rockerbacon** [comment]
Just to clarify what happened: you downloaded the source code, some of which needs to be compiled before it's functional. The releases always include the compiled artefacts along with the source but if you download just the source, you'd need to compile the binaries yourself before using the installer.
