### ISSUE TITLE
SteamOS Update Fix

### ISSUE THREAD

**Issue by ImCrumby** [rockerbacon/modorganizer2-linux-installer#434]
For anyone having the issue of “An instance of MO2 is already running” after updating Steam Deck/SteamOS to 3.4.x please take a look at [this guide I made. ](https://docs.google.com/document/d/1NhLgjyP8UmbW8HttsqPzPThvPQtpydLcrF00ZY5tXYQ/edit?usp=sharing) 

It goes in depth on how to fix the issue as it is more a Valve problem than a rockerbacon one. Please keep in mind I’m a Linux/SteamOS noob so if you have any critiques be sure to let me know so I can edit the guide accordingly :)

Edit: this seems to be a Fallout New Vegas issue as I’ve seen people say after updating their Oblivion install still worked. 

In theory this should work for all future SteamOS updates, but if you value your sanity and just want to play Fallout New Vegas then I’d just not update.

**Comment by lyckantropen** [comment]
I have found that you don't need to install `cabextract` system-wide so your configuration can survive SteamOS upgrades. You need to download the Arch build of cabextract from e.g. [here](https://ftp5.gwdg.de/pub/linux/archlinux/community/os/x86_64/cabextract-1.9.1-2-x86_64.pkg.tar.zst) then:

* unpack it with Ark (you can use the default path which will be `~/Downloads`)
* in Konsole create a subfolder in your home folder to hold binary files: `mkdir ~/.bin`
* run `kedit ~/.bashrc` to open your `.bashrc` in a text editor
* at the end of the file add the line `export PATH=~/.bin:$PATH`
* copy the cabextract binary to the newly created folder: `cp ~/Downloads/usr/bin/cabextract ~/.bin`
* open a new tab in Konsole and check that `cabextract` is found

**Comment by rockerbacon** [comment]
The installer already keeps everything within the user's home directory, so there really shouldn't be a problem with Steam Deck updates.

One issue I see is SteamOS not including cabextract. This could be fixed by the installer, but it is difficult to know for sure if it would fix the problem without means to consistently reproduce it.

**Comment by rockerbacon** [comment]
I'll move this conversation to #431, as that was opened first.
