### ISSUE TITLE
The file doesn't exist

### ISSUE THREAD

**Issue by YAR-Oracool** [rockerbacon/modorganizer2-linux-installer#435]
So I tried to install mo2 using your script, which I thought was broken because I have limited net access and limited thing that can bypass that limit. I finally gave up because your script doesn't allow me to point a file at it and say this is the file X you need, and tried to make my own. And this is where the issue began.

I attempted to basically do the script manually and at first it seemed fine, but the game had no vocal, so I tried the script again and managed to bypass my net access which resulted in success.

I launched the game MO2's first screen popped up, and I said global instance then it detected my previous modded set up, so I just told it to do that but changed the instance location to a different place.

After doing so I got the error in that image, Obviously what I did ruined the script. So I thought ok, I just reinstall. NOPE! Didn't work. I went and created the file it was missing, but I was hit with your antivirus is blocking the program. I came to the mane page to see if there was a full uninstall, but still nothing, so here I am. How do I fix this?
![Uploading Screenshot_20230102_201507.png…]()

**Comment by rockerbacon** [comment]
Can't provide support under such specific limitations.
