### ISSUE TITLE
Running game on steam does not start MO2

### ISSUE THREAD

**Issue by Cobra00747** [rockerbacon/modorganizer2-linux-installer#437]
Today's error;
![image](https://user-images.githubusercontent.com/121925475/211136502-d24b6b35-5ffe-423d-a3df-ec267f360bc0.png)

Yesterday I also got this error;
![Screenshot from 2023-01-05 21-01-13](https://user-images.githubusercontent.com/121925475/211136891-75d93d5b-f51e-4b5d-992d-c8a035b22d7a.png)

Fallout 4 is set up as instructions describe, all requirements fulfilled. Using POP!_os 22.04

Any suggestions would be greatly appreciated. Thank you for your time!

**Comment by Azurion42** [comment]
I'm running into the second error myself. Have you happened to have any luck with fixing this issue? I'm trying to get this working for skyrim.

**Comment by Cobra00747** [comment]
> I'm running into the second error myself. Have you happened to have any luck with fixing this issue? I'm trying to get this working for Skyrim SE.
> 
> Update: One thing I tried was putting a symlink for steamapps in the skyrim folder (FO4 Folder for you) and it started to install but I ran into other issues after that.

No solution, all I did was attempt another install and I got the first error. Idk how that "fixed" the second error.

**Comment by Azurion42** [comment]
I found a fix for the first problem where mkdir can't make a folder in tmp. I opened up the install.sh file and changed the line (probably line 18)
`downloads_cache=/tmp/mo2-linux-installer-downloads-cache`
with the following line
`downloads_cache=/home/[user]/Downloads/tempcache/mo2-linux-installer-downloads-cache` 
and it installed without issue. I did not run it as sudo, it found my game and installed MO2. 
However now it won't start up, so I have to troubleshoot that. But at least it installed.

**Comment by Cobra00747** [comment]
> I found a fix for the first problem where mkdir can't make a folder in tmp. I opened up the install.sh file and changed the line (probably line 18) `downloads_cache=/tmp/mo2-linux-installer-downloads-cache` with the following line `downloads_cache=/home/[user]/Downloads/tempcache/mo2-linux-installer-downloads-cache` and it installed without issue. I did not run it as sudo, it found my game and installed MO2. However now it won't start up, so I have to troubleshoot that. But at least it installed.
> 
> edit 1: I created the folder `tempcache` in my `Downloads` folder and directed the install to go there.
> 
> edit 2: I fixed the second problem with it not starting. I installed MO2 in `/home/[user]/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Skyrim Special Edition/` But now for whatever reason it's telling me it can't start it.

I've modified line 18 with this
`downloads_cache=/media/cobra_007/External\ 1/tempcachedownloads`
Edited nothing else.
I installed to 
`home/cobra_007/Games/mod-organizer-2-fallout4`
Got this error
`mkdir: cannot create directory ‘/media/cobra_007/External 1/SteamLibrary/steamapps/compatdata/377160/steamapps/compatdata/377160/pfx/drive_c/java’: No such file or directory`
After I get back from work I'll see what I can do to fix it.

**Comment by Cobra00747** [comment]
I had to "babysit" the installation and make it's directory files manually. I got it fully installed however on running FO4, MO2 didn't start, instead it proceeded with startup of FO4. I don't know if there's any error files or not, but so far the installation is complete.

**Comment by dan5tan** [comment]
I'm getting the same mkdir error with Fallout New Vegas. Looks to be same root cause of having Steam Library situated outside of home directory. Manually creating the directories isn't working.I also have also tried manually exporting path variables, editing the scripts to 'hardcode' the paths to the directory, and the usual reinstall/upgrade to latest/etc. I'm not sure what can be done but each time the script fails it fails at the java line. Curious if anyone has found a workaround because I've hit a wall. Willing to test what I can.

**Comment by Cobra00747** [comment]
> I'm getting the same mkdir error with Fallout New Vegas. Looks to be same root cause of having Steam Library situated outside of home directory. Manually creating the directories isn't working.I also have also tried manually exporting path variables, editing the scripts to 'hardcode' the paths to the directory, and the usual reinstall/upgrade to latest/etc. I'm not sure what can be done but each time the script fails it fails at the java line. Curious if anyone has found a workaround because I've hit a wall. Willing to test what I can.

I haven't found any other error in regards to directory errors. I just followed the filepath directly and fixed it. I'd make sure you made the file directory correctly without spelling errors or capitalization.

**Comment by Cobra00747** [comment]
I also need to install MO2 for SSE and FONV so I'll do those soon and troubleshoot em, then report any errors here.

**Comment by Cobra00747** [comment]
I'll let this sit now, I give up.

**Comment by alexdloia** [comment]
I'm also having the same issue with FNV where the install works fine, but neither game nor the mod manager will start (I click "play", it turns to "stop" for a few seconds, and then reverts to "play"). I tried looking at Wine/Proton logs but couldn't find anything wrong (though I'm no expert). I'm using the flatpak verison of Steam.

**Comment by alexdloia** [comment]
Actually, following the [above](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/437#issuecomment-1414818911) got it working for me

**Comment by rockerbacon** [comment]
Inability to create the directory within `/tmp` is caused by broken permissions to the directory. Inability to create the java directory is caused by not creating a game prefix by running it on Steam when the installer instructs you to.
