### ISSUE TITLE
Proton 6.6 =< for Dot Net and Visual C 2019 Runtime support

### ISSUE THREAD

**Issue by outsidefactor** [rockerbacon/modorganizer2-linux-installer#438]
Bethesda's games are heavily modifiable, but poorly written. The more mods you run the more you need to intervene to keep the game fast and stable.

Many fixes rely on DLL injection, and most of those injection methods use code that needs the Visual C 2019 runtime. Most fixes for FPS unlocking and slow load times require VC2019 support.

Currently, Mod Organizer 2 for Linux only supports Valve Proton 6.3, which means that Protontricks will failed to install Dot Net, Mono or the Visual C 2019 runtime.

Is there any plan to migrate to Proton 7.0?

**Comment by alghostzx** [comment]
You can backup your launcher exe in the game folder, rename the vc2019 setup exe to the launcher's original name, and run the game, which will run the setup, from there you should install it normally, delete the vc2019 setup exe, and then restore your launcher exe.
Worked for me in skyrim SE on the steam deck, running proton 6.3.

**Comment by rockerbacon** [comment]
The officially supported Proton version is now 8.0. Manually adding VC2019 shouldn't be necessary as MO2 itself requires it.
If anyone feels the need for additional Protontricks in a game, just open a specific issue or pull request with examples of mods/tools you have tested that require a new Protontrick. Adding Protontricks is as simple as adding them to the `game_protontricks` variable in the desired [gamesinfo file](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/master/gamesinfo).
