### ISSUE TITLE
Issue: Invisible UI components: radio buttons checkboxes, etc. (solved)

### ISSUE THREAD

**Issue by TryToRemember** [rockerbacon/modorganizer2-linux-installer#443]
Simple fix, it's Qt. If you cannot see parts of the interface, it's because of Qt Quick Controls and the custom style; you can: put in one that works that is not Windows Vista specific or has a custom transparency/alpha, or enable the various winetricks bits to force it to display properly, or edit the QtQuick2Plugin data, OR, standard simple way, _just delete / rename the qwindowsvistastyle.dll in the styles directory_ so that it will use the Qt's default, which displays buttons and checks and sliders in the boring-but-functioning way.

No idea if the installer script knows this or didn't do what it was supposed to do, but this is my current workaround.

Thanks for letting me "think out loud" here.

**Comment by TryToRemember** [comment]
update: further research shows a patch for wine to enable themed radio buttons, but this patch was just accepted and checked-in to MASTER about 8 weeks ago, so I highly doubt any proton from 2020 would support this.

https://gitlab.winehq.org/wine/wine/-/merge_requests/1220

But that begs the question, how are YOU and everyone else seeing radio buttons fine, and I'm not? Do most people use lutris? I do not.

**Comment by TryToRemember** [comment]
Original post moved down here...
---------------------------------------------

Since I'm having issues I switched it to Valve's supplied Proton 6.3-8... but it made no difference. Normally run GEs, 7.20 I think is the one I usually have for FO4.

So anyway, it _runs_ fine - my screenshots look like your example screenshots.

But that's not what it looks like in Windows! You CANNOT tell what you've toggled... if an FOMOD xml is being processed, you get plain looking text, but if you click it, you get a "it's selected" dashed outline but you cannot tell even if it's a Unique/choose-only-one option, which is selected! Making the whole damn thing **_useless!_**

Now you might want to poop on the wine uxtheme support, but it's worked for so many thousands of other things I'm guessing it's in the MO2 build or the particular way they've called GTK, since the guy who took over for the creator who moved on to paid coding making Vortex, and probably doesn't doesn't care about that - apparently both only work under Windows, and 32-bit & 64-bit code can exist side by side. Maybe it's just something simple, I can install wingdings font or a large unicode set or something, but doesn't seem like it.

I moved it to a staging build for the game's proton runtime so that after a 'protontricks 377160 shell' I can run winecfg and enable GTK3 theming, but that only seems to handle the window decorations?! Sigh. 

If I start from a console I can see lots (hundreds/thousands) of:
**2023-01-18 16:02:39.428 E] OpenThemeData() failed for theme 16 (WINDOW). (Element not found.)
[2023-01-18 16:02:39.474 E] OpenThemeData() failed for theme 5 (MENU). (Element not found.)**

Which would make sense considering checkmarks or icons and box outlines and even modal popups are BLACK with no visible text / content.

Looking in 377160's compatdata tree, I definitely find the relevant bits:
_/windows/syswow64/uxtheme.dll
/windows/syswow64/ext-ms-win-uxtheme-themes-l1-1-0.dll
/windows/syswow64/uxtheme-gtk.dll
/windows/system32/uxtheme.dll
/windows/system32/ext-ms-win-uxtheme-themes-l1-1-0.dll
/windows/system32/uxtheme-gtk.dll_

Using github's handy search feature, I'm going through the shell scripts to see if there's any winetricks winecfgs protontricks lines that would somehow fix not being about to see this crap, but it doesn't appear to be, so this might be a bug report of a sorts. So many distros, so many kernels, so many wines and protons, graphic drivers, varied font installs; the works. (_this is 6.1.5 on fedora 36 with nv 520.56.06 and cuda 11 with xorg no wayland protocol, if you think stuff like that matters for this particular problem - I don't...)_

Can I pirate a native uxtheme.dll from various windows installs, or will that not work either? I see even Windows 10 it's a system32 dll and of course we only have 32-bit compatlibs (ie wine-stable-common or wine-staging-common) on 64-bit only systems.

Ideas? Am I the only one?

Thanks for reading.

**Comment by TryToRemember** [comment]
Original post moved down here...
---------------------------------------------

Since I'm having issues I switched it to Valve's supplied Proton 6.3-8... but it made no difference. Normally run GEs, 7.20 I think is the one I usually have for FO4.

So anyway, it _runs_ fine - my screenshots look like your example screenshots.

But that's not what it looks like in Windows! You CANNOT tell what you've toggled... if an FOMOD xml is being processed, you get plain looking text, but if you click it, you get a "it's selected" dashed outline but you cannot tell even if it's a Unique/choose-only-one option, which is selected! Making the whole damn thing **_useless!_**

Now you might want to poop on the wine uxtheme support, but it's worked for so many thousands of other things I'm guessing it's in the MO2 build or the particular way they've called GTK, since the guy who took over for the creator who moved on to paid coding making Vortex, and probably doesn't doesn't care about that - apparently both only work under Windows, and 32-bit & 64-bit code can exist side by side. Maybe it's just something simple, I can install wingdings font or a large unicode set or something, but doesn't seem like it.

I moved it to a staging build for the game's proton runtime so that after a 'protontricks 377160 shell' I can run winecfg and enable GTK3 theming, but that only seems to handle the window decorations?! Sigh. 

If I start from a console I can see lots (hundreds/thousands) of:
**2023-01-18 16:02:39.428 E] OpenThemeData() failed for theme 16 (WINDOW). (Element not found.)
[2023-01-18 16:02:39.474 E] OpenThemeData() failed for theme 5 (MENU). (Element not found.)**

Which would make sense considering checkmarks or icons and box outlines and even modal popups are BLACK with no visible text / content.

Looking in 377160's compatdata tree, I definitely find the relevant bits:
_/windows/syswow64/uxtheme.dll
/windows/syswow64/ext-ms-win-uxtheme-themes-l1-1-0.dll
/windows/syswow64/uxtheme-gtk.dll
/windows/system32/uxtheme.dll
/windows/system32/ext-ms-win-uxtheme-themes-l1-1-0.dll
/windows/system32/uxtheme-gtk.dll_

Using github's handy search feature, I'm going through the shell scripts to see if there's any winetricks winecfgs protontricks lines that would somehow fix not being about to see this crap, but it doesn't appear to be, so this might be a bug report of a sorts. So many distros, so many kernels, so many wines and protons, graphic drivers, varied font installs; the works. (_this is 6.1.5 on fedora 36 with nv 520.56.06 and cuda 11 with xorg no wayland protocol, if you think stuff like that matters for this particular problem - I don't...)_

Can I pirate a native uxtheme.dll from various windows installs, or will that not work either? I see even Windows 10 it's a system32 dll and of course we only have 32-bit compatlibs (ie wine-stable-common or wine-staging-common) on 64-bit only systems.

Ideas? Am I the only one?

Thanks for reading.

**Comment by 17hoehbr** [comment]
A simple fix that worked for me:

1. In terminal:
```WINEPREFIX=/home/$USER/.local/share/Steam/steamapps/compatdata/$STEAMAPPID/pfx/ winecfg``` 
(replace $USER with your username and $STEAMAPPID with the app id of the game you're using)

2. Go to the libraries tab
3. Under 'New override for library', enter 'qwindowsvistastyle.dll' and click add
4. Scroll down to existing overrides, select qwindowsvistastyle.dll, click edit, and then set it to 'Disabled'
