### ISSUE TITLE
When runing a Nexus Mod Link in chrome It opens this window.

### ISSUE THREAD

**Issue by Kiaos** [rockerbacon/modorganizer2-linux-installer#449]
![Screenshot 2023-02-04 002523](https://user-images.githubusercontent.com/32118932/216754877-8cc60437-103d-4830-a2f9-44b73ecf5544.png)

I accidentally assosciated it with one of the available options which i chose protontrinks and now while proton tricks is installed it only opens that.  I had to uninstall proton tricks to get the previous window for this screenshot and now i have to reinstall it again.

This stupid window doesnt allow me to select anything outside what is in discover. I cant fix link assosications.

**Comment by Martan404** [comment]
Try searching for nxm in that list

If you have problems with the link handler then open this folder
`/home/deck/.local/share/applications/` and edit the file called `modorganizer2-nxm-handler.desktop`

Remove everything in there and paste [this](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/425#issuecomment-1399436896) code instead.

It could be possible that you also need to right-click inside the `/home/deck/.local/share/applications/` folder and click `Open Terminal Here`
Inside the terminal you paste these commands
`xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm`
`xdg-mime default modorganizer2-nxm-handler.desktop x-scheme-handler/nxm-protocol`
and reboot your Steam Deck.

When you try to open a nxm link you should now see something something named **nxm**. I can not remember the exact wording

**Comment by Kiaos** [comment]
I just did that and it opened the protal for seleceding a application to open that link.

**Comment by Martan404** [comment]
> I just did that and it opened the protal for seleceding a application to open that link.

Yes, but can you find something named NXM in that list?

**Comment by Kiaos** [comment]
so after i select nxm in that list nothing happens.

**Comment by Kiaos** [comment]
im using proton ge 48 for fallout 4 not sure that helps.

**Comment by Martan404** [comment]
Do you have Proton 6.3 installed in Steam?

**Comment by Kiaos** [comment]
I have access to 6.3-8 no 6.3 in steam play

**Comment by Martan404** [comment]
Oh, my script is only set up for Skyrim special edition at the moment. 
You need to change this line inside `modorganizer2-nxm-handler.desktop`

"$HOME/Games/**mod-organizer-2-skyrimspecialedition**/modorganizer2/nxmhandler.exe"

I would assume you folder is instead named something like this
`"$HOME/Games/**mod-organizer-2-fallout4**/modorganizer2/nxmhandler.exe"`

**Comment by Kiaos** [comment]
Installing 6.3 now

**Comment by Kiaos** [comment]
It works now thanks.

**Comment by Kiaos** [comment]
[Desktop Entry]
Type=Application
Categories=Game;

Exec=bash -c 'env "STEAM_COMPAT_CLIENT_INSTALL_PATH=$HOME/.steam/steam" "STEAM_COMPAT_DATA_PATH=$HOME/.steam/steam/steamapps/compatdata/489830" "$HOME/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-48/proton" run "$HOME/Games/mod-organizer-2-fallout4/modorganizer2/nxmhandler.exe" "%u"'

Name=Mod Organizer 2 NXM Handler
MimeType=x-scheme-handler/nxm;

For proton GE 48

**Comment by Martan404** [comment]
Glad to hear! Haha I was just going to suggest that you can edit my paths for Proton 6.3 to work with proton GE. Do note in the script you pasted that `STEAM_COMPAT_DATA_PATH` path is still for Proton 6.3

I don't know if that matters or not.

**Comment by Kiaos** [comment]
yea it does it didnt work.

**Comment by Martan404** [comment]
Maybe you can use the same folder that you already use, just remove the /proton

See if this works
`[Desktop Entry]
Type=Application
Categories=Game;

Exec=bash -c 'env "STEAM_COMPAT_CLIENT_INSTALL_PATH=$HOME/.steam/steam" "STEAM_COMPAT_DATA_PATH=$HOME/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-48" "$HOME/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-48/proton" run "$HOME/Games/mod-organizer-2-fallout4/modorganizer2/nxmhandler.exe" "%u"'

Name=Mod Organizer 2 NXM Handler
MimeType=x-scheme-handler/nxm;`

**Comment by Kiaos** [comment]
So I couldnt get Proton GE 48 working so im just gonna leave it at that. If I wana install mods I'll do it with 6.3 and if I wana play I'll do it with Proton GE 48
