### ISSUE TITLE
DynDOLOD does not work

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#45]
## Description

DynDOLOD fails when trying to generate tree LODs.

## Workaround

Use [TES5LODGen](https://www.nexusmods.com/skyrim/mods/62698/) instead.

## Cause

DynDOLOD uses Microsoft's TextConv which does not work on Wine. More details can be found in spooknik/SkyrimSE-Linux-Modding#5

**Comment by rockerbacon** [comment]
Someone on Reddit pointed out that DynDOLOD uses Microsoft's TexConv for compressing DDS files and anything relying on this tool may not work on Wine.

**Comment by FormBurden** [comment]
Refer to this workaround that someone ended up finding, which works great: [Reddit Link](https://www.reddit.com/r/skyrimmods/comments/uyrxzr/dyndolod_in_mo2_on_linux_if_anyone_who_wants_to/)

**Comment by rockerbacon** [comment]
Closing this, since there hasn't been any activity in quite a while and there have been a few reports of newer DynDOLOD + newer Proton working as expected.

**Comment by Rain-Gayming** [comment]
Bringing this back up, when I run dyndolod ill eventually get an error saying that an "OS function could not be called"

**Comment by RoaminGrape** [comment]
I've noticed something, especially when it comes to Linux Mint, TexGenx64 defaults to generating BC7 files. When the menu shows for TexGen, select BC3 as the compression format for all four boxes below. When using DynDOLOD afterwards to generate the textures, it should no longer crash when attempting to run texconv. I was able to get the mod to work afterward.
