### ISSUE TITLE
README out of date: no release tag with latest fixes from this year

### ISSUE THREAD

**Issue by DominicWatson** [rockerbacon/modorganizer2-linux-installer#451]
The install instructions in the README instruct to "Download the latest release" and provide a link to the latest tagged release. However, this is quite old and missing a number of fixes added to this repo since then (for me, the missing bits were patch for FNIS with the empty directory trick + the latest SKSE endpoints).

Is the master branch in a stable state ready for a new tag + update README links?

p.s. this project is fantastic!

**Comment by rockerbacon** [comment]
I've made a new release and updated the README link
