### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ladykorine** [rockerbacon/modorganizer2-linux-installer#459]
I followed the installation directions carefully. When I go to run Skyrim AE a little black box pops up for a moment, then it goes away and nothing launches. I have tried multiple versions of proton and I can't get it to work no matter what I try. Using Pop OS with a fairly fresh build and fresh install of Skyrim.

**Comment by Unfoundzoro** [comment]
Having similar issues in fallout new vegas, did you find any fix?

**Comment by Liassica** [comment]
If you're using Flatpak, see [my comment on #463](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/463#issuecomment-1537234940) for a potential fix.
