### ISSUE TITLE
Trouble updating NVSE

### ISSUE THREAD

**Issue by ChongaPapi** [rockerbacon/modorganizer2-linux-installer#461]
I'm having trouble updating the version of NVSE that comes with this Linux version of mod organizer 2. I downloaded a new version of NVSE extracted it to the root folder. Launch game and I'm still getting prompts that my NVSE is still outdated.

**Comment by Razatop** [comment]
You using xNVSE or NVSE?

**Comment by rockerbacon** [comment]
Closing as stale
