### ISSUE TITLE
Unable to open in explorer / unable to edit files in MO2

### ISSUE THREAD

**Issue by BirbOwner** [rockerbacon/modorganizer2-linux-installer#462]
I downloaded a mod where it requires you to edit a JSON file to configure it, but whenever I try to look at a file inside MO2 by clicking on it and opening it in explorer, it just gives me this error : [2023-04-02 23:14:22.927 E] failed to invoke 'open C:/users/USERNAME/AppData/Local/ModOrganizer/Skyrim Special Edition/mods/Equipment Toggle/EquipmentToggle/Config.json': BadEXEformatfor%1. (0xc1). This goes for anything else I want to look at in explorer.

**Comment by maural** [comment]
I am also having issues with being unable to open files in the Explorer (Dolphin). Specifically, in Settings > Themes, the "Explore" button beside the Style is not functional. I'm trying to add a [custom style](https://gist.github.com/pineapplemachine/454eacec21835fb61481b180d8d087d3) to increase the font size for my 4k screen.

**Comment by rockerbacon** [comment]
Could not reproduce. Make sure you're using the latest release here on GitHub and if the problem is still present, I'll reopen the issue
