### ISSUE TITLE
How to totally uninstall

### ISSUE THREAD

**Issue by zrcaeiou** [rockerbacon/modorganizer2-linux-installer#466]
How to totally uninstall this MO2? Should I just remove the "~/Games/mod-orgnizer-2-xxx" directory, or do something else?

**Comment by UnstoppableMango** [comment]
I'm very new to this project, but here are a few paths I noticed in the scripts that may or may not have MO2 files

The install dir you already mention
`$HOME/.local/share/modorganizer2`
`$game_prefix/drive_c/java`
`$HOME/.local/share/applications/modorganizer2-nxm-handler.desktop`
`$game_installation/modorganizer2`
`$HOME/.config/modorganizer2`

where `game_prefix` and `game_installation` are

```shell
game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
```

It also does some whatnot with your game exe files to get the steam redirection to work, so either verify your local files in steam, or uninstall and reinstall the game in question.

If you're super paranoid, this script also puts files in `/tmp` but I wouldn't worry too much about that

`/tmp/mo2-linux-installer-downloads-cache`

**Comment by zrcaeiou** [comment]
THANK YOU！That's helpful.
