### ISSUE TITLE
Could not find 'Fallout New Vegas' in any of your Steam libraries

### ISSUE THREAD

**Issue by bahuers** [rockerbacon/modorganizer2-linux-installer#468]
Linux Mint 20.1 Cinnamon
terminal says this

INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: steam not found in ''
INFO: steam not found in '/root/.var/app/com.valvesoftware.Steam/.local/share/Steam'
ERROR: could not find any Steam library containing a game with appid '22380'. If you known exactly where the library is, you can specify it using the environment variable STEAM_LIBRARY

Actual game directory is ~/.steam/debian-installation/steamapps/common/Fallout New Vegas$, so how can I direct it to the right one? I on't really understand what it says in the terminal with environment variable, I'm new to linux

**Comment by bahuers** [comment]
Solution: selected proton 6.3-8 compatibility for new vegas, before it was 7.0-6 and that's why it didn't work I suppose

**Comment by Julia-nbeo** [comment]
im having the same issue now with both FNV and FO3, in that the mo2 install looked in the  debian-installation folder but not the comms or compatdata folders deeper in, but i dont understand your fix? i used proton 6.3-8 to run FO3, after switching over from the latest hotfix and deleting the old prefix from the compatdata, but it didnt change anything.

my OS is Ubuntu 24.04, protontricks is 1.12.1, all the other dependancies updatad. ive been at this for a month so any help would be appropriated
