### ISSUE TITLE
Fallout 4 Launcher

### ISSUE THREAD

**Issue by Azurion42** [rockerbacon/modorganizer2-linux-installer#469]
How can I re-launch the launcher to change some graphics settings without uninstalling and reinstalling MO2? I've tried launching the launcher from the drop down menu in MO2, but it says an instance of MO2 is already running instead of throwing up the default launcher.

**Comment by Peremious** [comment]
Go to the executable binaries, and add a "_" to the beginning of the Fallout Luancher exe. It should then execute the launcher.

The way the MO2 install script works is that it replaces the default launcher with the MO2 executable and renames the default launcher to it's own name+_ at the beginning. So all you need to do is add _ to the beginning of the executable name in the executables menu.

**Comment by rockerbacon** [comment]
This is covered in the post-install instructions linked in the README.
