### ISSUE TITLE
[Steam Deck] Skyrim Special Edition: MO2 not showing up

### ISSUE THREAD

**Issue by XargonWan** [rockerbacon/modorganizer2-linux-installer#473]
First, I had to edit `gamesinfo/skyrimspecialedition.sh` otherwise the installer was not finishng as the file that was searching for didn't exist.
```
game_executable="skse64_loader.exe"
```

After this edit the installer ended correctly but MO2 is not running: when I launch the game from Steam it just... Run the game, not MO2.

**Comment by rockerbacon** [comment]
Your edit just masked the real issue. You had some leftover files and was probably affected by #496 which has been long fixed.
