### ISSUE TITLE
NXM links don't download properly

### ISSUE THREAD

**Issue by TheRedBaron56** [rockerbacon/modorganizer2-linux-installer#475]
When downloading a mod from nexus with 'mod manager download' option, the download fails immediately. It does not do this while mo2 is closed; it opens the manager and the download goes through. But if the manager is open when I start the download, it fails. 

I have already looked around and found this thread:[https://github.com/rockerbacon/modorganizer2-linux-installer/issues/355](url) and others like it. I am confident my issue stems from a different error: I'm using the latest version of protontricks (1.10.3) installed through pipx, on Mint Cinnnamon 21.1

**Comment by Cubeson** [comment]
I have the same issue, also Mint Cinnnamon 21.1

**Comment by rockerbacon** [comment]
Duplicate of #317
