### ISSUE TITLE
Loot isn't working properly and/or doesn't even startup when linked to MO2

### ISSUE THREAD

**Issue by BlueberrySempai** [rockerbacon/modorganizer2-linux-installer#476]
It's not like even an issue, just wanted to know if it's even possible to link LOOT to MO2 on linux. It would help me out a ton in modpack building, as sorting mods by my own is pain in the ass. Previously i was succesful to even run LOOT, but it would just tell me "Running for the first time?" and after clicking any button (yes, no) it would just close. Right now, it wouldn't even open.

I do need to notify that without MO2 - LOOT works perfectly fine and will do the deed, but it just doesn't see added mods through MO2 at all, because they are stored in instance, that is separated from root directory of game (in my case - Skyrim SE). And going through google, as i understood - LOOT needs to be opened as part of MO2 executables. And it simply won't startup.

I am providing the screenshot of my LOOT executable, maybe it will help to understand how to link it all together in order to receive a working exe.

![Screenshot_20230524_012914](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/42878325/9959926e-6963-4c32-928f-0f8ae007cbce)

**Comment by itspngu** [comment]
Hey, I've been having issues running LOOT through MO2 and eventually got it to work. I've commented about it as a reply to somebody's (excellent) guide on Nexus: https://forums.nexusmods.com/index.php?/topic/12887082-modding-skyrim-se-on-linux-a-headache-minimization-guide/page-8#entry125529648

**Comment by hazelnot** [comment]
@itspngu I'm having the same issue, but the post you mentioned has been deleted from the Nexus forums :(

**Comment by itspngu** [comment]
> @itspngu I'm having the same issue, but the post you mentioned has been deleted from the Nexus forums :(

Seems they broke their site. I can't figure out how to copy a direct link to the comment, but you can find it on this page when scrolling through it: https://www.nexusmods.com/skyrimspecialedition/mods/91500?tab=posts&BH=1

Here's a copy:

> I feel rather stupid asking this, but in the guide you're instructing us to install LOOT into the main wineprefix, not the skyrim-specific one, and then add it to MO2 as an executable. Where on earth do I find LOOT.exe when browsing for it from MO2's "Edit" dialogue? :D

> Thank you for the great guide.

> Edit: Figured it out, my problem was 2 problems. Or perhaps 3. Or maybe just one and I suck at computers.

> 1: To find LOOT.exe (from the main wineprefix) in MO2 (running in the proton wineprefix for SSE), I added $HOME/.wine/drive_c as "Drive D:" to the latter using winecfg (run from protontricks). Then I was able to select it from D:\Program Files\LOOT\LOOT.exe.
> 2: Don't, really don't, run the LOOT installer in the proton wineprefix. It somehow manages to install an extra copy of the VC runtime and MO2 won't launch after that. Use protontricks to uninstall both LOOT and the additional VC runtime it installed.
> 3: Not sure if related, because I've messed with too many things at once, but I ended up using the installer from LOOT's Github releases. Not from Nexus, not the 7z archive from the Github releases, the installer. I was getting some uncaught exceptions and prompts to launch winedbg before.

> Edit 2: Problem 3 was an actual problem, not just my messy workflow. LOOT version 0.20.0 doesn't work. Version 0.19.1 does. Is 0.20.0 working for anyone else? 

The problem mentioned with version 0.20.0 has since been fixed by the LOOT team, they now even provide a Linux build of some sort, but I've sort-of abandoned Skyrim modding in fall.

**Comment by rockerbacon** [comment]
I've seen reports of this being an issue specific to a few LOOT versions, and that newer versions should work as expected. 

Since this issue hasn't seen activity in quite a while, I'll be closing it. We can revisit it if the problem pops up again and there's something the installer can do about it.
