### ISSUE TITLE
NVSE trying to install to wrong directory

### ISSUE THREAD

**Issue by Cupcake-VGC** [rockerbacon/modorganizer2-linux-installer#477]
I'm trying to install MO2 for FNV, but it's cancelling my installation partway through. Looking through the terminal output, the only thing I'm seeing is that it's trying to install NVSE to a different directory than where my New Vegas installation is located, and when that directory doesn't exist, it cancels the entire install. Here's my output after running install.sh:

INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/cupcake/.steam/debian-installation'
INFO: steam not found in '/home/cupcake/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/cupcake/.steam/debian-installation'
INFO: selected install directory '/mnt/9f4d7724-d53e-4871-9062-b09d193083b7/MO2/FNV'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing existing JDK installation in '/home/cupcake/.steam/debian-installation/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing JDK in '/home/cupcake/.steam/debian-installation/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/mnt/9f4d7724-d53e-4871-9062-b09d193083b7/MO2/FNV/modorganizer2'
INFO: installing script extender in '/home/cupcake/.steam/debian-installation/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/cupcake/.steam/debian-installation/steamapps/common/Fallout New Vegas'
cp: target '/home/cupcake/.steam/debian-installation/steamapps/common/Fallout New Vegas' is not a directory
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'

Is there a file I need to change so it can install where it's supposed to, or something else to fix this issue? I have a small SSD for my file system, which is why my Steam games are all installed to another drive, so I'd rather not reinstall the game to my main SSD. I may also be wrong about what the problem is, since I'm fairly new to this sort of Linux in general, but I know that on my old windows install the script extender needed to be in the same directory as the game's executable. Thanks in advance!

**Comment by rockerbacon** [comment]
Will be handled in #496
