### ISSUE TITLE
mo2 installs successfully, launching fo4 on steam shows a terminal for a second, then closes.

### ISSUE THREAD

**Issue by KoboDev** [rockerbacon/modorganizer2-linux-installer#485]
mo2 is working correctly? I ran it through wine, it works. Also not sure f4se is the issue.

its like 2am writing this, It may seem like other issues but im running all on latest.
i've been looking at current issues and closed ones trying to fix this.
I have reinstalled mo2 multiple times for proton 6.3-8.
I need help. Help me find the logs to see if it makes any, help me fix fallout 4 to  launch mo2, and help me get mods working so i can shove an 10mm smg into an anime girls face.

**Comment by michael811au** [comment]
I was getting a similar thing with Oblivion and Fallout 4

I'm on openSUSE 15.5
/home/user is on sda
/storage/Games is on sdb with a symlink to /home/user/Games

I was installing mo2 into a folder on sdb with no luck loading the games from Steam.
Today on a whim I installed mo2 into /home/user/mo2 for both games and mo2 loads from steam.

Maybe this info will help

**Comment by rusilac** [comment]
i fixed this by deleting/moving f4se_loader.exe in the Fallout 4 folder, launching Fallout 4 from steam, then moving f4se_loader.exe back into the Fallout 4 folder

**Comment by FakeMichau** [comment]
> i fixed this by deleting/moving f4se_loader.exe out of the Fallout 4 folder, launching Fallout 4 from steam, then moving f4se_loader.exe back into the Fallout 4 folder

Same for me. But I found a workaround.

Renaming f4se_loader to f4se_loader2 (for example) and using the renamed file in mo2 allows me to launch the game without having to rename the file every time.

It's likely that something in the launch process tries to launch f4se_loader if it exists and mo2 is then skipped.
Another thing I'm seeing is that the game sometimes just needs to be launched few time before it doesn't crash, it just works™
