### ISSUE TITLE
Operation Canceled due to "Invalid file magic number" error 

### ISSUE THREAD

**Issue by grayandgrainy810** [rockerbacon/modorganizer2-linux-installer#487]
When trying to install MO2 for fallout new vegas in Konsole, I get the error File "/home/deck/.local/pipx/venvs/protontricks/lib/python3.9/site-packages/protontricks/steam.py", line 436, in iter_appinfo_sections raise SyntaxError("Invalid file magic number") 

I made sure to install protontricks and made sure that fallout new vegas runs in proton 6.3-8 before running the install. Fallout NV is also installed on my steam decks SSD.

**Comment by JSH4a** [comment]
Same issue here running on PopOS! 22.04

**Comment by JSH4a** [comment]
Issue seemed to be caused by protontricks. Realized the version installed by Ubuntu 22.04 (and PopOS!) was out of date. Installed the flatpack version instead to get the most up to date one which resolved the issue.

**Comment by rockerbacon** [comment]
@JSH4a Ubuntu 22.04 protontricks packages are outdated, according to the packaging status at [https://github.com/Matoking/protontricks](https://github.com/Matoking/protontricks).

@grayandgrainy810 you seem to be on a Steam Deck, so you should try the Flatpak version of Protontricks. Let me know if the Flatpak version doesn't work either and I'll reopen the issue.
