### ISSUE TITLE
Some issues with installation - hopefully worked around it

### ISSUE THREAD

**Issue by michaldybczak** [rockerbacon/modorganizer2-linux-installer#488]
Since the installer asks for very antiquated version of proton, I just used the newest ProtonGE instead. Maybe that was the issue.
Anyway, the installation process broke at this point:

```
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_01_05'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

(zenity:57147): Gtk-WARNING **: 00:45:53.697: Theme parsing error: gtk.css:7188:40: Junk at end of value for background-color

```

Luckily, since all files seemed to be there, I just launched ModOrganizer.exe with Protontricks and chose the prefix with Skyrim SE. Then I got the MO window and the rest seemed to run fine.

It looks like the app needs to be updated. Most people use Proton Experimental or GE nowadays. However, the issue seems to be with gtk, so maybe it's not about the Proton. I'm using:

Operating System: Manjaro Linux (testing branch - more on pair with Arch packages)
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.4.1-1.0-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Alienware
Product Name: Alienware 17 R3
System Version: 1.13.1

**Comment by rockerbacon** [comment]
The logs you posted are from the clean-up process and the relevant information would be above that. Always provide full logs.

The Zenity log indicates GTK can't properly parse the theme you're using, but it seems to be just a warning and unrelated to whatever problem you experienced.
