### ISSUE TITLE
Installing stops at downloading Winetricks. 

### ISSUE THREAD

**Issue by ConvexTlc97** [rockerbacon/modorganizer2-linux-installer#490]
Not sure why but the installer refuses to download wine tricks when it gets to that point. the bar just doesn't move and nothing happens. 

EDIT: tried an older version 4.2.4 and the same issue happened. will try again tomorrow. for all I know it is a server issue for wine tricks. 

Version 4.3.0

HARDWARE: Steam Deck

INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: selected install directory '/home/deck/Games/mod-organizer-2-newvegas'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
/home/deck/Downloads/mo2installer-4_3_0/step/download_external_resources.sh: line 82:  9530 Hangup                  "$download" "$winetricks_url" "$downloaded_winetricks"
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by Nastas95** [comment]
I have the same problem. Stuck on "Downloading Winetricks"

**Comment by rockerbacon** [comment]
The script for downloading files is the same for all of them. Since you could download all files except for winetricks, this was probably just a temporary network issue.

I ran the script today and had no problems with any downloads. Please, try again and let me know if the problem is gone.

**Comment by ConvexTlc97** [comment]
So I have tried again with the newer 4.3.1 version on my desktop too and I am having the same issues. going to try with a VPN and see if that may be the issue.

**Comment by ConvexTlc97** [comment]
So with a VPN worked. seems I am having a weird internet issue that is causing this but have a work around now.
