### ISSUE TITLE
Could not find game with APPID '22490'

### ISSUE THREAD

**Issue by zoidsberg** [rockerbacon/modorganizer2-linux-installer#491]
Installing for Fallout New Vegas is failing with the above error. I believe this is because New Vegas' APPID is actually 22380, but I'm not knowledgeable enough to fix the installer.

**Comment by rockerbacon** [comment]
There are two distributions of Fallout New Vegas, one for the Russian market (appid 22490) and another for everyone else (appid 22380). Both options are presented when selecting the game you want to install, make sure you are selecting the correct one.

**Comment by zoidsberg** [comment]
I had been using the Lutris installer, which only gave one option for "Fallout New Vegas." Installing without Lutris allowed me to see all the options and select the non-Russian version.
