### ISSUE TITLE
Adding mo2 shorcut to bypass the gui doesnt work with other launch options

### ISSUE THREAD

**Issue by Saigaiii** [rockerbacon/modorganizer2-linux-installer#504]
While the mo2 shortcut works, I cannot add the launch option I want because the shortcut seems to disable it. Is there a way around this?

Edit: For example: 'moshortcut://"Tale of Two Wastelands"'  RADV_PERFTEST=gpl %command%. This would fix stuttering issues I have encountered, but running this just crashes when I hit play. If I take out %command%, then it proceeds to run, but doesn't seem to load the 2nd launch option.

**Comment by rockerbacon** [comment]
You want to have parameters after the executable file, so what you want to put in the launch options text box is:
```
RADV_PERFTEST=gpl %command% 'moshortcut://"Tale of Two Wastelands"'
```


The basic syntax for executing something is:
```
[Environment variables...] [executable] [parameters...]
```

In the launch options, `%command%` is a placeholder which Steam will replace with its own environment variables, executable and parameters, which is in a format similar to this:
```
ENV_1=abc ENV_2=fgh /proton/wine --param_1 --param_2 run game_executable.exe
```

The string you were trying to use translates to something like:
```
'moshortcut://"Tale of Two Wastelands"' RADV_PERFTEST=gpl WINE_ENV_1=abc /proton/wine run Fallout.exe
```
Reordering the shortcut parameter to appear after `%command%` will place it at the end of the execution after all replacements occur and achieve what you want.
