### ISSUE TITLE
mkdir fail

### ISSUE THREAD

**Issue by coolst3r** [rockerbacon/modorganizer2-linux-installer#511]
mkdir: cannot create directory ‘/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c/java’: No such file or directory
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by rockerbacon** [comment]
Please provide the full logs. The issue is that `/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c` does not exist, most likely cause is that first time setup was not run on Steam.

**Comment by coolst3r** [comment]
> Please provide the full logs. The issue is that `/mnt/veracrypt4/SteamLibrary/steamapps/compatdata/489830/pfx/drive_c` does not exist, most likely cause is that first time setup was not run on Steam.

i did run first time setup

**Comment by coolst3r** [comment]
restarted seemed to fix it also launched it again
