### ISSUE TITLE
Installation fails due to missing Proton prefix

### ISSUE THREAD

**Issue by SpencerHD2020** [rockerbacon/modorganizer2-linux-installer#513]
It fails trying to create this directory "/run/media/mmcblk0p1/steamapps/compatdata/489830/pfx/drive_c/java" I scanned this in terminal and it appears that up to /run/media/mmcblk0p1/steamapps/ exists but the "steamapps" dir does not have a "compatdata" dir. I saw a similar issue where someone mentioned not running first time setup on steam. Not sure what this means, but I did set the proton version and ensure no launch options and start the game and create a save prior to running install.sh

INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game not found in '/home/deck/.local/share/Steam'
INFO: game found in '/run/media/mmcblk0p1'
INFO: selected install directory '/home/deck/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using wget backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using wget backend
INFO: fetching remote resource at 'https://skse.silverlock.org/beta/skse64_2_02_03.7z'
INFO: downloading 'https://skse.silverlock.org/beta/skse64_2_02_03.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z' to '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'
mkdir: cannot create directory ‘/run/media/mmcblk0p1/steamapps/compatdata/489830/pfx/drive_c/java’: No such file or directory
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/skyrimspecialedition_skse64_2_02_03'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks

**Comment by rockerbacon** [comment]
What Proton version are you using?

**Comment by rockerbacon** [comment]
Please provide the output for the command:
```
flatpak run 'com.github.Matoking.protontricks' -c 'echo $WINEPREFIX' 489830
```

**Comment by SpencerHD2020** [comment]
Sorry just seeing this, will provide when I get home here shortly

**Comment by SpencerHD2020** [comment]
Proton 8.0-3 and above command gives below output. I can try running the command it suggests:

protontricks (WARNING): Protontricks does not appear to have access to the following directories:
 /run/media/mmcblk0p1

To fix this problem, grant access to the required directories by copying the following command and running it in a terminal:

flatpak override --user --filesystem=/run/media/mmcblk0p1 com.github.Matoking.protontricks

You will need to restart Protontricks for the settings to take effect.
protontricks (WARNING): Steam library folder /run/media/mmcblk0p1 not found. Protontricks might not have access to the directory.
Steam app with the given app ID could not be found. Is it installed, Proton compatible and have you launched it at least once? You can search for the app ID using the following command:
$ protontricks -s <GAME NAME>

**Comment by SpencerHD2020** [comment]
After giving protontricks access to that dir command prints:

/home/deck/.local/share/Steam/steamapps/compatdata/489830/pfx

**Comment by SpencerHD2020** [comment]
For what it is worth running install.sh throws the same error after this though

**Comment by Sockwater** [comment]
Wanted to mention that I am having the same issue on desktop. My protontricks does appear to have access to the directories but I have the same error. Checked with older versions of the installer and I get the same issue, so it does not seem to be a regression in the latest version. I'll try to provide any additional info as needed to help!

**Comment by SpencerHD2020** [comment]
Can try that after work today and update

**Comment by SpencerHD2020** [comment]
Can confirm that moving the game to internal storage (vs. MicroSD) allowed it to install. However that is all I have done thus far. Thanks!
