### ISSUE TITLE
Unable to locate files/folders?

### ISSUE THREAD

**Issue by Neko-Silver** [rockerbacon/modorganizer2-linux-installer#523]
I installed a crash logging mod, but I am unable to locate the actual folders the files are in. Through MO2 I'm able to see where the files supposedly are ( C:users/steamuser/skyrim/ ) but I'm not even able to find a folder called steamuser anywhere.

**Comment by rockerbacon** [comment]
“C:\” is the root of the Proton prefix.

Since you intend on manipulating mod files from outside of MO2, you probably want to have a portable instance so that all files will be stored in the MO2 itself.
