### ISSUE TITLE
error during install.sh

### ISSUE THREAD

**Issue by Code-Slave** [rockerbacon/modorganizer2-linux-installer#524]
Just grabbed latest and cant even get to install as i get this error. any ideas?

INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/smayes/.steam/debian-installation'
INFO: game not found in '/home/smayes/.steam/debian-installation'
INFO: steam not found in '/home/smayes/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/gaming/SteamLibrary'
Traceback (most recent call last):
  File "/home/smayes/bin/protontricks", line 309, in <module>
    steam_lib_dirs = get_steam_lib_dirs(steam_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smayes/bin/protontricks", line 223, in get_steam_lib_dirs
    library_folders = parse_library_folders(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smayes/bin/protontricks", line 196, in parse_library_folders
    key, value = match.group(1), match.group(2)
                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Code-Slave** [comment]
running budgie 23.04

**Comment by rockerbacon** [comment]
Protontricks is broken on your system. Make sure you’re using a recent version.

You can also try installing it from other sources (pipx, flatpak, etc).

**Comment by Code-Slave** [comment]
weird. running latest from flathub
