### ISSUE TITLE
Warning!!!

### ISSUE THREAD

**Issue by Mobiacikaka** [rockerbacon/modorganizer2-linux-installer#533]
Do not use this script if you don't know what it is doing!!!
It has possibility to remove your game data in compatdata forever!

**Comment by Mobiacikaka** [comment]
What the fuck are you guys doing???
rm -rf $game_compatdata???
Who give you the right to do this???
The dumbass who wrote this script knows nothing about linux. All he care about is his fucking games.
Suck my dick please.

**Comment by rockerbacon** [comment]
The installer asks "Would you like to delete your current game prefix and
create a new one?" and the user can accept or decline the operation.
