### ISSUE TITLE
mo2 won't open throught steam

### ISSUE THREAD

**Issue by Ggargur** [rockerbacon/modorganizer2-linux-installer#538]
i tried opening mo2 throught steam, right after it finished installing, but i won't open. It closes right after trying to open. 

If i try opening the .exe file manually it opens just fine.

I'm using proton 8.0-4.

LOG:
[steam-489830.log](https://github.com/rockerbacon/modorganizer2-linux-installer/files/13359291/steam-489830.log)

EDIT: even when trying installing after opening it manually, the mods won't install.

**Comment by Patola** [comment]
Yeah, same error message as I have:
```
61594.414:012c:0130:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0000000228280000: builtin
INFO: read executable location 'Z'
ERROR: cannot execute 'Z' - No such file or directory
```

**Comment by Ggargur** [comment]
> Yeah, same error message as I have:
> 
> ```
> 61594.414:012c:0130:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\msvcrt.dll" at 0000000228280000: builtin
> INFO: read executable location 'Z'
> ERROR: cannot execute 'Z' - No such file or directory
> ```

i fixed it by changing the installation folder to /home/[myUser]/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/modorganizer2. I was probably related to how I installed my steam client using flatpak.
