### ISSUE TITLE
New Skyrim version breaks SKSE

### ISSUE THREAD

**Issue by fighuass** [rockerbacon/modorganizer2-linux-installer#549]
The current release of MO2 Linux has an older SKSE version which doesn't work with the new Skyrim version.

**Comment by Smirnaff** [comment]
You can fix that manually by changing the file `gamesinfo/skyrimspecialedition.sh` like this:

`game_steam_subdirectory="Skyrim Special Edition"
game_nexusid="skyrimspecialedition"
game_appid=489830
game_executable="SkyrimSELauncher.exe"
game_protontricks=("xaudio2_7=native")
game_scriptextender_url="https://skse.silverlock.org/beta/skse64_2_02_05.7z"
game_scriptextender_files=( \
	"skse64_2_02_05/Data" \
	"skse64_2_02_05/skse64_1_6_1130.dll" \
	"skse64_2_02_05/skse64_loader.exe" \
)
`
and then reinstall MO2

**Comment by MrShelbySann** [comment]
`game_steam_subdirectory="Skyrim Special Edition" 
game_nexusid="skyrimspecialedition" 
game_appid=489830 
game_executable="SkyrimSELauncher.exe" 
game_protontricks=("xaudio2_7=native") 
game_scriptextender_url="https://skse.silverlock.org/beta/skse64_2_02_05.7z" 
game_scriptextender_files=( \ 
	"skse64_2_02_05/Data" \ 
	"skse64_2_02_05/skse64_1_6_1130.dll" \ 
	"skse64_2_02_05/skse64_loader.exe" \ 
) 
`
Thanks @Smirnaff! It works, here's proper formatting for easier copy-paste!

**Comment by fighuass** [comment]
Thank you!
