### ISSUE TITLE
install.sh: 6: set: Illegal option -o pipefall; when trying to install install.sh

### ISSUE THREAD

**Issue by MZO940** [rockerbacon/modorganizer2-linux-installer#556]
I'm running the command `sudo sh install.sh` in the mo2installer-4.4.0 folder. Have even tried running `chmod +x install.sh` as someone on reddit suggested. No idea what's wrong here.

**Comment by rockerbacon** [comment]
Never run anything with sudo unless explicitly instructed to.
The script is not meant to be run with sh, but with bash.

**Comment by MZO940** [comment]
Running `bash install.sh` now, getting an invalid file magic number error now. [Here's the log of the terminal](https://paste.ee/p/Kt11b)

**Comment by rockerbacon** [comment]
#545
