### ISSUE TITLE
Can't manually install mods ?

### ISSUE THREAD

**Issue by hawari21** [rockerbacon/modorganizer2-linux-installer#558]
So, i did manages to install MO2 on Linux mint setup and some of mods from nexus are downloading as well. Until, i tried to install some mod from 3rd party website and manually put my mods in "Download" tab in MO2 but it didn't put on my tab and tried it several times but still same. Is there a way to install mod manually via MO2 ?

**Comment by rockerbacon** [comment]
Yes, manual downloads work fine. Check some tutorials online on how to install mods manually with Mod Organizer 2.
