### ISSUE TITLE
Unconfirmed ENB support

### ISSUE THREAD

**Issue by Kutabe** [rockerbacon/modorganizer2-linux-installer#561]
Looks like latest [v0.496](http://enbdev.com/mod_fallout4_v0496.htm) ENB works without any (major) issues, at least in Fallout 4.
If confirmed, README should be updated.

**Comment by rockerbacon** [comment]
Could you also confirm which preset you're using? Some effects are known to break under DXVK and some presets may introduce their own shaders which may or may not work properly.

**Comment by Kutabe** [comment]
Yes, I used [Reactor ENB](https://www.nexusmods.com/fallout4/mods/57321), haven't tried any others yet. There's a problem with opening ENB menu, though. I think it can't capture input, haven't found a workaround yet, but it isn't a huge issue, for me, at least. Might look into it later. Also, [vkBasalt](https://github.com/DadSchoorse/vkBasalt) and [ReShade-steam-proton](https://github.com/kevinlekiller/reshade-steam-proton) could be mentioned somewhere,

**Comment by Liswolynski** [comment]
You can trigger the menu by changing the settings in "enblocal.ini", specifically the line "OpenOnStartup=false/true". If you set it to "true", the menu will pop up when the game launches, allowing you to tweak it to your liking. Unfortunately, I haven't found a way to close the menu once it's open. The only option is to close the game after you're done tweaking, then change the line in the config file back to "OpenOnStartup=false".

I use this method in Skyrim, and it should work similarly in Fallout 4.
