### ISSUE TITLE
MO2 won't open. (Skyrim SE)

### ISSUE THREAD

**Issue by DuskTheSnep** [rockerbacon/modorganizer2-linux-installer#564]
i went through all the installation stuff, it said it installed successfully, but it just refuses to run mo2 when i click play
(video attached that shows what happens when i try)
https://github.com/rockerbacon/modorganizer2-linux-installer/assets/97635080/52e0dc8e-6b58-49b9-9087-02740daee07b

i'm on mint, running skyrim on proton 8.0-5

**Comment by DuskTheSnep** [comment]
sorry i'm an idiot i clicked the close button by accident

**Comment by Kutabe** [comment]
Could you share launch options (right click on game in steam library - properties - general - launch options) and maybe logs (try running `steam steam://run/1946180` in a terminal)?

**Comment by DuskTheSnep** [comment]
the launch options were just "WINEDLLOVERRIDES="xaudio2_7=n,b" PULSE_LATENCY_MSEC=90 %command%" which i copied from a random forum post to try and fix an issue involving game audio

and uh, it opened the creation kit when i did the steam terminal thing? here are the logs

[2024-01-24 20:45:27] Performing checksum verification of executable files
[2024-01-24 20:45:27] Verification complete

Steam logging initialized: directory: /home/duskthesnep/.steam/debian-installation/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe8f059c0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe8f041f0
/usr/share/themes/Mint-Y-Dark-Purple/gtk-2.0/main.rc:1053: error: unexpected identifier 'direction', expected character '}'
steamwebhelper.sh[27190]: Runtime for steamwebhelper: defaulting to /home/duskthesnep/.steam/debian-installation/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[27190]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
CAppInfoCacheReadFromDiskThread took 19 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 27352
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 0ms
BuildCompleteAppOverviewChange: 337 apps
RegisterForAppOverview 1: 7ms
RegisterForAppOverview 2: 7ms
/bin/sh\0-c\0/home/duskthesnep/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1946180 -- /home/duskthesnep/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/duskthesnep/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/duskthesnep/.steam/debian-installation/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/duskthesnep/.steam/debian-installation/steamapps/common/Skyrim Special Edition/CreationKit.exe'\0
chdir "/home/duskthesnep/.steam/debian-installation/steamapps/common/Skyrim Special Edition"
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
WARNING: discarding _NET_WM_PID 2 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 5 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
Setting breakpad minidump AppID = 1946180
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198171303111 [API loaded no]
Game 1946180 created interface STEAMAPPLIST_INTERFACE_VERSION001 / AppList
Game 1946180 created interface STEAMAPPS_INTERFACE_VERSION008 / Apps
Game 1946180 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_004 / HTMLSurface
Game 1946180 created interface STEAMHTTP_INTERFACE_VERSION002 / HTTP
Game 1946180 created interface STEAMINVENTORY_INTERFACE_V002 / Inventory
Game 1946180 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / MusicRemote
Game 1946180 created interface STEAMMUSIC_INTERFACE_VERSION001 / Music
Game 1946180 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / ParentalSettings
Game 1946180 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / RemoteStorage
Game 1946180 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / Screenshots
Game 1946180 created interface STEAMUGC_INTERFACE_VERSION010 / UGC
Game 1946180 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 1946180 created interface STEAMVIDEO_INTERFACE_V002 / Video
Game 1946180 created interface SteamController006 / Controller
Game 1946180 created interface SteamFriends015 / Friends
Game 1946180 created interface SteamMatchMaking009 / Matchmaking
Game 1946180 created interface SteamMatchMakingServers002 / MatchmakingServers
Game 1946180 created interface SteamNetworking005 / Networking
Game 1946180 created interface SteamUser019 / User
Game 1946180 created interface SteamUtils009 / Utils
Game 1946180 method call count for IClientAppManager::GetCurrentLanguage : 1
Game 1946180 method call count for IClientAppManager::GetAvailableLanguages : 1
Game 1946180 method call count for IClientAppManager::GetAppInstallState : 2
Game 1946180 method call count for IClientUtils::RecordSteamInterfaceCreation : 22
Game 1946180 method call count for IClientUtils::GetSteamUILanguage : 1
Game 1946180 method call count for IClientUtils::GetAppID : 24
Game 1946180 method call count for IClientUser::GetSteamID : 1
Uploaded AppInterfaceStats to Steam

**Comment by DuskTheSnep** [comment]
could the bug i'm experiencing have to do with the fact that im using the flatpak version of steam? the terminal thing opened an entirely new instance with none of my games installed

**Comment by rockerbacon** [comment]
> and uh, it opened the creation kit when i did the steam terminal thing?

Because you were given a command to open Creation Kit, @Kutabe mixed things up. These logs won't help.

If you're using Flatpak, some manual steps may be required depending on where you installed MO2. See the instructions provided [in the Flathub page](https://flathub.org/apps/com.valvesoftware.Steam) on adding games to another drive and make sure Steam has access to the location where you installed MO2.
If that was your case, keep in mind that you need to have the game and MO2 installed on the same drive because MO2 doesn't work across multiple file systems.

**Comment by DuskTheSnep** [comment]
i just used flatseal to give steam permissions to all my files and it worked, thank you. i dont know how i didn't think of that before.
