### ISSUE TITLE
NXM hander does not work if MO2 is already open using non-flatpak install

### ISSUE THREAD

**Issue by RobinVdBroeck** [rockerbacon/modorganizer2-linux-installer#574]
Whenever I try to open nxm links, it does not work if mo2 is already open. It however does seem to work when it's closed.

Output:
`# bash  /home/robin/.local/share/modorganizer2/modorganizer2-nxm-broker.sh "nxm://skyrimspecialedition/mods/12604/files/35407?key=TeJjzif9jlcp34aQxE6FnQ&expires=1707152283&user_id=4872276"`
```bash
23919
INFO: sending download 'nxm://skyrimspecialedition/mods/12604/files/35407?key=TeJjzif9jlcp34aQxE6FnQ&expires=1707152283&user_id=4872276' to running Mod Organizer 2 instance
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8 (found in $LANG)
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[24439]: W: Container startup will be faster if missing locales are created at OS level
pressure-vessel-adverb[24439]: E: Failed to execute child process "/var/games/hdd/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-service" (No such file or directory)
steam-runtime-launch-client[24480]: E: Unable to connect to any of the specified bus names

(zenity:24812): Gtk-WARNING **: 23:22:12.510: Locale not supported by C library.
	Using the fallback 'C' locale.

(zenity:24812): Gtk-WARNING **: 23:22:12.521: Unknown key gtk-modules in /home/robin/.config/gtk-4.0/settings.ini

(zenity:24812): Adwaita-WARNING **: 23:22:12.573: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```

it seems to be an error about a specific file not existing, it however, does exist:
`file /var/games/hdd/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-service`
```bash
/var/games/hdd/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-service: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=d4c21142347bdbcdbd9df38692dabf4b6a902f5c, stripped
```
I do have read + execute access on this file.

I've installed mo2 on a non-flatpak install of steam, on arch, using wine-9.1 and protontricks 11.1.1

**Comment by rockerbacon** [comment]
What Proton version? Are you launching MO2 from Steam?

**Comment by RobinVdBroeck** [comment]
I use proton 8.0-5 but I also tried to use the latest GE release without any success.

**Comment by rockerbacon** [comment]
And are you launching MO2 from Steam?

**Comment by RobinVdBroeck** [comment]
I have the problem both when I launch MO2 originally from steam (by pressing play on skyrim SE) and when launching mo2 trough an nxm link (which just launches steam as far as I can tell from looking at the bash script.)

**Comment by rockerbacon** [comment]
protontricks-launch is unable to access “/var/games/hdd/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/pressure-vessel/bin/steam-runtime-launcher-service” and Steam is also failing to connect to some bus that it requires.
I have a hunch the problem is related to your use of the “/var” directory for the Steam library but you’ll need to report your problem to the Protontricks devs at [their GitHub](https://github.com/Matoking/protontricks/issues) to get any clarification on the matter.

This is the command the NXM link handler should be executing:
```
protontricks-launch --appid "489830" "$HOME/.config/modorganizer2/instances/skyrimspecialedition/modorganizer2/nxmhandler.exe" "nxm://skyrimspecialedition/mods/12604/files/35407?key=TeJjzif9jlcp34aQxE6FnQ&expires=1707152283&user_id=4872276"
```
Give it a double check to ensure you get the same results and make sure to include it in your eventual Protontricks issue.
