### ISSUE TITLE
Post-installation, Fallout 4 won't launch and neither does Mod Organizer

### ISSUE THREAD

**Issue by PetrichorVoices** [rockerbacon/modorganizer2-linux-installer#580]
i installed Mod Organizer 2, everything worked fine, and then i went to launch Fallout 4 and neither it nor Mod Organizer 2 opened. Steam will start to run Fallout 4, it'll load for a quarter of a minute, and then it stops as though i'd closed the game. i have Steam Flatpak, using Protontricks Flatpak. i have no experience with any of this so i really don't know what to do

**Comment by rockerbacon** [comment]
Issue is related to Flatpak permissions and/or Steam runtime permissions, plenty of open and closed issues on this already

**Comment by PetrichorVoices** [comment]
> Issue is related to Flatpak permissions and/or Steam runtime permissions, plenty of open and closed issues on this already

i looked through them and i wasn't able to figure out which issues relate to this, can you point me to the specific ones?

**Comment by rockerbacon** [comment]
#564 #526 #285 are a few of them
