### ISSUE TITLE
SKSE won't open

### ISSUE THREAD

**Issue by sorin255** [rockerbacon/modorganizer2-linux-installer#583]
When I try to run SKSE through MO2, it doesn't open a command line window and goes straight to launching Skyrim SE. All mods are then disabled and don't load.

It launches just fine if I rename it to SkyrimSE.exe and set MO2 to open the launcher and open it that way. At that point though it can't find SKSE.ini where I'm telling it to use Skyrim.exe as the game executable.

Switching logs to debug I notice that that the process just completes and ends instead of staying open.

**Comment by rockerbacon** [comment]
If you’re having to move files around it’s likely that Steam has partially uninstalled MO2. This may happen if Steam verifies the game files or updates the game. Just run the installer again and it will make sure to restore the files Steam might have removed. 

Also read through the [post install instructions](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md) for details on how to skip the MO2 interface and launch SKSE directly.
