### ISSUE TITLE
SKSE and FINS not running

### ISSUE THREAD

**Issue by XargonWan** [rockerbacon/modorganizer2-linux-installer#584]
Greetings,

I want to report a weird issue or a possible bug: SKSE is not recognized and FINS cannot start.

So why these issue are connected?
I'm not totally sure but it seems like that modorganizer2 cannot call external exes.

Environment:
- Steam Deck
- Skyrim SE/AE from Steam (latest, no downgrades, so I believe is 1.6.1170)
- Proton 8.0-5 (latest Proton 8 available on Steam as today)
- SKSE 2.2.6
- Prefix cleaned? Yes
- modorganizer2 and Skyrim are installed on an external, ext4, sd card
- Paths seems correct and refreshed

Whenever I try to load FINS from modorganizer2 it is prepearing to run it, calling the exe (apparently) then exiting. This process is about 20 seconds.
Whenever I run SKSE from modorganizer2 apparently is calling SKSE but when on Skyrim mods such as RaceMenu and SkyUI are prompting about that SKSE is not running.
So I believe that modorganizer2 cannot run external executables.

If I browse the vfs it seems to be all right.

Last summer I was running modded Skyrim correctly with the same setup type, however this setup is completely new as many things are changed on the modding side and on mine (I reset the Steam Deck), modorganizer2 and the mods are fresh.

**Comment by XargonWan** [comment]
I completely removed mo2, skyrim and started from the beginnin, skse seems like it's loading but FINS is still not running.

**Comment by rockerbacon** [comment]
Closing as stale
