### ISSUE TITLE
Flatpak Proton on Flatpak Steam Not Supported During Installation

### ISSUE THREAD

**Issue by rehashedsalt** [rockerbacon/modorganizer2-linux-installer#590]
This is a really silly series of complexities, but it highlights an error condition that isn't handled correctly.

---

I run Fedora Kinoite, which is immutable at runtime outside of Flatpaks. Thus, I have Flatpak Steam installed. I also, for convenience, have a Flatpak version of Proton-GE installed to keep my Proton-GE up-to-date (this is a moot point since the flatpak is unmaintained but bear with me).

During installation for F:NV, with this Flatpak Proton selected as the compatibility tool for the game, mo2installer yells at me that I didn't do the "set up a clean Proton prefix" step correctly, even though I did and such a prefix exists:

> A prefix for the selected game could not be found. Make sure you have followed the instructions on creating a clean prefix

What's *actually* happening is that protontricks can't execute Proton (because it's in a random Flatpak), and this error is masked by the wrapper script.

Example output:

```
# With Proton Flatpak selected
$ STEAM_LIBRARY=~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/ protontricks -c 'echo $WINEPREFIX' 22380
protontricks (ERROR): Could not find configured Proton installation!
protontricks (ERROR): Active Proton installation could not be found automatically.
Proton installation could not be found!
(returns 1)
```

```
# With Proton Experimental selected
$ STEAM_LIBRARY=~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/ protontricks -c 'echo $WINEPREFIX' 22380
protontricks (WARNING): Current Steam Runtime not recognized by Protontricks.
/var/home/[redacted]/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/22380/pfx
(returns 0)
```

```
# With Proton Experimental selected and no Wine prefix
$ STEAM_LIBRARY=~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/ protontricks -c 'echo $WINEPREFIX' 22380
Steam app with the given app ID could not be found. Is it installed, Proton compatible and have you launched it at least once? You can search for the app ID using the following command:
$ protontricks -s <GAME NAME>
(returns 1)
```

The workaround I used was to just not use this deprecated Flatpak Proton setup and instead use the one Steam downloads itself.

If you wanted to handle this error condition, you could capture STDERR in `utils/protontricks.sh` and analyze it. You could also justifiably write this off as a 4-dimensional corner-case.

**Comment by rehashedsalt** [comment]
To clarify: the issue arises because mo2installer is being run in the context of the host (or a Podman container), not the Steam Flatpak context as Flatpak would set it up. There's no good solution for that problem, but an error message that hints toward this and recommends using a Steam-downloaded Proton wouldn't be out-of-place.

**Comment by rockerbacon** [comment]
There are two parts to this issue.

First is the issue of Protontricks not being able to find the prefix. Unless I'm missing something, it looks like something that could only be implemented in Protontricks itself.

For the error message, it's definitely a bug. The installer should detect that the protontricks command failed and report that as the problem. No need to parse stderr when the process exits with an error code.
I have noticed that the [get_prefix](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/b835fd8ed053ce405bd47dd63245c74803b6a493/utils/protontricks.sh#L49) function intentionally suppresses protontricks errors (appends "|| true" to the execution). I can't remember why this is there, but it probably shouldn't be.
