### ISSUE TITLE
Installer cancels itself 

### ISSUE THREAD

**Issue by TOMAS4098** [rockerbacon/modorganizer2-linux-installer#600]
Hi so new problem, after electing a folder to install mo2 in the install runs fine and starts downloading stuff but out of nowhere It cancels itself and says check terminal for details, well on konsole it says error: could not fetch ‘https://github.com/adpotium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip’ 

im not sure what this means or how to fix it, can anyone help?

**Comment by StellarHarbour** [comment]
Same, it can't download anything anymore...

**Comment by rockerbacon** [comment]
#596
