### ISSUE TITLE
Operation canceled. Check the terminal for details during "Add a new entry"

### ISSUE THREAD

**Issue by StellarHarbour** [rockerbacon/modorganizer2-linux-installer#601]
Directory '/home/stellarharbour/Games/mod-organizer-2-skyrim' does not exist. Would you like to create it?
I choose "Yes"
Then it crashes afterwards with "Operation canceled. Check the terminal for details"

**Comment by StellarHarbour** [comment]
INFO: all dependencies met

(zenity:53844): Gtk-WARNING **: 19:53:18.077: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini
INFO: selected game 'skyrim'
INFO: found Steam in '/home/stellarharbour/.local/share/Steam'
INFO: game found in '/home/stellarharbour/.local/share/Steam'
INFO: steam not found in '/home/stellarharbour/.var/app/com.valvesoftware.Steam/.local/share/Steam'

(zenity:54062): Gtk-WARNING **: 19:53:26.135: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini

(zenity:54062): Gtk-CRITICAL **: 19:53:26.293: GtkBox 0x555640fc0b90 reports a minimum height of 219, but minimum height for width of 1048576 is 229. Expect overlapping widgets.

(zenity:54062): Gtk-CRITICAL **: 19:53:26.293: GtkBox 0x555641028ac0 reports a minimum height of 119, but minimum height for width of 1048576 is 129. Expect overlapping widgets.
INFO: proceeding with existing prefix

(zenity:54086): Gtk-WARNING **: 19:53:30.717: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini
INFO: user confirmed prefix setup

(zenity:54261): Gtk-WARNING **: 19:53:35.119: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini

(zenity:54283): Gtk-WARNING **: 19:53:36.563: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini
INFO: selected install directory '/home/stellarharbour/Games/mod-organizer-2-skyrim'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'

(zenity:54309): Gtk-WARNING **: 19:53:38.422: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini
mkdir: cannot create directory ‘/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07’: File exists

(zenity:54332): Gtk-WARNING **: 19:53:38.695: Unknown key gtk-modules in /home/stellarharbour/.config/gtk-4.0/settings.ini

**Comment by cprin21** [comment]
See issue #596 , as of right now wget in more up to date/rolling distros like Arch and the Fedora 40 Beta is having problems with downloading archives to the /tmp directory. Edit download.sh in the utils folder to remove the section related to wget.

```
if [ -n "$DOWNLOAD_BACKEND" ]; then
	download_backend="$DOWNLOAD_BACKEND"
elif command -v wget >& /dev/null; then
	log_info "using wget backend"
	download_backend="wget"
elif command -v curl >& /dev/null; then
	log_info "using curl backend"
	download_backend="curl"
else
	log_error "either wget or curl must be installed on this system"
	exit 1
fi
```

Becomes

```
if [ -n "$DOWNLOAD_BACKEND" ]; then
	download_backend="$DOWNLOAD_BACKEND"
elif command -v curl >& /dev/null; then
	log_info "using curl backend"
	download_backend="curl"
else
	log_error "either wget or curl must be installed on this system"
	exit 1
fi
```

**Comment by StellarHarbour** [comment]
@cprin21 Did you found out why does it stopped working? Fedora 40 stable release in few days and there's still time to report issue

**Comment by rockerbacon** [comment]
#596

**Comment by fontivan** [comment]
> See issue #596 , as of right now wget in more up to date/rolling distros like Arch and the Fedora 40 Beta is having problems with downloading archives to the /tmp directory via modorganizer2-linux-installer. Edit download.sh in the utils folder to remove the section related to wget.
> 
> ```
> if [ -n "$DOWNLOAD_BACKEND" ]; then
> 	download_backend="$DOWNLOAD_BACKEND"
> elif command -v wget >& /dev/null; then
> 	log_info "using wget backend"
> 	download_backend="wget"
> elif command -v curl >& /dev/null; then
> 	log_info "using curl backend"
> 	download_backend="curl"
> else
> 	log_error "either wget or curl must be installed on this system"
> 	exit 1
> fi
> ```
> 
> Becomes
> 
> ```
> if [ -n "$DOWNLOAD_BACKEND" ]; then
> 	download_backend="$DOWNLOAD_BACKEND"
> elif command -v curl >& /dev/null; then
> 	log_info "using curl backend"
> 	download_backend="curl"
> else
> 	log_error "either wget or curl must be installed on this system"
> 	exit 1
> fi
> ```
> 
> What this does is forces modorganizer2-linux-installer to fall back on curl for its downloading purposes.

Editing the script is not necessary at least on on Fedora 40, I was able to proceed by using the DOWNLOAD_BACKEND variable that is already baked in:
```
DOWNLOAD_BACKEND=curl ./install.sh
```

**Comment by xylorp** [comment]
I edited the bash file and ran the install script again but experienced a new error. I tried troubleshooting by launching the game under multiple different proton versions but got the same error:

/install.sh
INFO: all dependencies met

(zenity:310247): Gtk-WARNING **: 01:04:15.756: Unknown key gtk-modules in /home/z/.config/gtk-4.0/settings.ini

(zenity:310247): Adwaita-WARNING **: 01:04:15.795: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
INFO: selected game 'newvegas'
INFO: steam not found in ''
INFO: found Steam in '/home/z/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/z/.var/app/com.valvesoftware.Steam/.local/share/Steam'

(zenity:310364): Gtk-WARNING **: 01:04:19.127: Unknown key gtk-modules in /home/z/.config/gtk-4.0/settings.ini

(zenity:310364): Adwaita-WARNING **: 01:04:19.165: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
INFO: user confirmed prefix setup
ERROR: no prefix found

(zenity:310452): Gtk-WARNING **: 01:04:24.330: Unknown key gtk-modules in /home/z/.config/gtk-4.0/settings.ini

(zenity:310452): Adwaita-WARNING **: 01:04:24.368: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:310452): Gtk-CRITICAL **: 01:04:24.480: GtkBox 0x555d796f1670 reports a minimum height of 179, but minimum height for width of 1048576 is 189. Expect overlapping widgets.

(zenity:310452): Gtk-CRITICAL **: 01:04:24.480: GtkBox 0x555d796fe8b0 reports a minimum height of 79, but minimum height for width of 1048576 is 89. Expect overlapping widgets.
