### ISSUE TITLE
Please help me! Pt2 

### ISSUE THREAD

**Issue by Mattster28** [rockerbacon/modorganizer2-linux-installer#604]
I’m trying to play Fallout New Vegas on Steam Deck with Mods but when I try to install the MO2installer in the Konsole I get an error.
I tried the #601 Quick fix in the download.sh folder but I’m still getting an error. Please help me! 
![IMG_8456](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/167602349/dca067a2-a372-497f-bd37-7d787bea15ba)

**Comment by Mattster28** [comment]
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: selected install directory '/home/deck/Games/mod-organizer-2-newvegas'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using curl backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing existing JDK installation in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing JDK in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/deck/Games/mod-organizer-2-newvegas/modorganizer2'
INFO: installing script extender in '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/Data/NVSE/nvse_config.ini'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_1_4.dll'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_editor_1_4.dll'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_loader.exe'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_steam_loader.dll'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by rockerbacon** [comment]
Don’t “bump” issues
