### ISSUE TITLE
Please help... I cannot, for the life of me, make it work.

### ISSUE THREAD

**Issue by Proficiency-git** [rockerbacon/modorganizer2-linux-installer#605]
First thing first.

I'm running Vanilla OS, Steam installed via Flatpak. Protontricks installed via flatpak. Game (New vegas) installed via Flatpak.

Installation success. I click launch, nothing happens. Click Play on Steam, nothing happens. 

Installation folder exist, it modify the game folder by adding NVSE (usually done this AFTER I installed the game myself by following Viva New Vegas guidelines).

On each shortcut I tried clicking run to, everything comes up as error. Error 5:0000065434 to be exact.

Please, if anyone know any solution, let me now.

**Comment by rockerbacon** [comment]
Install logs

**Comment by Proficiency-git** [comment]
> Install logs

Okay, I managed to make the installation works, by allowing Files permission to the Steam app, via Flatseal app. 

But then when it launched, none of the launch option works. It's always crashes and gives 5:0000065434 error message. I tried to replace the NVSE and it still does not work. 

I'll give you the installation log files later. Appreciate all your work. Thank you.

**Comment by rockerbacon** [comment]
I'll be closing this one, then. The load error 5 problem is being tracked in #588, any additional information you get can be submitted there.
