### ISSUE TITLE
Fallout 4 Update Imminent, How to Halt Updates For The Game?

### ISSUE THREAD

**Issue by Greymanz** [rockerbacon/modorganizer2-linux-installer#610]
Since this method of installing MO2 hijacks the Steam Play button, pressing play will cause the game to update in the next couple of days which will break many mods in the short term.
Is there any solution for stopping game updates by running the game as an executable shortcut instead of through the official game listing? And using the games wine prefix as well to avoid issues?

**Comment by rockerbacon** [comment]
#544 is open for the discussion of update prevention methods.
