### ISSUE TITLE
path to the steam executable cannot be found

### ISSUE THREAD

**Issue by ballinbill** [rockerbacon/modorganizer2-linux-installer#616]
probably a simple issue, but when i open mo2 it opens, but it says it cannot start steam, and that the "path to the steam executable cannot be found" How do i direct mo2 to the steam executable on linux?

**Comment by rockerbacon** [comment]
You don't, you're supposed to launch MO2 from Steam not the other way around. How exactly are you launching MO2?

**Comment by ballinbill** [comment]
MO2 doesn't open through steam for me, it just says playing and then closes.

**Comment by rockerbacon** [comment]
And how did you get to the "path to the steam executable cannot be found" error?

**Comment by swjzielinski** [comment]
I believe if you open MO2 with Wine, it will say that it can't find Steam. 


> MO2 doesn't open through steam for me, it just says playing and then closes.

Do you, by any chance, have the game on an NTFS drive?

**Comment by ballinbill** [comment]
No, it's on a ext4 drive. I've just opened it again after following the instructions, and opening it on steam still just says launching, and then automatically switches to the play button. Nothing opens, and the only way to open MO2 is through wine.

**Comment by swjzielinski** [comment]
What Proton version do you have?

**Comment by rockerbacon** [comment]
Don’t open through Wine. You either have Flatpak permission problems or Steam runtime permission problems. MO2 doesn’t launch because Steam cannot access the executable, plenty of other issues on that already
