### ISSUE TITLE
How to launch from steam without updating?

### ISSUE THREAD

**Issue by undo-k** [rockerbacon/modorganizer2-linux-installer#617]
The new Fallout 4 update dropped today and I don't want to risk breaking any of the mods I have installed. I have updates set to "Only update this game when I launch it" in Steam's properties, but I'm not sure how to launch MO2 without going thru Steam. Any advice?
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/46544691/5b54b4b6-c43f-4b10-b622-3f7d41416f9a)

**Comment by JND94** [comment]
You can't, I just cracked my own game and then used heroic games launcher to launch "Fallout4 Launcher.exe" (which is the redirector to modorganizer2) with the same proton and proton prefix I was using, for this, F4SE needs additional params in modorganizer2: -forcesteamloader (the same you do with gog version)
That's Steam for ya, not as consumer-friendly like some say uh??

**Comment by parazyd** [comment]
It broke for me. Update happened, and now Steam starts the vanilla launcher.

**Comment by wins1ey** [comment]
I got it working by adding Fallout4Launcher.exe to Lutris and set the wine prefix to the Fallout 4 one at:
`$HOME/.local/share/Steam/steamapps/compatdata/377160/pfx`

**Comment by wins1ey** [comment]
This is a better solution: https://www.nexusmods.com/fallout4/mods/81471

**Comment by LinuxfarmerHH** [comment]
Had blocked Steam for some weeks from updates, by setting the Appmanifest file to "chattr +i". But remind that Bethesda blocks you from Creations if this is set.

Tipp source here: [https://www.reddit.com/r/skyrimmods/comments/18c54wo/how_to_prevent_update_on_linux_a_solution/](url)
