### ISSUE TITLE
Prefix not found when using Bottles and GOG game

### ISSUE THREAD

**Issue by Lippiece** [rockerbacon/modorganizer2-linux-installer#621]
Hi. Thanks for your work.

I'm trying to run
`STEAM_LIBRARY=/home/lippiece/.local/share/bottles/bottles/TES-IV-Oblivion/ ./install.sh`

The prefix is already created and has the path above. However, I'm getting
```
A prefix for the selected game could not be found.
```

I'm looking for recommendations for this issue and for running MO2 with Bottles in general.

Related to #594

**Comment by QuaiGoner** [comment]
Same Issue here

**Comment by rockerbacon** [comment]
Refer to #399
