### ISSUE TITLE
xNVSE version detected as 6.2x with 6.3 installed (Steam Deck Bazzite/Fedora)

### ISSUE THREAD

**Issue by leinaht** [rockerbacon/modorganizer2-linux-installer#623]
Bazzite/Fedora on Steam Deck, Fallout New Vegas installed via Steam to internal SSD, successfully installed ModOrganizer2 4.6.1 using the fix in #596. Attempting to install [Alternate Start](https://www.nexusmods.com/newvegas/mods/82319) which has JIP LN and ShowOff xNVSE among the prerequisites, both of which require xNVSE version 6.3+. Installed the latest xNVSE (6.3.5b at time of writing), but when launching the game both JIP and ShowOff throw errors that only 6.2 is installed and 6.3 is needed at minimum, leaving the following in Notifications:

>The failed plugins are:
  • JIP LN NVSE version 5721 (jip_nvse.dll, JIP LN NVSE Plugin) reported as incompatible during query.
  • ShowOffNVSE Plugin version 175 (ShowOffNVSE.dll, ShowOff xNVSE Plugin) reported as incompatible during query.

I can still load into the game and start a new save but end up stuck in a black void so I'm assuming JIP and SO aren't loading in as they can't see that I have xNVSE 6.3 installed. I've tried installing xNVSE from Nexus and also from file (after a full reinstall of the game and ModOrganizer 2 between attempts) but still get the version mismatch error. Not sure if the issue is with the other mods themselves or the version detection in ModOrganizer2 (or something else entirely)

**Comment by leinaht** [comment]
Actually as I'm reinstalling again I noticed that ModInstaller2 2.4.4 is being downloaded  in the logs rather than 2.6.1. logs attached
[mo2 logs.txt](https://github.com/rockerbacon/modorganizer2-linux-installer/files/15143050/mo2.logs.txt)

**Comment by rockerbacon** [comment]
The installer will apply NVSE 6.2. If some of your mods are warning about an outdated NVSE version, it's probably because your manual install didn't go well.

I've opened #624 for updating NVSE.
