### ISSUE TITLE
Cannot start Storage

### ISSUE THREAD

**Issue by TheNukeLore** [rockerbacon/modorganizer2-linux-installer#626]
getting an issue labeled cannot start storage, this is while a fresh install of both fnv and mo2l. both flatpak and proton tricks are flatpaks but this issue is currently halting me from playing. I looked at the location mentioned and there is no "Storage" file or directory.

**Comment by TheNukeLore** [comment]
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/56121120/550c5316-90c0-46c5-b8c2-30138357ec15)

**Comment by swjzielinski** [comment]
Can you create that file?

**Comment by rockerbacon** [comment]
This happens because of #387. Follow post-install instructions and run the original game launcher at least once
