### ISSUE TITLE
I keep getting this error when I select Fallout New Vegas.

### ISSUE THREAD

**Issue by Krunkdo** [rockerbacon/modorganizer2-linux-installer#632]
(deck@steamdeck mo2installer-4.4.0)$ ./install.sh
INFO: all dependencies met
ERROR: no game selected
(1)(deck@steamdeck mo2installer-4.4.0)$

**Comment by rockerbacon** [comment]
Latest installer version is 4.6.2. You’re using 4.4.0

**Comment by Krunkdo** [comment]
Sorry I should've mentioned I tried multiple launcher versions including 4.6.2 and still got the same error.

(deck@steamdeck mo2installer-4.6.2)$ ./install.sh
INFO: all dependencies met
ERROR: no game selected
(1)(deck@steamdeck mo2installer-4.6.2)$

**Comment by rockerbacon** [comment]
This can only happen due to user error or a broken Zenity installation. See what happens if you run this command:
```
zenity --height=450 --list --radiolist --text="test" --hide-header --column="checkbox" --column="option_value" --column="option_text" --hide-column=2 '' "correct" "Select this" '' "incorrect" "Do not select this" && echo "All is good!" || echo "Broken zenity or nothing selected"
```

**Comment by Krunkdo** [comment]
This is what I get.
(deck@steamdeck ~)$ zenity --height=450 --list --radiolist --text="test" --hide-header --column="checkbox" --column="option_value" --column="option_text" --hide-column=2 '' "correct" "Select this" '' "incorrect" "Do not select this" && echo "All is good!" || echo "Broken zenity or nothing selected"
All is good!
(deck@steamdeck ~)$

**Comment by rockerbacon** [comment]
Your selected option should have been printed right before “All is good!”, but for some reason Zenity isn’t doing that in your system.

Could you check your Zenity version?
```
zenity —version
```

And also what binary is being used:
```
command -v zenity 
```

Have you done any significant changes to your Steam Deck or is it mostly stock?

**Comment by Krunkdo** [comment]
I just got the Steam Deck recently so it should be mostly stock.
(deck@steamdeck ~)$ zenity —version
You must specify a dialog type. See 'zenity --help' for details
(255)(deck@steamdeck ~)$ command -v zenity 
/usr/bin/zenity
(deck@steamdeck ~)$

**Comment by rockerbacon** [comment]
My apologies, the phone's auto-corrector converted two dashes into a long bar. The version command is:
```
zenity --version
```

**Comment by Krunkdo** [comment]
(deck@steamdeck ~)$ zenity --version
3.32.0
(deck@steamdeck ~)$
