### ISSUE TITLE
"No prefix found" on certain installations

### ISSUE THREAD

**Issue by swjzielinski** [rockerbacon/modorganizer2-linux-installer#635]
#576 #611, #615 and possibly others

So, what is the problem here?

@ChanceNCounter reported:
>Works for FO4, doesn't work for FO3: GOTY

I asked if both games were on the same drive, but unfortunately I got no reply.
So I ask again, can someone with this error check if it works on another drive?

My earlier thoughts:
>I think the problem is that the script can't find the prefix location. (wow, no way)
The function "load_prefix_locations" from step/clean_game_prefix.sh returns an empty string. However, I've asked one person in this issue to run the same command as the function does, and it did produce the expected result.

**Comment by rockerbacon** [comment]
Please, don’t intentionally create duplicates. It ends up scattering information even more.
