### ISSUE TITLE
NXM handler sort of working?

### ISSUE THREAD

**Issue by JimBimBum** [rockerbacon/modorganizer2-linux-installer#639]
i've it worked at first but after so many reinstalls it's kind of broken? not on flatpak, yes proton 8

doesn't download mods when MO2 is open, just gives a zenity pop up saying it can't but when it's not running. no error, launches MO2, steam says FNV is running and it downloads but then it goes back to the first issue meaning i have to download one at a time while ii's off idk what's causing this glitch. i erased the prefix, mo2 folder that held the install and i just don't exactly know what the problem is.

**Comment by rockerbacon** [comment]
Not enough information. What does the Zenity pop up say?

**Comment by JimBimBum** [comment]
it says something like "Could not download file because there is no Mod Organizer 2 instance " or "failed to download
