### ISSUE TITLE
MO doesn't launch

### ISSUE THREAD

**Issue by OhKayBet** [rockerbacon/modorganizer2-linux-installer#643]
Had issues where MO wasn't launching, figured it out. Now whenever i launch the game there's no audio. Its wasn't a prior issue.

**Comment by rockerbacon** [comment]
Not enough information. No audio suggests a dirty prefix or failure to apply Protontricks

**Comment by OhKayBet** [comment]
Been trying to figure it out. It's not the prefix looking into the logs I see this. 

ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred

Im using wireplumber
