### ISSUE TITLE
Unable to find skyrimse.exe

### ISSUE THREAD

**Issue by Jinma420** [rockerbacon/modorganizer2-linux-installer#645]
I am having an issue when I try to launch games through this app. 
MO2 gives me an error that states that it is unable to find my Skyrimse.exe. 
I would appreciate any help that you are able to provide towards solving this problem.

**Comment by rockerbacon** [comment]
I could not reproduce the issue.

Need more information on that. Do you have prints or error logs? When exactly does it give you an error that it is unable to find the executable?

**Comment by rockerbacon** [comment]
Closing as stale
