### ISSUE TITLE
MO2 tries to open Skyrim Special Edition\SE instead of Skyrim Special Edition

### ISSUE THREAD

**Issue by TepungPadat** [rockerbacon/modorganizer2-linux-installer#646]
So I'm using the latest release (5.0.1) and for some reason MO2 tries to open an extra "SE" folder and the file path becomes .steam\debian-installation\steamapps\common\Skyrim Special Edition\SE instead of \.steam\debian-installation\steamapps\common\Skyrim Special Edition, rendering me unable to open MO2 entirely. I've reinstalled it multiple times, double checking if I accidentally added an SE folder in the file paths, but everything looks as it should (no extra folder, file paths in the folders I want). I've taken some screenshots of the error I get when I try to run MO2, as well as MO2's confirmation page during instance creation to show that I inserted the file paths correctly.

![6ct8bu9rv2](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/169863578/5db8fa80-217f-4b8c-91e0-4fda41509318)

![7vye8h8u93f](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/169863578/0524711e-cb82-49af-962e-c1c5098c24f0)

**Comment by SoakedTofu** [comment]
I think it's because your mod organizer path contains spaces, try renaming your "Skyrim  SE Mods" folder. It's going to break the MO installation though, so you'll have to run the installer again.

**Comment by TepungPadat** [comment]
> I think it's because your mod organizer path contains spaces, try renaming your "Skyrim SE Mods" folder. It's going to break the MO installation though, so you'll have to run the installer again.

Alright, I'll give it a try and get back to you.

**Comment by TepungPadat** [comment]
Wow, it actually worked! Kind of an odd issue to have, but I'm glad it's fixed now. Thanks for the help. Cheers!
