### ISSUE TITLE
Skyrim logo missing, crashes when entering game world, can't fullscreen

### ISSUE THREAD

**Issue by TepungPadat** [rockerbacon/modorganizer2-linux-installer#647]
So after getting it to run smoothly, the first thing I notice is that the Skyrim logo was missing. I didn't think it was a big deal, but then when I tried to enter the game world by entering "coc riverwood" into the console, it immediately crashes to desktop. Furthermore, I can't seem to play the game in fullscreen, as there's an app header at the top of my screen and my taskbar won't automatically disappear.

I have no other mods installed except for 3 creations and the Anniversary Edition plugin.

**Comment by rockerbacon** [comment]
Please keep in mind that all this tool does is install MO2 and integrate it with Proton. If you're experiencing issues in-game, this is not the best place to get help. That said, I could not reproduce your issue.

Make sure you have cleaned your prefix during the install process and are using a recommended Proton version. Make sure your DE of choice does not have any issues with fullscreen Proton applications (and that you've configured your game to run fullscreen, of course). And as always, whenever you have CTDs on Bethesda games, test the game without any mods and slowly introduce them to make sure they're not the culprits.
