### ISSUE TITLE
Set winecfg "Graphics/Automatically capture the mouse in full-screen windows" option

### ISSUE THREAD

**Issue by gmn42** [rockerbacon/modorganizer2-linux-installer#648]
After (re)running the installer for Fallout 4 (and resetting the wine environment), I need to manually run `protontricks 377160 winecfg` and set the "Automatically capture mouse in full-screen windows" option to prevent the mouse from escaping the monitor running the game (it is a secondary monitor on a dual-head setup).  It would be helpful if the installer could do this automatically, as it is a [general problem with FO4 on dual-monitor setups](https://www.reddit.com/r/linux_gaming/comments/rjaq74/fallout_4_cursor_wont_lock_into_game/).  When this option is set, I can still access the desktop and other windows by pressing the Super key.  I don't believe this option would cause problems when running on a single display setup, but that would need to be tested.

![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/78309818/767e982c-4e57-4e88-befd-7b23f9c51b97)

I have no idea how to script winecfg now, but will try to figure it out and contribute a patch if needed.  It may well be helpful for other games supported by the installer, but I have no way to test.

**Comment by rockerbacon** [comment]
First step is investigating how to automate this, the rest is easy. I do know that Winecfg is just a tool for configuring registry keys, and automating registry key modifications is fairly simple.

Here are some resources from WineHQ for people who may want to look into this:
- [Configuring Wine](https://wiki.winehq.org/Wine_User%27s_Guide#Configuring_Wine)
- [Winecfg](https://wiki.winehq.org/Winecfg)

**Comment by gmn42** [comment]
Okay, I found the registry entry (below), but it looks like it's a supported winetricks command, so the easy fix is just to set `game_protontricks=("xaudio2_7=native" "grabfullscreen=y")` in gamesinfo/fallout4.sh.  Should i submit a PR?

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"GrabFullscreen"="Y"
```

**Comment by rockerbacon** [comment]
Even better if there’s a winetricks verb. Feel free to send a PR
