### ISSUE TITLE
Cannot Complete Install: Protontricks not detected by install.sh

### ISSUE THREAD

**Issue by mbsergent** [rockerbacon/modorganizer2-linux-installer#668]
I have attempted to install the program using the instruction on the github page and the install fails with the following error: 

/home/USER/ModOrganizer2/step/check_dependencies.sh: line 13: /home/USER/ModOrganizer2/utils/protontricks.sh: Permission denied
ERROR: missing dependencies protontricks
/home/USER/ModOrganizer2/step/check_dependencies.sh: line 23: /home/USER/ModOrganizer2/utils/dialog.sh: Permission denied

I am attempting to install the program on the most up to date version of Arch with Protontricks version 1.11.1-1 installed. I have also ran "protontricks-desktop-install." Any help would be appreciated.

**Comment by rockerbacon** [comment]
You're being denied permission for executing the script itself. Most likely cause is files missing the execution flag.

**Comment by mbsergent** [comment]
install.sh and all .sh files within the step directory are set as executable. It still gives me the same error.
