### ISSUE TITLE
Nothing Starting from Steam after installing.

### ISSUE THREAD

**Issue by Eisdaemon** [rockerbacon/modorganizer2-linux-installer#671]
I have Fallout 4 installed and wanted to install MO2. 
After using it, Nothing starts through steam anymore. If I verify the integrity of the files, Fallout starts again as normally. 

I have steam installed through flatpak as well as protontricks. I had no error during installation. I use KDE Neon 6.0, so Ubuntu based.

**Comment by rockerbacon** [comment]
Duplicate of #656
