### ISSUE TITLE
does not proceed with installation beyond Protontricks

### ISSUE THREAD

**Issue by Thorazines** [rockerbacon/modorganizer2-linux-installer#674]
Log messages:

Found Steam directory at /home/marco/.local/share/Steam
Using default Steam Runtime at /home/marco/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 3 Steam library folders
Steam library folder /run/media/marco/Steam/SteamLibrary not found. Protontricks might not have access to the directory.
Multiple compatdata directories found for app 1172470
Currently logged-in Steam user: thoraz63
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider
No compatibility tool found by reading Steam configuration. Using stable version of Proton as fallback.
Could not find configured Proton installation!
Active Proton installation could not be found automatically.

**Comment by Thorazines** [comment]
I didn't think I had to install Proton and in fact the installation stops at the same point.

**Comment by rockerbacon** [comment]
We do not maintain Protontricks.

If you have checked that Protontricks works outside of the installer and can point to a problem in the installer, then we can do something about it. Otherwise, you must take your issue to the Protontricks maintainers.
