### ISSUE TITLE
Installation step 4 not working on Steam Deck – "permission denied"

### ISSUE THREAD

**Issue by ThreepQuest64** [rockerbacon/modorganizer2-linux-installer#675]
I've followed the installation steps on the Steam Deck and after trying to execute .install.sh I get this log, in full:

` /run/media/deck/de5e2de9-b405-4611-b7d5-afb01a0b10d2/mo2 installer/step/check_dependencies.sh: line 13: /run/media/deck/de5e2de9-b405-4611-b7d5-afb01a0b10d2/mo2 installer/utils/protontricks.sh: Permission denied
ERROR: missing dependencies protontricks
/run/media/deck/de5e2de9-b405-4611-b7d5-afb01a0b10d2/mo2 installer/step/check_dependencies.sh: line 23: /run/media/deck/de5e2de9-b405-4611-b7d5-afb01a0b10d2/mo2 installer/utils/dialog.sh: Permission denied
`

Protontricks has beeninstalled prior to this via Discovery as described by the Requirements paragraph. However, I do not know what bash, curl, wget or zenity is. I could not find neither of those terms via Discovery nor the Application Launcher.

**Comment by rockerbacon** [comment]
You’re having permission erros to run the installer itself. I see you’re running from an external media device so I’ll suggest doing everything from the Steam Deck (download, extract, execute)

**Comment by ThreepQuest64** [comment]
When I had the issue I did donwload the archive from a Windows PC and moved it to the Steam Deck's external SD card. Executing alone from the _internal_ drive after moving the folder from the external SD card wasn't enough. Oddly, _downloading_ the archive from the Steam Deck and _then_ extracting _and_ executing did the trick.

In short: download, extract, execute all from the SD – as mentioned by rockerbacon – helped.
