### ISSUE TITLE
After changing gameinfo/starfield.sh to download the correct SFSE It's still looking for the wrong version.

### ISSUE THREAD

**Issue by jSQrD-dev** [rockerbacon/modorganizer2-linux-installer#682]
Modified gameinfo/starfield.sh

```bash
game_steam_subdirectory="Starfield"
game_nexusid="starfield"
game_appid=1716740
game_executable="Starfield.exe"
game_protontricks=("xaudio2_7=native")
game_scriptextender_url="https://sfse.silverlock.org/download/sfse_0_2_8.7z"
game_scriptextender_files=( \
	"sfse_0_2_8/sfse_1_12_30.dll" \
	"sfse_0_2_8/sfse_loader.exe" \
)

```

I've even manually added the files ant this is what I get. I know this is the right version because I tested it on a Windows Partition.

![Screenshot_20240611_072613](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/39681015/9f6da120-5597-4cb5-99c5-d9c60b66a956)

**Comment by jSQrD-dev** [comment]
#679 could also be what's causing this

**Comment by jSQrD-dev** [comment]
![Screenshot_20240611_073601](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/39681015/30254670-b748-4ef5-ad15-567a818a9b78)

**Comment by jSQrD-dev** [comment]
Another observation if I Validate Game Files and install Mo2 with Winetrick it works

**Comment by tdtooke** [comment]
If you edit 'gamesinfo/starfield.sh' you have to build it again.  Otherwise you can download it from https://sfse.silverlock.org/ and unzip that into your game directory overwriting the old one.

**Comment by Preman-Kampung** [comment]
> If you edit 'gamesinfo/starfield.sh' you have to build it again. Otherwise you can download it from https://sfse.silverlock.org/ and unzip that into your game directory overwriting the old one.
> 
> Edit: I just noticed on reddit that Starfield is releasing a creation kit today, I think?? If that's the case I can practically guarantee SFSE will have to be updated yet again. It might be best to just wait a few days and manually update SFSE from their site.

They have update the SFSE and I already tried using that and put in game's folder but still the MO2 looking for the previous version. I already tried build and changing  starfield.sh just like above post.

**Comment by tdtooke** [comment]
There's only one way that can happen.  sfse_loader.exe is the old version.

**Comment by Preman-Kampung** [comment]
> There's only one way that can happen. sfse_loader.exe is the old version.

Already update the game, but I found the problem. I delete _Starfield.exe also Starfield.exe  for good measure then validate the game and rebuild MO2 using installer.

**Comment by rockerbacon** [comment]
The installer doesn’t overwrite script extender files. Once you have SFSE installed, you need to update it manually.
