### ISSUE TITLE
Mangohud?

### ISSUE THREAD

**Issue by halfmexican** [rockerbacon/modorganizer2-linux-installer#685]
I apologize if this is irrelevant, but I was wondering how one would go about using mangohud with the modded games? I'm trying to limit the FPS of FNV. I tried adding ``mangohud`` to launch options to no avail.

**Comment by rockerbacon** [comment]
It’ll work as long as you use the global setup (MANGOHUD=1 environment variable). Using mangoapp (Steam deck overlay) is also an option but its setup can be quite complicated.

If all you want is an FPS limiter, you don’t need manmangohud at all, DXVK has a built in limiter that you can enable with a simple dxvk.conf file. Docs on the file [here](https://github.com/doitsujin/dxvk/wiki/Configuration#configuration-file)
