### ISSUE TITLE
New Vegas on ArchLinux issues

### ISSUE THREAD

**Issue by GlowstoneUnknown** [rockerbacon/modorganizer2-linux-installer#688]
Running Arch, New Vegas won't launch at all past Proton 4.11, so that's the version I have to make the prefix on, but after running the install.sh, nothing launches at all when I attempt to run the game from Steam on 4.11, I've managed to get MO2 to launch on Proton 9.0, but then from there I can't launch the game, and while it's going through the setup phase, it complains about a Read-only INI file. I'm super lost on what to do from here, I've reinstalled the game several times, tried using Glorious Eggroll (still unable to launch the game at all), and this is my last resort.

**Comment by GlowstoneUnknown** [comment]
![Screenshot from 2024-06-17 15-43-39](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/157577956/ff53f71f-d013-4d75-a727-371656ec0e4d)
![Screenshot from 2024-06-17 15-43-25](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/157577956/813e8e14-f921-465a-b887-b58fd28ad166)
This is all that happens when I try to launch the game.

**Comment by GlowstoneUnknown** [comment]
![Screenshot from 2024-06-17 15-43-25](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/157577956/813e8e14-f921-465a-b887-b58fd28ad166)
![screenshotedited](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/157577956/a85e41e2-a1e8-4d4c-b795-fc4c2a7c8d81)
This is all that happens when I try to launch the game.

**Comment by rockerbacon** [comment]
If you can’t get the game to launch with Proton 9.0 there’s nothing that can be done by the installer. You need to go to the Arch community for help.
