### ISSUE TITLE
MO2 extremely unstable and can't seem to be able to access certain directories in the data folder randomly

### ISSUE THREAD

**Issue by BirbOwner** [rockerbacon/modorganizer2-linux-installer#689]
I decided to get back into modding Skyrim after a while and decided to wipe everything clean, do a fresh install of everything, and the mod organizer app itself works fine, its just that it can't seem to access some files found in the vfs when executing anything, which causes major problems with things like fnis and just starting the game in general because the files will include texture directories with meshes, and whole esps and mods go missing as well. The logs will show a long list of directories and plugins that can't be found, for example, "[2024-06-17 22:23:38.626 E] failed to open directory 'riften': 0xc000011f", and the files shown in the log seem to go completely missing in the mod organizer, completely disappearing from the data folder and the esp load list, but not the mod list itself. There seems to be absolutely no reason for this to happen. I also tried creating a global instance where everything was located inside the prefix, which didn't seem to help at all, so it can't be an issue with accessing files outside of the prefix. All of this is really weird because I've used this workaround in the past, and mo2 and fnis had just worked perfectly, but now it's all broken and I don't know why,

please help thanks ;w;

**Comment by rockerbacon** [comment]
I could not reproduce and by the lack of other reports on the matter I doubt there’s an issue with the installer.
We do not maintain USVFS nor the Wine systems that make it work. You need to go through the proper support channels for those systems.
