### ISSUE TITLE
Starfield MO2 won't sort plugins

### ISSUE THREAD

**Issue by Skyknight320** [rockerbacon/modorganizer2-linux-installer#691]
When using MO2 with starfield, there is no option to sort the plugins, as the button is greyed out

**Comment by rockerbacon** [comment]
Unless there’s some indication that your issue is caused by this installer, there’s nothing to be done.
You should take this issue to the MO2 developers, if it’s a limitation of MO2, or to the Wine developers, if it’s a behavior disparity between Windows and Wine.
