### ISSUE TITLE
Font messed up

### ISSUE THREAD

**Issue by Rain-Gayming** [rockerbacon/modorganizer2-linux-installer#695]
The font on it is really messed up, letters are different thicknesses and some dont show up at all.
![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/120071361/2485aa68-89ba-4aa8-8806-02dc400cae66)

**Comment by genericanimegirl** [comment]
I also had this issue, fontsmooth-rgb needs to be enabled,(theres a couple other ones they might also need to be) just open protontricks, click the clack then select the default wine prefix, then change settings and its in that list.
