### ISSUE TITLE
Wine 9.0 Not Supported?

### ISSUE THREAD

**Issue by Samshanan** [rockerbacon/modorganizer2-linux-installer#696]
Hello, I was trying to get MO2 up and running for Skyrim Special Edition but it cancels mid install each time I do it. It says I should look at the console, which I says I need update to Wine 8.0 when I am using the latest Wine version 9.X. I'm not the most technologically savvy person in the world, so if there are any solutions please let me know; I've attached a screenshot of what console said [I made a GitHub account to post this, so I hope I wrote this out with proper etiquette].
![Screenshot from 2024-07-04 16-49-13](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/174749976/65ab78d5-b533-4a87-9ee8-8ca690e62904)

**Comment by Xeraster** [comment]
I can't get this to work with skyrim special edition at all. Both proton 8 and 9 cause the same issue. After installation, it crashes before showing a loading screen or anything.

**Comment by rockerbacon** [comment]
Your error is `brwap: setting up uid map: Permission denied`, which is a Protontricks error.
