### ISSUE TITLE
Closes on the create instance window with Fallout 4 (modern gen update) on Steamdeck

### ISSUE THREAD

**Issue by okimodoki** [rockerbacon/modorganizer2-linux-installer#699]
I'm using Fallout 4 with the modern gen update, from what I've heard most mods have updated for it. I've used this branch of mo2 with nv on steamdeck and it worked perfectly, but for some reason when I try to use it on Fallout 4, the create global/portable instance window will open, but all input stops working other than touchscreen, and even if i click the buttons with touchscreen it doesn't register, after a few seconds the window closes on it's own and nothing happens

**Comment by rockerbacon** [comment]
That's a bug somewhere in Proton, Wine, MO2, Qt, or anything else. Once MO2 has been installed, the installer has done all it's supposed to do.
