### ISSUE TITLE
Mod Organizer 2 won't launch

### ISSUE THREAD

**Issue by NatureofDoom** [rockerbacon/modorganizer2-linux-installer#701]
I installed Mod organizer successfully in the default directory using Proton 8, I gave flatpak Protontricks access to all files, but it won't launch, I tried to reinstall it over five times after re-verifying the games each time. Skyrim SE is on the same drive. Tested Protontricks on other games and it works. I tried running it directly with protontricks, but it wouldn't work. I've restarted a few times as well. I use Kubuntu.

Let me know if you need any other information.

Thanks for your time.

**Comment by rockerbacon** [comment]
Minimum requirement is Proton 9
