### ISSUE TITLE
(Steam Deck) install.sh script not proceeding after game selection

### ISSUE THREAD

**Issue by filteredx3** [rockerbacon/modorganizer2-linux-installer#703]
Hey everybody.

When running install.sh, the script prompts me to select a game. However, after making a selection, the script either does nothing if the game is already installed or indicates that the game isn’t installed when it indeed isn’t installed.
(Logs here : https://pastebin.com/wcVwrqic)

I saw in tutorials it should be asking something about the prefixes, but it’s just doing nothing.

Please help me out. I tried pretty much everything I found on the web and that I could think of at that point. (Tried Multiples games, reinstalled them, tried multiple releases of the repo, cleared compatdata folders, gave all needed permissions to protontricks, reinstalled protontricks, downloaded and tried multiple proton versions with the games. I’ll go bald if I keep scratching my head on this.

**Comment by Grif2501** [comment]
I think I am having the same or at least similar issue. I have updated my system, rebooted and searched for a few days and am now giving up and asking for help. I am attaching a photo of my terminal with the errors I am having In case its an easy and obvious this I have been blind too. (A likely thing.)


![Screenshot_20240716_193520](https://github.com/user-attachments/assets/7d9797e1-3d9d-4b42-bf8a-1c1f59a472a9)

**Comment by filteredx3** [comment]
I found a fix !
I think I found it here : https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470

but I found this fix late at night and I can’t lie I’m not 100% sure this was the solution.

**Comment by Grif2501** [comment]
OMG I missed Steam deck in your title, I don't think this thread will help be, but I will look at what you posted.

**Comment by rockerbacon** [comment]
It’s a Protontricks issue that should be handled by the Protontricks devs
