### ISSUE TITLE
GOG-Version possible

### ISSUE THREAD

**Issue by petemount** [rockerbacon/modorganizer2-linux-installer#704]
Hi rockerbacon, 
First of all, 1,000 thanks for the great and detailed description of how to use the MO2 in Linux. 
You don't know how you help us players and certainly also some modders. 
Now to my little problem: I bought my Skyrim SE from GOG and just wanted to ask if it is basically possible to get the game modded with MO2 if it is not in Steam, but comes from GOG. Should only be a matter of entering the correct path, right?

**Comment by Nathanomir** [comment]
Rockerbacon can give you a more definitive answer, especially where this MO2 is concerned, but I can say this much.

I'm having good success with the GOG version of Skyrim with MO2 via Bottles. Install the game and MO2 in the same bottle, and connect MO2 to the game as usual. Getting MO2 to find your mods is the tricky part. Bottles doesn't like to see things outside WINE, so you'll have to download and install Flatseal so you can set Bottles to see and read all your files. It also has some limitations. A few mods that work on the Steam system won't on Bottles (ENB is a rabid bear in heat and Nemesis will drive you to drink), but if you're used to GOG versions, you're already familiar with that small percentage of mods that won't work on both games. Some fine tuning and tweaking required, but this is Linux.

That's my experience with Bottles. Apparently, GOG games can also be installed and modded through Lutris, but I haven't tried.

**Comment by LinuxfarmerHH** [comment]
Would expand this wishlist to the Lutris client, where users can install a game without the game-manager and be completely update free. The mo2 setup only have to ask for the game folder and can try the executable afterwards.

**Comment by rockerbacon** [comment]
#399

**Comment by gitdunk** [comment]
I have found an alternative way while trying to get fallout 4 GOG working on my device, if you symlink your GOG copy's game folder (where the exes for it are), add the launcher from that symlinked folder to steam, then change the appid in the <gamename>.sh from the gamesinfo folder in this program to the new appid it will install perfectly fine, then the audio wasn't showing up, so I found out that installing faudio and setting every xaudio dll to native,builtin in protontricks winecfg fixed it for my device
