### ISSUE TITLE
Console not opening in Skyrim SE

### ISSUE THREAD

**Issue by Connor-Kolan** [rockerbacon/modorganizer2-linux-installer#706]
I am sorry if this is the wrong place for me to ask this. But I have problems opening the console in Skyrim Special Edition. 
For context I have a german Keyboard and normally open the console with the button left to the 1. But opening it with mo2 it only gives me a white filed with the ^ in it in the bottem left corner.

Distro: debian 12

![image](https://github.com/user-attachments/assets/fe2453b3-bb57-4bab-808f-fa8b5affa70a)

**Comment by LinuxfarmerHH** [comment]
It's "SHIFT ^" in all Bethesda games, no idea why

**Comment by Connor-Kolan** [comment]
That works, thank you very much :)
