### ISSUE TITLE
Cannot install MO2 because of not recognizing my games-folder

### ISSUE THREAD

**Issue by petermartinberg** [rockerbacon/modorganizer2-linux-installer#707]
Hi rockerbacon
I dont understand why intstall.sh does not recognize my game in the following folder "/media/nvme1n1p1/SteamLibrary/steamapps/common/Fallout 3 goty/" although it recognizes "/media/nvme1n1p1/SteamLibary" but not the rest of the path.

Every time I run it it says to me:
INFO: all dependencies met
INFO: selected game 'fallout3_goty'
INFO: found Steam in '/home/tuxpete/.steam/debian-installation'
INFO: game not found in '/home/tuxpete/.steam/debian-installation'
INFO: found Steam in '/home/tuxpete/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game not found in '/media/nvme1n1p1/SteamLibrary'
INFO: game not found in '/home/tuxpete/.var/app/com.valvesoftware.Steam/.local/share/Steam'
ERROR: could not find any Steam library containing a game with appid '22370'. If you known exactly where the library is, you can specify it using the environment variable STEAM_LIBRARY

How should I use STEAM_LIBARY? There is no STEAM_LIBARY variable in all of its files to show the script where the game is. 

Adding the correct path to my game in MO2/utils/list-steam-libaries.sh:

`steam_install_candidates=( \
	"$(readlink -f "$HOME/.steam/root")" \
	"$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam" \
        "/media/nvme1n1p1/SteamLibrary/steamapps/common/" \
)`
doesn't solve the problem either. The install-script fails constantly to install MO2.

I need to install that game, because MO"s Setup requires at least a minimum of one Steam-Game and when this would function I could install my GOG-Version of Skyrim afterwards in with a running MO2 but it doesn't work. What can I do?

**Comment by ArtyIF** [comment]
Try specifying the STEAM_LIBRARY variable, in your case set it to `/media/nvme1n1p1/SteamLibrary` (without the `/steamapps/common/Fallout 3 goty/`).
