### ISSUE TITLE
Crashes when using Steam Deck's keyboard and touchscreen

### ISSUE THREAD

**Issue by Treeways** [rockerbacon/modorganizer2-linux-installer#709]
1. Invoking the Steam Deck's on-screen keyboard with the Steam+X button shortcut crashes MO2, even if no text box is selected, and even if the MO2 window is completely out of focus. This makes it difficult to create new sections or rename anything.
2. Using the touch screen in any capacity crashes MO2, even if the MO2 window is out of focus.
   - Whether you use the official "Gamepad With Joystick Trackpad" layout or the default Web Browser layout restores controller button/trackpad functionality, but the touchscreen crash still occurs.
   - Using an external mouse works perfectly fine.

I'm using the OLED Steam Deck with SteamOS holo 3.5.19.

Related tip for anyone using Proton 9.0: if your file explorer isn't working (ie. you're getting MO2 crashes instead), run Skyrim with [Proton GE 9](https://github.com/GloriousEggroll/proton-ge-custom/releases) instead. This is helpful to locate BethINI in MO2, for instance.

*(This is a duplicate of #669 with more information provided.)*

**Comment by Treeways** [comment]
I have some dump file diagnostics from the crashes; would those be helpful? If so, how should I upload them?

**Comment by gmvi** [comment]
Ran into the touchscreen crash and couldn't find other info on it. Search engines led me here, so here's my solution. I disable the touch input device entirely when launching modorganizer2 via a script invoked in my Steam launch options. It feels pretty hacky, my launch options look like `~/bin/no-touch.sh ; %command% ; ~/bin/no-touch.sh reset`.

https://gist.github.com/gmvi/4a7828ed90da2dc84c4edb1de34e29f1
