### ISSUE TITLE
Is there any possibility to configure to other games? Wanted to use for BG3

### ISSUE THREAD

**Issue by PickMeNow** [rockerbacon/modorganizer2-linux-installer#714]
I wanted to use mod organizer 2 for Baldur's Gate 3, unfortunately I cannot set the install path for another game.

I found the following plugin to be able to use it in windows: 
https://www.nexusmods.com/site/mods/807

Is there anyway to port it to the modorganizer2-linux-installer? 

I tried creating a baldursgate3.sh in gamesinfo but for some reason I am failing :/

**Comment by rockerbacon** [comment]
Requires installer modifications. Look through closed issues and pull requests related to adding support for new games.
