### ISSUE TITLE
Install expects Steam to be where it wasn't installed

### ISSUE THREAD

**Issue by tkd-drums-bass** [rockerbacon/modorganizer2-linux-installer#717]
I'm on Ubuntu 24.04, my goal is to  run Skyrim and Fallout4 with a ton of mods.

Running install.sh yields:

INFO: all dependencies met
INFO: selected game 'skyrim'
INFO: steam not found in ''
INFO: steam not found in **'/home/[me]/.var/app/com.valvesoftware.Steam/.local/share/Steam'**

But Steam is located here:

**/home/[me]/snap/steam/common/.local/share/Steam**

Steam was installed from Steam website.
As far as I know, wine and protontricks are installed okay.

.wine looks like this:

[me]@[me]:~/.wine$ la
dosdevices  drive_c  system.reg  .update-timestamp  userdef.reg  user.reg

install.sh was extracted and executed from:

/home/[me]/Downloads/mo2installer-5.0.3

Should Steam be re-installed?  Should install.sh be run from a different directory?  
Not sure how to proceed with this.

Thanks, and apologies if this is redundant.

EDIT TO ADD:
Possible progress.
I added:

**STEAM_LIBRARY="/home/[me]/snap/steam/common/.local/share/Steam"**

to find-library-for-file.sh per advice in other issue discussions.
Install no longer complains about finding Steam.

Now it says there is no prefix.

AFAIK I've followed directions, i.e. 1) run Steam, 2) play Skyrim for a little bit, 3) exit Skyrim, 4) exit Steam.

Shouldn't that have created the prefix?  What have I misunderstood?

**Comment by wololoArch** [comment]
You dont need to exit steam, when you get the pop-up telling you to run the game for Steam to set up appears, simply run the game, let it configure itself for your hardware, then close the launcher. Then click "continue" or whatever the prompt says and it'll work. I had the same problem as you first time around.

**Comment by tkd-drums-bass** [comment]
Thanks for your suggestion, @wololoArch.  Alas, I tried it, same result.  Here's the REDACTED output of the as-installed script:

REDACTED@REDACTED-GA-78LMT-USB3:~/Downloads/mo2installer-5.0.3$ ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrim'
INFO: steam not found in ''
INFO: found Steam in '/home/REDACTED/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/REDACTED/snap/steam/common/.local/share/Steam'
INFO: user confirmed prefix setup
ERROR: no prefix found

I got past the initial failure to find Steam by creating a symlink.  Still cannot find the prefix.  

Other issues/responses here lead me to think I may have a protontricks (???) problem, but I have no idea how to investigate it.

Any suggestions would be fantastic.  Thanks.

**Comment by rockerbacon** [comment]
Snaps are not supported

**Comment by tkd-drums-bass** [comment]
Ah, I saw no indication of that.  Thanks, it's good to know.  I shall un/reinstall.

**Comment by rockerbacon** [comment]
To further clarify, Snap is not supported by Valve themselves: https://news.itsfoss.com/valve-steam-snap-ubuntu/

Anyone using Snap should instead opt for the official deb package (preferably) or the unofficial Flatpak.
