### ISSUE TITLE
[Question] Are all Proton versions supported?

### ISSUE THREAD

**Issue by Yasand123** [rockerbacon/modorganizer2-linux-installer#724]
This is such a cool project. MO2 is superb and thanks to this I can use it on Linux. Thank you!

I wonder however, do you have to stick to specific Proton versions, or can you use any version you want (including ProtonGE)?

**Comment by rockerbacon** [comment]
There’s no support for anything other than Steam Proton 9.0. You may use Proton GE, TKG or anything else you’d like but these don’t get any testing and any issues exclusive to them should be reported to their respective bug trackers.
