### ISSUE TITLE
Launching Game through MO2 cuases severe graphical issues

### ISSUE THREAD

**Issue by drill558** [rockerbacon/modorganizer2-linux-installer#733]
![glitch](https://github.com/user-attachments/assets/ec4eb822-f8a5-4950-a5ee-7599c5421895)

I installed as instructed, I get no errors, but everything is graphically borked. The default start has audio, but everything else is broken, I tried the skip Helgen start and the image above is what I was left with in the cave. I created a new profile in MO2 without mods to check, and it happens with or without using  mods or skse64. Even launching the base game through this MO2 destroys the game, and I haven't the slightest clue what went wrong.

**Comment by rockerbacon** [comment]
This is just an installer. We do not maintain the graphical stack.

**Comment by drill558** [comment]
something is going on with the installer then because I had to run MO2
through steamtinkerlaunch and everything worked. I switched back
temporarily to your installer and the same thing happened.
