### ISSUE TITLE
Installer crashes after Steam Deck client stable update

### ISSUE THREAD

**Issue by rubenbuelvas** [rockerbacon/modorganizer2-linux-installer#736]
Tried with Fallout New Vegas and Protontricks 1.11.1 installed via the Discover store.

Installer was working fine until [Steam Deck Sept 11 client update](https://store.steampowered.com/news/app/1675200/view/4583064247488721809)

![Screenshot_20240913_094536](https://github.com/user-attachments/assets/7c56f985-9e0c-4eff-b8eb-2075a15a51c9)

**Comment by rockerbacon** [comment]
It’s an issue in Protontricks and can only be handled by the Protontricks dev team.
