### ISSUE TITLE
trying to install MO2 using the script 

### ISSUE THREAD

**Issue by FriendlyConstructGamer** [rockerbacon/modorganizer2-linux-installer#741]
trying to run your install script after installing proton tricks and skyrim special edition, im not having alot of luck. 
running nobora 39, latest version of proton tricks, proton 9.0 compatability layer though steam.
after i do all the previous steps i get to the step of running your script and it tells me 

”: No such file or directory
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/ben/.local/share/Steam'
INFO: steam not found in '/home/ben/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/ben/.local/share/Steam'
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /run/media/ben/nvme1n1p1/NVME Games Librarys/NVME Steam Games not found. Protontricks might not have access to the directory.
Traceback (most recent call last):
  File "/app/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n

![Screenshot_20240916_172739](https://github.com/user-attachments/assets/4e101a1d-6be1-4c5d-a8fe-7ca0c55593b9)
![Screenshot_20240916_172711](https://github.com/user-attachments/assets/2ad8e6f7-83b3-4040-9346-806cb74f2d73)
![Screenshot_20240916_172645](https://github.com/user-attachments/assets/7345a0d1-6393-4d48-a981-c61aff0745c5)

can i have some assistance am i doing something wrong there are a few other people with this same error, help please. dont just close the ticket

**Comment by Anaphylaxis** [comment]
try `PROTON_VERSION="GE-Proton9-11" ./install.sh` replacing the proton version with the one from Steam.
