### ISSUE TITLE
"ERROR: Protontricks did not find a valid prefix directory" during installation

### ISSUE THREAD

**Issue by TepungPadat** [rockerbacon/modorganizer2-linux-installer#744]
The installer gives me this error when installing. This happens after I get the menu to choose which game to install MO2 for. I'm running Bazzite. My Protontricks is indeed up to date.

Full error log:

> INFO: selected game 'skyrimspecialedition'
> INFO: found Steam in '/var/home/user/.local/share/Steam'
> INFO: steam not found in '/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam'
> INFO: game found in '/var/home/user/.local/share/Steam'
> Traceback (most recent call last):
>   File "/usr/bin/protontricks", line 33, in <module>
>     sys.exit(load_entry_point('protontricks==1.11.1', 'console_scripts', 'protontricks')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
>     main(args)
>   File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
>     return cli_func(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
>     proton_app = find_proton_app(
>                  ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
>     tool_app = find_steam_compat_tool_app(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
>     section for section in iter_appinfo_sections(appinfo_path)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
>     raise SyntaxError(
> SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.
> ERROR: Protontricks did not find a valid prefix directory.  Stdout was:\n

**Comment by AZCurt** [comment]
This might be a protontricks problem. Regardless of which prefix i select running protontricks --gui i get the following. For example this is the output after selecting The Elder ScrollsV: Skyrim Special Edition: 489830. It is the same across the board.

See this post. https://github.com/Matoking/protontricks/issues/351 So far he says its a Waylend issue, but I had a similar problem with X11 in Arch and Gentoo.

```
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 274, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 821, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 610, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 540, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number
```
