### ISSUE TITLE
I'm begging you to remove the 7z requirement

### ISSUE THREAD

**Issue by savaxo** [rockerbacon/modorganizer2-linux-installer#749]
This may sound stupid but I just can't make 7z work on my distro, there is no compatible way. All other install methods didn't work in the past and I really love your Installer, it always worked. Right now it's the only thing keeping me from finally switching from windows to linux :'(

Thank you for all your work <3

**Comment by savaxo** [comment]
I'm using Fedora Silverblue

**Comment by rockerbacon** [comment]
Then you should be able to install 7z using rpm-ostree. If that doesn’t work, you should contact the Fedora package maintainers

**Comment by savaxo** [comment]
That's what I tried. But there is no 7z of 7zip for rpm-ostree, only p7zip, but that isn't recognized by Mo2 installer as 7z

**Comment by rockerbacon** [comment]
As far as my knowledge of Fedora goes, the “p7zip” package is the one you want but you may also need additional plugins on top of it. On a standard Fedora distribution, one can use the command `dnf whatprovides 7z` to find the exact package containing the 7z binary.

**Comment by savaxo** [comment]
On the atomic version dnf doesn't work. p7zip shows as installed in terminal but isn't in my launcher or somewhere. 

This might be a extremely dumb question, but for a workaround, could I use the installer on another Distro and copy over the file path?
