### ISSUE TITLE
Please support manually adding a game path outside of steam library folders

### ISSUE THREAD

**Issue by alexbobp** [rockerbacon/modorganizer2-linux-installer#753]
My standard procedure for modding skyrim has always been to move the game out of the steam library folder, so that I don't have to worry about steam updating the game and causing version mismatch issues with mods.

In the case of linux, I have moved the game's install, and then added it back to stem as a non-steam game.  This works fine after creating a steam_appid.txt file in the game's install.  Of course, steam still then shows me as running Skyrim Special Edition, but the point is it won't update the game when I try to run it.

Please provide a way that I can specify a custom game install directory (and if needed, the appid for the manually-added entry, so that your tool can access the proton environment)

**Comment by rockerbacon** [comment]
#594 #544
