### ISSUE TITLE
Problem installing MO2 on Endeavour KDE Plasma

### ISSUE THREAD

**Issue by petermartinberg** [rockerbacon/modorganizer2-linux-installer#763]
Hi there,

I run Endeavour Neo OS and got all necessary stuff so far.

But when I want to install mo2 for Skyrim SE it runs in to problems. As I am not perfectly smart with my semi-rolling Derivate  I report you what the installation process says and I hope someone can help me:
`petermb@EndeavourOSNeo-Machine Mo2-Modorganizer2]$ ls
mo2installer-5.0.3.tar-1
[petermb@EndeavourOSNeo-Machine Mo2-Modorganizer2]$ cd mo2installer-5.0.3.tar-1/
[petermb@EndeavourOSNeo-Machine mo2installer-5.0.3.tar-1]$ ls -a
.  ..  gamesinfo  handlers  install.sh  LICENSE  README.md  steam-redirector  step  utils  workarounds
[petermb@EndeavourOSNeo-Machine mo2installer-5.0.3.tar-1]$ ./install.sh
INFO: all dependencies met

(zenity:64183): Gtk-WARNING **: 19:05:40.404: Unknown key gtk-modules in /home/petermb/.config/gtk-4.0/settings.ini

(zenity:64183): Adwaita-WARNING **: 19:05:40.450: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:64183): Gdk-WARNING **: 19:05:44.050: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)

(zenity:64183): Gdk-WARNING **: 19:05:44.122: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)

(zenity:64183): Gdk-WARNING **: 19:05:44.288: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)
INFO: selected game 'skyrimspecialedition'
INFO: steam not found in ''
INFO: found Steam in '/home/petermb/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/petermb/.var/app/com.valvesoftware.Steam/.local/share/Steam'
pressure-vessel-wrap[64283]: W: Using libdrm from provider system for some but not all architectures! Will take /usr/share/libdrm from provider.
pressure-vessel-wrap[64283]: W: Using libGLX_mesa.so.0 from provider system for some but not all architectures! Will take /usr/share/drirc.d from provider.
pressure-vessel-wrap[64283]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[64283]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework

(zenity:64368): Gtk-WARNING **: 19:05:59.356: Unknown key gtk-modules in /home/petermb/.config/gtk-4.0/settings.ini

(zenity:64368): Adwaita-WARNING **: 19:05:59.402: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:64368): Gtk-CRITICAL **: 19:05:59.712: GtkBox 0x586ea328f2b0 reports a minimum height of 172, but minimum height for width of 1048576 is 182. Expect overlapping widgets.

(zenity:64368): Gtk-CRITICAL **: 19:05:59.712: AdwBin 0x586ea33d3ac0 reports a minimum height of 81, but minimum height for width of 1048576 is 91. Expect overlapping widgets.

(zenity:64368): Gdk-WARNING **: 19:07:26.489: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)

(zenity:64368): Gdk-WARNING **: 19:07:26.492: ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (32) not an integer multiple of theme size (24)
`
![grafik](https://github.com/user-attachments/assets/37be1581-8e9e-47fa-8acc-54a12bbfa534)

**Comment by rockerbacon** [comment]
There are no issues present in the log nor the screenshot.
