### ISSUE TITLE
Black screen on Wabbajack

### ISSUE THREAD

**Issue by rockerbacon** [rockerbacon/modorganizer2-linux-installer#98]
The app is running, but black screen unless I move the cursor around - sometimes the whole interface is fine, sometimes just able to see a widget, like the settings button.  Clicking on things like the settings button DOES work, but the screen is black 75% of the time, and you have to move the cursor around to see what's going on.

_Originally posted by @kleshas in https://github.com/rockerbacon/lutris-skyrimse-installers/issues/93#issuecomment-651530190_

**Comment by rockerbacon** [comment]
The described behavior is very similar to #42

**Comment by kleshas** [comment]
Dumb question:  Where do I put the -Dsun.java2d.d3d=false argument?  in the run.sh like so?:

'/home/kleshas/.local/share/modorganizer2/proton-launcher.sh'  --native 'xaudio2_7' --protonver 5.* -e 'PULSE_LATENCY_MSEC=90' "$@" 489830 '/mnt/veracrypt3/Lutris/Wabbajack.exe' -Dsun.java2d.d3d=false

It doesn't work inside the quotes

**Comment by rockerbacon** [comment]
> Dumb question: Where do I put the -Dsun.java2d.d3d=false argument? in the run.sh like so?:
> 
> '/home/kleshas/.local/share/modorganizer2/proton-launcher.sh' --native 'xaudio2_7' --protonver 5.* -e 'PULSE_LATENCY_MSEC=90' "$@" 489830 '/mnt/veracrypt3/Lutris/Wabbajack.exe' -Dsun.java2d.d3d=false
> 
> It doesn't work inside the quotes, but then I tried putting nonsense at the end and the command still ran.

This is a JVM option, it won't work for Wabbajack. For the Java patchers, this option is add as an argument to the executable within Mod Organizer 2.

**Comment by kleshas** [comment]
Fixed:

'/home/kleshas/.local/share/modorganizer2/proton-launcher.sh' --wined3d --native 'xaudio2_7' --protonver 5.* -e 'PULSE_LATENCY_MSEC=90' "$@" 489830 '/mnt/veracrypt3/Lutris/Wabbajack.exe'

I put in the --wined3d argument manually into run.sh.

**Comment by kleshas** [comment]
What's the best way of getting the wineprefix into win10 mode?  I've been looking for an argument like the --wined3d in the script above, but haven't found it yet.  I know you can do it via WINEPREFIX=xyz winecfg on the command line and then change settings to win10 (not that I've tried yet).

**Comment by kleshas** [comment]
Reinstalled OS, and tried getting this working again.  After many complete reinstalls from scratch (deleting 489830, lutris MO2 folder, winetricks --self-update and making sure the correct vcrun2019 in the cache) I FINALLY got MO2 working - I had to use the "--wined3d" argument in run.sh.  This argument used to be just for getting Wabbajack to work so I'm not sure what the change is.
